-- UNIFIED AI SERVER - DATABASE SCHEMA v3.0
-- Gamification + AI Bots + Legal Compliance

-- ============================================
-- GAMIFICATION SYSTEM TABLES
-- ============================================

-- User Progress & Stats
CREATE TABLE user_progress (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  level INTEGER DEFAULT 1,
  xp INTEGER DEFAULT 0,
  streak INTEGER DEFAULT 0,
  last_active TIMESTAMP DEFAULT NOW(),
  total_workouts INTEGER DEFAULT 0,
  total_points INTEGER DEFAULT 0,
  created_at TIMESTAMP DEFAULT NOW(),
  updated_at TIMESTAMP DEFAULT NOW()
);

-- Points Ledger (Immutable Audit Trail)
CREATE TABLE points_ledger (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  points INTEGER NOT NULL,
  activity_type VARCHAR(50) NOT NULL, -- workout_complete, streak, social_post, etc.
  description TEXT,
  reference_id UUID, -- workout_id, post_id, etc.
  created_at TIMESTAMP DEFAULT NOW(),
  INDEX idx_user_points (user_id, created_at)
);

-- Achievements
CREATE TABLE achievements (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  name VARCHAR(100) NOT NULL,
  description TEXT,
  icon VARCHAR(50),
  xp_reward INTEGER DEFAULT 0,
  points_reward INTEGER DEFAULT 0,
  criteria JSONB, -- {type: 'streak', value: 7}
  is_secret BOOLEAN DEFAULT FALSE,
  created_at TIMESTAMP DEFAULT NOW()
);

-- User Achievements (Unlocked)
CREATE TABLE user_achievements (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  achievement_id UUID NOT NULL REFERENCES achievements(id),
  unlocked_at TIMESTAMP DEFAULT NOW(),
  UNIQUE(user_id, achievement_id)
);

-- Leaderboards
CREATE TABLE leaderboards (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  name VARCHAR(100) NOT NULL, -- weekly, monthly, all-time
  period_start DATE NOT NULL,
  period_end DATE NOT NULL,
  created_at TIMESTAMP DEFAULT NOW()
);

CREATE TABLE leaderboard_entries (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  leaderboard_id UUID NOT NULL REFERENCES leaderboards(id) ON DELETE CASCADE,
  user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  rank INTEGER,
  score INTEGER,
  metadata JSONB,
  created_at TIMESTAMP DEFAULT NOW(),
  UNIQUE(leaderboard_id, user_id)
);

-- Social Features
CREATE TABLE social_posts (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  content TEXT NOT NULL,
  image_url VARCHAR(500),
  workout_id UUID,
  xp_earned INTEGER DEFAULT 0,
  points_earned INTEGER DEFAULT 0,
  is_public BOOLEAN DEFAULT TRUE,
  created_at TIMESTAMP DEFAULT NOW(),
  INDEX idx_user_posts (user_id, created_at)
);

CREATE TABLE social_likes (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  post_id UUID NOT NULL REFERENCES social_posts(id) ON DELETE CASCADE,
  user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  created_at TIMESTAMP DEFAULT NOW(),
  UNIQUE(post_id, user_id)
);

CREATE TABLE social_comments (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  post_id UUID NOT NULL REFERENCES social_posts(id) ON DELETE CASCADE,
  user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  content TEXT NOT NULL,
  created_at TIMESTAMP DEFAULT NOW(),
  INDEX idx_post_comments (post_id, created_at)
);

-- ============================================
-- AI BOT SYSTEM TABLES
-- ============================================

-- AI Bot Sessions
CREATE TABLE ai_bot_sessions (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  bot_type VARCHAR(50) NOT NULL, -- workout, nutrition, form, alternatives, chat
  session_data JSONB, -- {messages: [], context: {}}
  created_at TIMESTAMP DEFAULT NOW(),
  updated_at TIMESTAMP DEFAULT NOW(),
  INDEX idx_user_bot (user_id, bot_type, created_at)
);

-- Workout Plans (Generated by AI)
CREATE TABLE ai_workout_plans (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  plan_data JSONB NOT NULL, -- {boards: [], exercises: [], timing: {}}
  difficulty VARCHAR(20), -- easy, standard, hard
  equipment_used TEXT[],
  estimated_duration INTEGER,
  nasm_compliant BOOLEAN DEFAULT TRUE,
  generated_at TIMESTAMP DEFAULT NOW(),
  completed_at TIMESTAMP,
  INDEX idx_user_workouts (user_id, generated_at)
);

-- Nutrition Plans
CREATE TABLE ai_nutrition_plans (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  plan_data JSONB NOT NULL, -- {meals: [], macros: {}, supplements: []}
  dietary_restrictions TEXT[],
  calorie_target INTEGER,
  protein_target INTEGER,
  generated_at TIMESTAMP DEFAULT NOW(),
  INDEX idx_user_nutrition (user_id, generated_at)
);

-- Form Analysis Sessions
CREATE TABLE ai_form_analysis (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  video_url VARCHAR(500) NOT NULL,
  exercise_name VARCHAR(100),
  analysis_data JSONB, -- {score: 85, corrections: [], timestamps: []}
  feedback_text TEXT,
  safety_warnings TEXT[],
  created_at TIMESTAMP DEFAULT NOW(),
  INDEX idx_user_form (user_id, created_at)
);

-- Exercise Alternatives
CREATE TABLE ai_alternatives (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  original_exercise VARCHAR(100),
  alternatives JSONB, -- [{name: '...', equipment: '...', difficulty: '...'}]
  reason TEXT, -- injury, equipment unavailable, etc.
  created_at TIMESTAMP DEFAULT NOW(),
  INDEX idx_user_alternatives (user_id, created_at)
);

-- ============================================
-- LEGAL & COMPLIANCE SYSTEM
-- ============================================

-- AI Disclaimers (Master Templates)
CREATE TABLE ai_disclaimers (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  type VARCHAR(50) NOT NULL, -- medical, nutrition, form, general
  version VARCHAR(20) NOT NULL,
  content TEXT NOT NULL,
  is_active BOOLEAN DEFAULT TRUE,
  created_at TIMESTAMP DEFAULT NOW(),
  UNIQUE(type, version)
);

-- User Consent Records (Immutable)
CREATE TABLE user_consents (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  disclaimer_id UUID NOT NULL REFERENCES ai_disclaimers(id),
  consented BOOLEAN NOT NULL,
  ip_address VARCHAR(45),
  user_agent TEXT,
  timestamp TIMESTAMP DEFAULT NOW(),
  withdrawn_at TIMESTAMP,
  INDEX idx_user_consents (user_id, timestamp)
);

-- Audit Log (Compliance)
CREATE TABLE compliance_audit_log (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID REFERENCES users(id) ON DELETE SET NULL,
  action VARCHAR(100) NOT NULL, -- consent_given, consent_withdrawn, data_access, etc.
  resource_type VARCHAR(50),
  resource_id UUID,
  details JSONB,
  created_at TIMESTAMP DEFAULT NOW(),
  INDEX idx_audit_user (user_id, created_at),
  INDEX idx_audit_action (action, created_at)
);

-- Emergency Contact Logs
CREATE TABLE emergency_checks (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  check_type VARCHAR(50) NOT NULL, -- missed_workout, low_activity, etc.
  sent_via VARCHAR(20), -- sms, email, push
  status VARCHAR(20) DEFAULT 'pending', -- pending, sent, responded, escalated
  response TEXT,
  escalated_to_trainer BOOLEAN DEFAULT FALSE,
  created_at TIMESTAMP DEFAULT NOW(),
  INDEX idx_user_emergency (user_id, created_at)
);

-- ============================================
-- ANALYTICS & MONITORING
-- ============================================

-- Bot Usage Analytics
CREATE TABLE bot_analytics (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  bot_type VARCHAR(50) NOT NULL,
  user_id UUID REFERENCES users(id) ON DELETE SET NULL,
  request_count INTEGER DEFAULT 1,
  response_time_ms INTEGER,
  tokens_used INTEGER,
  cost_cents INTEGER,
  success BOOLEAN DEFAULT TRUE,
  error_type VARCHAR(100),
  created_at TIMESTAMP DEFAULT NOW(),
  INDEX idx_bot_analytics (bot_type, created_at)
);

-- Feature Discovery Tracking
CREATE TABLE feature_discovery (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  feature_name VARCHAR(100) NOT NULL,
  discovered_via VARCHAR(50), -- embedded, standalone, notification
  timestamp TIMESTAMP DEFAULT NOW(),
  INDEX idx_user_discovery (user_id, timestamp)
);

-- Performance Metrics
CREATE TABLE performance_metrics (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  metric_name VARCHAR(100) NOT NULL,
  value DECIMAL(10,2),
  metadata JSONB,
  created_at TIMESTAMP DEFAULT NOW(),
  INDEX idx_metric_time (metric_name, created_at)
);

-- ============================================
-- INDEXES & CONSTRAINTS
-- ============================================

-- Performance Indexes
CREATE INDEX idx_points_ledger_aggregate ON points_ledger(user_id, activity_type, created_at);
CREATE INDEX idx_leaderboard_entries_score ON leaderboard_entries(leaderboard_id, score DESC);
CREATE INDEX idx_social_posts_recent ON social_posts(created_at DESC) WHERE is_public = TRUE;
CREATE INDEX idx_ai_sessions_active ON ai_bot_sessions(user_id, updated_at DESC);
CREATE INDEX idx_compliance_timestamp ON compliance_audit_log(created_at DESC);

-- Foreign Key Constraints
ALTER TABLE user_progress ADD CONSTRAINT fk_user_progress_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE;
ALTER TABLE points_ledger ADD CONSTRAINT fk_points_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE;
ALTER TABLE user_achievements ADD CONSTRAINT fk_achievement_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE;

-- ============================================
-- VIEWS FOR EASY QUERYING
-- ============================================

-- User Gamification Summary
CREATE VIEW user_gamification_summary AS
SELECT 
  u.id as user_id,
  u.email,
  up.level,
  up.xp,
  up.streak,
  up.total_points,
  COALESCE(pl.points_this_week, 0) as points_this_week,
  COALESCE(pa.achievements_count, 0) as achievements_count,
  COALESCE(sp.posts_count, 0) as posts_count
FROM users u
LEFT JOIN user_progress up ON u.id = up.user_id
LEFT JOIN (
  SELECT user_id, SUM(points) as points_this_week
  FROM points_ledger
  WHERE created_at >= date_trunc('week', NOW())
  GROUP BY user_id
) pl ON u.id = pl.user_id
LEFT JOIN (
  SELECT user_id, COUNT(*) as achievements_count
  FROM user_achievements
  GROUP BY user_id
) pa ON u.id = pa.user_id
LEFT JOIN (
  SELECT user_id, COUNT(*) as posts_count
  FROM social_posts
  WHERE created_at >= date_trunc('week', NOW())
  GROUP BY user_id
) sp ON u.id = sp.user_id;

-- AI Bot Performance Dashboard
CREATE VIEW bot_performance_summary AS
SELECT 
  bot_type,
  COUNT(*) as total_requests,
  AVG(response_time_ms) as avg_response_time,
  SUM(tokens_used) as total_tokens,
  SUM(cost_cents) / 100.0 as total_cost,
  (SUM(CASE WHEN success THEN 1 ELSE 0 END) * 100.0 / COUNT(*)) as success_rate
FROM bot_analytics
WHERE created_at >= date_trunc('day', NOW() - INTERVAL '7 days')
GROUP BY bot_type;

-- Compliance Status
CREATE VIEW user_compliance_status AS
SELECT 
  u.id as user_id,
  u.email,
  MAX(CASE WHEN ad.type = 'medical' AND uc.consented = TRUE THEN 1 ELSE 0 END) as medical_consent,
  MAX(CASE WHEN ad.type = 'nutrition' AND uc.consented = TRUE THEN 1 ELSE 0 END) as nutrition_consent,
  MAX(CASE WHEN ad.type = 'form' AND uc.consented = TRUE THEN 1 ELSE 0 END) as form_consent,
  MAX(uc.timestamp) as last_consent_date,
  MAX(CASE WHEN uc.withdrawn_at IS NOT NULL THEN 1 ELSE 0 END) as has_withdrawn
FROM users u
LEFT JOIN user_consents uc ON u.id = uc.user_id
LEFT JOIN ai_disclaimers ad ON uc.disclaimer_id = ad.id
GROUP BY u.id, u.email;

-- ============================================
-- SAMPLE DATA
-- ============================================

-- Insert Active Disclaimers
INSERT INTO ai_disclaimers (type, version, content, is_active) VALUES
('medical', '1.0', 'IMPORTANT: The AI-generated workout plans are for informational purposes only. Always consult with a qualified healthcare professional before starting any new exercise program. If you experience pain, dizziness, or shortness of breath, stop immediately and seek medical attention.', TRUE),
('nutrition', '1.0', 'DISCLAIMER: AI-generated nutrition plans are general guidelines only. They do not account for specific medical conditions, allergies, or dietary restrictions. Consult a registered dietitian or healthcare provider for personalized nutrition advice.', TRUE),
('form', '1.0', 'SAFETY NOTICE: Form analysis is provided by computer vision AI and may not detect all safety issues. Always prioritize proper form over speed or weight. If unsure about an exercise, consult a certified trainer. This tool is not a substitute for professional instruction.', TRUE),
('general', '1.0', 'By using AI features, you acknowledge that artificial intelligence is used in the generation of content. Responses may contain inaccuracies. Use your judgment and consult professionals when needed. You may withdraw consent at any time in your account settings.', TRUE);

-- Insert Sample Achievements
INSERT INTO achievements (name, description, icon, xp_reward, points_reward, criteria, is_secret) VALUES
('First Workout', 'Complete your first AI-generated workout', '🏆', 100, 10, '{"type": "workout_count", "value": 1}', FALSE),
('Streak Master', '7-day workout streak', '🔥', 500, 50, '{"type": "streak", "value": 7}', FALSE),
('Social Butterfly', 'Post 5 times to community', '🦋', 250, 25, '{"type": "posts", "value": 5}', FALSE),
('Form Expert', 'Analyze 10 exercises', '👁️', 300, 30, '{"type": "form_analysis", "value": 10}', FALSE),
('Nutrition Pro', 'Follow meal plan for 7 days', '🥗', 400, 40, '{"type": "nutrition_days", "value": 7}', FALSE),
('Hidden Gem', 'Unlock a secret achievement', '💎', 1000, 100, '{"type": "secret", "value": 1}', TRUE);