/**
 * Master Prompt Builder Service
 * =============================
 * Auto-builds a masterPromptJson from existing user data when none exists.
 * Pulls from: User, WaiverRecord, MovementAnalysis, EquipmentProfile, WorkoutSession.
 *
 * Used by: aiWorkoutController, longHorizonController, aiChatService
 */
import { getAllModels } from '../models/index.mjs';
import logger from '../utils/logger.mjs';

/**
 * Build masterPromptJson from available user data.
 * Returns a v3.0-compatible master prompt object, or null if user not found.
 */
export async function buildMasterPromptFromUserData(targetUser) {
  if (!targetUser) return null;

  const models = getAllModels();
  const {
    WaiverRecord,
    MovementAnalysis,
    EquipmentProfile,
    EquipmentItem,
    WorkoutSession,
    WorkoutLog,
    ClientBaselineMeasurements,
    ClientOnboardingQuestionnaire,
  } = models;

  const userId = targetUser.id;

  // Gather all data sources in parallel
  const [waiver, movementAnalysis, equipmentProfiles, recentSessions, baseline, questionnaire] =
    await Promise.all([
      WaiverRecord?.findOne({
        where: { userId, status: 'linked' },
        order: [['signedAt', 'DESC']],
      }).catch(() => null) ?? null,

      MovementAnalysis?.findOne({
        where: { userId, status: ['completed', 'linked'] },
        order: [['assessmentDate', 'DESC']],
      }).catch(() => null) ?? null,

      EquipmentProfile?.findAll({
        where: { trainerId: userId, isActive: true },
        include: EquipmentItem ? [{ model: EquipmentItem, as: 'items' }] : [],
        limit: 10,
      }).catch(() => []) ?? [],

      WorkoutSession?.findAll({
        where: { userId },
        order: [['date', 'DESC']],
        limit: 10,
        include: WorkoutLog ? [{ model: WorkoutLog, as: 'logs' }] : [],
      }).catch(() => []) ?? [],

      ClientBaselineMeasurements?.findOne({
        where: { userId },
        order: [['takenAt', 'DESC']],
      }).catch(() => null) ?? null,

      ClientOnboardingQuestionnaire?.findOne({
        where: { userId },
        order: [['createdAt', 'DESC']],
      }).catch(() => null) ?? null,
    ]);

  // Build the master prompt JSON (v3.0 schema)
  const masterPrompt = {
    version: '3.0',
    generatedAt: new Date().toISOString(),
    autoGenerated: true,

    // Client profile
    clientProfile: {
      name: targetUser.firstName && targetUser.lastName
        ? `${targetUser.firstName} ${targetUser.lastName}`
        : targetUser.username || 'Client',
      dateOfBirth: targetUser.dateOfBirth || waiver?.dateOfBirth || null,
      gender: targetUser.gender || null,
      weight: targetUser.weight || baseline?.weight || null,
      height: targetUser.height || baseline?.height || null,
    },

    // Goals
    goals: {
      primary: targetUser.fitnessGoal || questionnaire?.primaryGoal || 'general_fitness',
      secondary: questionnaire?.secondaryGoals || [],
      notes: questionnaire?.goalNotes || targetUser.fitnessGoal || null,
    },

    // Fitness background
    fitnessBackground: {
      experienceLevel: questionnaire?.experienceLevel || 'beginner',
      trainingExperience: targetUser.trainingExperience || null,
      currentActivityLevel: questionnaire?.activityLevel || null,
      preferredExercises: questionnaire?.preferredExercises || [],
      dislikedExercises: questionnaire?.dislikedExercises || [],
    },

    // Health & medical
    health: {
      concerns: targetUser.healthConcerns || null,
      medicalClearanceRequired: movementAnalysis?.medicalClearanceRequired || false,
      medicalClearanceDate: movementAnalysis?.medicalClearanceDate || null,
      injuries: extractInjuries(movementAnalysis, waiver),
      parqScreening: movementAnalysis?.parqScreening || null,
    },

    // Movement assessment data
    movementAssessment: movementAnalysis ? {
      assessmentDate: movementAnalysis.assessmentDate,
      nasmScore: movementAnalysis.nasmAssessmentScore,
      overheadSquat: movementAnalysis.overheadSquatAssessment || null,
      posturalAssessment: movementAnalysis.posturalAssessment || null,
      squatUniversity: movementAnalysis.squatUniversityAssessment || null,
      movementQuality: movementAnalysis.movementQualityAssessments || null,
      correctiveStrategy: movementAnalysis.correctiveExerciseStrategy || null,
      primaryCompensations: extractCompensations(movementAnalysis.overheadSquatAssessment),
    } : null,

    // Available equipment
    equipment: equipmentProfiles.length > 0
      ? equipmentProfiles.map(p => ({
          profileName: p.name,
          locationType: p.locationType,
          items: (p.items || []).map(i => ({
            name: i.name,
            category: i.category,
            quantity: i.quantity,
          })),
        }))
      : [{ profileName: 'Default', locationType: 'gym', items: [] }],

    // Training history summary
    trainingHistory: {
      totalSessions: recentSessions.length,
      recentWorkouts: recentSessions.slice(0, 5).map(s => ({
        date: s.date,
        type: s.sessionType || s.type || 'general',
        duration: s.duration || null,
        exerciseCount: (s.logs || []).length,
      })),
    },

    // Baseline measurements
    measurements: baseline ? {
      takenAt: baseline.takenAt,
      weight: baseline.weight || null,
      bodyFatPercentage: baseline.bodyFatPercentage || null,
      bmi: baseline.bmi || null,
    } : null,
  };

  logger.info('Auto-generated masterPromptJson from user data', {
    userId,
    hasWaiver: !!waiver,
    hasMovementAnalysis: !!movementAnalysis,
    equipmentProfiles: equipmentProfiles.length,
    recentSessions: recentSessions.length,
    hasBaseline: !!baseline,
  });

  return masterPrompt;
}

/**
 * Extract injury/limitation data from movement analysis and waiver records.
 */
function extractInjuries(movementAnalysis, waiver) {
  const injuries = [];

  // From waiver activity types (may indicate limitations)
  if (waiver?.activityTypes && Array.isArray(waiver.activityTypes)) {
    // Activity types themselves aren't injuries, but metadata might have them
    if (waiver.metadata?.injuries) {
      injuries.push(...(Array.isArray(waiver.metadata.injuries) ? waiver.metadata.injuries : [waiver.metadata.injuries]));
    }
  }

  // From movement analysis corrective strategy
  if (movementAnalysis?.correctiveExerciseStrategy) {
    const strategy = movementAnalysis.correctiveExerciseStrategy;
    if (strategy.limitations && Array.isArray(strategy.limitations)) {
      injuries.push(...strategy.limitations);
    }
    if (strategy.painAreas && Array.isArray(strategy.painAreas)) {
      injuries.push(...strategy.painAreas);
    }
  }

  return injuries.length > 0 ? injuries : null;
}

/**
 * Extract primary compensations from OHSA assessment for quick reference.
 */
function extractCompensations(ohsa) {
  if (!ohsa) return [];

  const compensations = [];
  const views = ['anteriorView', 'lateralView'];
  const labels = {
    feetTurnout: 'Feet Turn Out',
    feetFlattening: 'Feet Flatten',
    kneeValgus: 'Knee Valgus',
    kneeVarus: 'Knee Varus',
    excessiveForwardLean: 'Excessive Forward Lean',
    lowBackArch: 'Low Back Arch',
    armsFallForward: 'Arms Fall Forward',
    forwardHead: 'Forward Head Posture',
  };

  for (const view of views) {
    if (!ohsa[view]) continue;
    for (const [key, label] of Object.entries(labels)) {
      if (ohsa[view][key] === 'significant' || ohsa[view][key] === 'minor') {
        compensations.push({ finding: label, severity: ohsa[view][key] });
      }
    }
  }

  if (ohsa.asymmetricWeightShift && ohsa.asymmetricWeightShift !== 'none') {
    compensations.push({ finding: 'Asymmetric Weight Shift', severity: ohsa.asymmetricWeightShift });
  }

  return compensations;
}

export default { buildMasterPromptFromUserData };
