/**
 * socialAutoPost — Auto-generate social feed posts for key events
 * ================================================================
 * Creates public posts when users complete workouts, hit streaks,
 * or earn achievements. All auto-posts are best-effort (never fail
 * the triggering operation) and marked with isAutoGenerated metadata.
 */

import SocialPost from '../models/social/SocialPost.mjs';
import logger from '../utils/logger.mjs';

const STREAK_MILESTONES = [7, 14, 30, 60, 90, 180, 365];

const WORKOUT_MESSAGES = [
  'Just crushed a workout! 💪',
  'Another workout in the books! 🔥',
  'Putting in the work! 💯',
  'Grinding! No days off! 🏋️',
  'Showing up and getting it done! ⚡',
];

/**
 * Create an auto-post for a completed workout.
 * @param {number} userId
 * @param {{ duration: number, exercisesCompleted: number, pointsAwarded: number }} workoutData
 */
export async function createWorkoutAutoPost(userId, workoutData) {
  try {
    const { duration, exercisesCompleted, pointsAwarded } = workoutData;
    const msg = WORKOUT_MESSAGES[Math.floor(Math.random() * WORKOUT_MESSAGES.length)];

    const parts = [msg];
    if (duration) parts.push(`⏱️ ${duration} min`);
    if (exercisesCompleted) parts.push(`🎯 ${exercisesCompleted} exercises`);
    if (pointsAwarded) parts.push(`+${pointsAwarded} XP`);

    const content = parts.join(' | ');

    await SocialPost.create({
      userId,
      content,
      type: 'workout',
      visibility: 'public',
      moderationStatus: 'approved',
      moderationNotes: 'auto-generated',
    });

    logger.info(`Auto-post: workout post created for user ${userId}`);
  } catch (err) {
    logger.error(`Auto-post: failed to create workout post for user ${userId}: ${err.message}`);
  }
}

/**
 * Create an auto-post for a streak milestone (7, 14, 30, 60, 90, 180, 365 days).
 * @param {number} userId
 * @param {number} streakDays
 */
export async function createStreakAutoPost(userId, streakDays) {
  try {
    if (!STREAK_MILESTONES.includes(streakDays)) return;

    const emoji = streakDays >= 90 ? '👑' : streakDays >= 30 ? '🔥' : '⚡';
    const content = `${emoji} ${streakDays}-day workout streak! Consistency is key! 🏆`;

    await SocialPost.create({
      userId,
      content,
      type: 'milestone',
      visibility: 'public',
      moderationStatus: 'approved',
      moderationNotes: 'auto-generated',
    });

    logger.info(`Auto-post: streak ${streakDays}d post created for user ${userId}`);
  } catch (err) {
    logger.error(`Auto-post: failed to create streak post for user ${userId}: ${err.message}`);
  }
}

/**
 * Create an auto-post for an achievement unlock.
 * @param {number} userId
 * @param {{ name: string, description?: string }} achievement
 */
export async function createAchievementAutoPost(userId, achievement) {
  try {
    const content = `🏅 Achievement Unlocked: ${achievement.name}! ${achievement.description || ''}`.trim();

    await SocialPost.create({
      userId,
      content,
      type: 'achievement',
      visibility: 'public',
      moderationStatus: 'approved',
      moderationNotes: 'auto-generated',
    });

    logger.info(`Auto-post: achievement post created for user ${userId} — ${achievement.name}`);
  } catch (err) {
    logger.error(`Auto-post: failed to create achievement post for user ${userId}: ${err.message}`);
  }
}

export default { createWorkoutAutoPost, createStreakAutoPost, createAchievementAutoPost };
