/**
 * ============================================================================
 * FILE: supplementData.mjs
 * PURPOSE: Static supplement catalog and category definitions
 * AUTHOR: Claude Sonnet 4.6 | LAST MODIFIED: 2026-04-08
 * ============================================================================
 *
 * WHAT THIS FILE DOES: Provides the static SUPPLEMENT_CATALOG (12 products)
 *   and CATEGORIES array used by supplementService.mjs.
 *   Extracted to keep supplementService.mjs under 300 lines (CLAUDE.md rule).
 *
 * NOTE: All affiliateUrl fields are empty placeholders — Sean must populate
 *   these after signing up for each affiliate program (AG1, etc.).
 */

export const SUPPLEMENT_CATALOG = [
  {
    id: 'ag1',
    name: 'AG1 (Athletic Greens)',
    category: 'greens',
    description: 'Comprehensive daily nutrition with 75 vitamins, minerals, and whole-food sourced ingredients. Supports gut health, immunity, energy, and recovery.',
    price: '$79/month',
    rating: 4.8,
    seansPick: true,
    nasmContext: 'Covers micronutrient gaps that macros alone miss. Especially valuable during caloric restriction phases.',
    affiliateUrl: '', // Sean: sign up at drinkag1.com/affiliates
    imageTag: 'ag1',
    badges: ['Trainer Pick', 'NSF Certified'],
  },
  {
    id: 'whey-protein',
    name: 'Whey Protein Isolate',
    category: 'protein',
    description: 'Fast-absorbing complete protein. Ideal post-workout for muscle protein synthesis. 25-30g protein per scoop.',
    price: '$35-55',
    rating: 4.7,
    seansPick: false,
    nasmContext: 'NASM recommends 1.4-2.0g/kg/day for active individuals. Whey isolate has the highest bioavailability.',
    affiliateUrl: '',
    imageTag: 'whey',
    badges: ['Post-Workout'],
  },
  {
    id: 'plant-protein',
    name: 'Plant-Based Protein Blend',
    category: 'protein',
    description: 'Pea + rice protein blend for complete amino acid profile. Dairy-free, soy-free. 20-25g protein per scoop.',
    price: '$30-50',
    rating: 4.5,
    seansPick: false,
    nasmContext: 'Blended plant proteins match whey for muscle synthesis when combined with leucine-rich sources.',
    affiliateUrl: '',
    imageTag: 'plant-protein',
    badges: ['Vegan'],
  },
  {
    id: 'creatine',
    name: 'Creatine Monohydrate',
    category: 'performance',
    description: 'Most researched supplement in sports nutrition. 5g/day supports strength, power output, and muscle recovery.',
    price: '$15-25',
    rating: 4.9,
    seansPick: true,
    nasmContext: 'NASM OPT Phases 3-5 (Hypertrophy, Max Strength, Power) benefit most from creatine supplementation.',
    affiliateUrl: '',
    imageTag: 'creatine',
    badges: ['Research-Backed', 'Trainer Pick'],
  },
  {
    id: 'vitamin-d3',
    name: 'Vitamin D3 + K2',
    category: 'vitamins',
    description: 'Essential for bone health, immune function, and muscle recovery. 5000 IU D3 with K2 for optimal absorption.',
    price: '$12-20',
    rating: 4.8,
    seansPick: false,
    nasmContext: 'Deficiency linked to increased injury risk and slower recovery. Critical for indoor athletes and northern climates.',
    affiliateUrl: '',
    imageTag: 'vitamin-d',
    badges: ['Essential'],
  },
  {
    id: 'omega3',
    name: 'Omega-3 Fish Oil (EPA/DHA)',
    category: 'recovery',
    description: 'Anti-inflammatory essential fatty acids. Supports joint health, brain function, and cardiovascular health.',
    price: '$18-35',
    rating: 4.6,
    seansPick: false,
    nasmContext: 'Reduces exercise-induced inflammation. Particularly beneficial for high-volume training and joint-heavy sports like golf.',
    affiliateUrl: '',
    imageTag: 'omega3',
    badges: ['Joint Health'],
  },
  {
    id: 'magnesium',
    name: 'Magnesium Glycinate',
    category: 'recovery',
    description: 'Highly bioavailable magnesium for sleep quality, muscle relaxation, and nerve function. 400mg/day.',
    price: '$15-25',
    rating: 4.7,
    seansPick: true,
    nasmContext: 'Depleted during intense exercise via sweat. Glycinate form has best absorption and least GI distress.',
    affiliateUrl: '',
    imageTag: 'magnesium',
    badges: ['Sleep', 'Trainer Pick'],
  },
  {
    id: 'electrolytes',
    name: 'Electrolyte Mix (No Sugar)',
    category: 'performance',
    description: 'Sodium, potassium, magnesium blend for hydration. Zero sugar, zero calories. Essential for athletes.',
    price: '$20-30',
    rating: 4.6,
    seansPick: false,
    nasmContext: 'NASM hydration protocol: replace electrolytes during sessions >60 minutes or in hot/humid conditions.',
    affiliateUrl: '',
    imageTag: 'electrolytes',
    badges: ['Hydration'],
  },
  {
    id: 'collagen',
    name: 'Collagen Peptides',
    category: 'recovery',
    description: 'Type I & III collagen for joint, tendon, and skin health. 10-20g/day. Unflavored mixes into anything.',
    price: '$25-40',
    rating: 4.5,
    seansPick: false,
    nasmContext: 'Emerging research supports collagen + vitamin C 30-60 min before exercise for connective tissue repair.',
    affiliateUrl: '',
    imageTag: 'collagen',
    badges: ['Joint Health'],
  },
  {
    id: 'probiotic',
    name: 'Multi-Strain Probiotic',
    category: 'gut-health',
    description: 'Broad-spectrum probiotic with 50+ billion CFU. Supports gut-brain axis, nutrient absorption, immunity.',
    price: '$25-40',
    rating: 4.5,
    seansPick: false,
    nasmContext: 'Gut health affects nutrient absorption efficiency. Poor gut = wasted macros regardless of diet quality.',
    affiliateUrl: '',
    imageTag: 'probiotic',
    badges: ['Gut Health'],
  },
  {
    id: 'beta-alanine',
    name: 'Beta-Alanine',
    category: 'performance',
    description: 'Buffers lactic acid for longer high-intensity sets. 3-6g/day. Tingling (paresthesia) is harmless.',
    price: '$15-25',
    rating: 4.4,
    seansPick: false,
    nasmContext: 'Most effective in NASM OPT Phases 2-3 (Strength Endurance, Hypertrophy) where sets are 8-20 reps.',
    affiliateUrl: '',
    imageTag: 'beta-alanine',
    badges: ['Endurance'],
  },
  {
    id: 'sleep-formula',
    name: 'Sleep & Recovery Formula',
    category: 'sleep',
    description: 'Magnesium, L-theanine, and ashwagandha blend. Supports deep sleep and cortisol management.',
    price: '$25-35',
    rating: 4.6,
    seansPick: false,
    nasmContext: 'Recovery happens during sleep. Poor sleep = elevated cortisol = muscle breakdown + fat storage.',
    affiliateUrl: '',
    imageTag: 'sleep',
    badges: ['Recovery', 'Sleep'],
  },
];

export const CATEGORIES = [
  { id: 'greens',      name: 'Greens & Superfoods',     icon: 'leaf',     description: 'Daily micronutrient coverage' },
  { id: 'protein',     name: 'Protein',                 icon: 'dumbbell', description: 'Muscle protein synthesis support' },
  { id: 'performance', name: 'Performance',             icon: 'zap',      description: 'Strength, power, and endurance' },
  { id: 'vitamins',    name: 'Vitamins & Minerals',     icon: 'sun',      description: 'Essential micronutrients' },
  { id: 'recovery',    name: 'Recovery & Joint Health', icon: 'heart',    description: 'Inflammation and repair' },
  { id: 'gut-health',  name: 'Gut Health',              icon: 'shield',   description: 'Absorption and immunity' },
  { id: 'sleep',       name: 'Sleep & Stress',          icon: 'moon',     description: 'Recovery optimization' },
];
