const PAGE_WIDTH = 612;
const PAGE_HEIGHT = 792;
const PAGE_MARGIN = 44;
const FOOTER_Y = 32;
const HEADER_HEIGHT = 78;
const BODY_TOP = PAGE_HEIGHT - PAGE_MARGIN - HEADER_HEIGHT;
const BODY_BOTTOM = 60;
const MAX_CHARS_BY_KIND = {
  title: 54,
  subtitle: 70,
  section: 70,
  week: 76,
  day: 78,
  tableHeader: 96,
  exercise: 102,
  metric: 94,
  body: 96,
  meta: 96,
};

const STYLE = {
  title: { font: 'F3', size: 20, leading: 24, indent: 0, color: [0, 32, 96] },
  subtitle: { font: 'F2', size: 12, leading: 16, indent: 0, color: [31, 41, 55] },
  section: { font: 'F2', size: 11, leading: 18, indent: 0, color: [0, 32, 96], band: true },
  week: { font: 'F2', size: 10, leading: 16, indent: 0, color: [139, 92, 246] },
  day: { font: 'F2', size: 9, leading: 14, indent: 10, color: [0, 48, 128] },
  tableHeader: { font: 'F2', size: 7.5, leading: 12, indent: 18, color: [255, 255, 255], band: true, darkBand: true },
  exercise: { font: 'F1', size: 7.5, leading: 11, indent: 18, color: [31, 41, 55] },
  metric: { font: 'F1', size: 9, leading: 13, indent: 10, color: [31, 41, 55] },
  body: { font: 'F1', size: 8.5, leading: 12, indent: 10, color: [31, 41, 55] },
  meta: { font: 'F4', size: 7.5, leading: 11, indent: 10, color: [91, 103, 122] },
};

const firstPresent = (...values) => (
  values.find((value) => value !== undefined && value !== null && value !== '')
);

const escapePdfText = (value) => (
  String(value).replace(/\\/g, '\\\\').replace(/\(/g, '\\(').replace(/\)/g, '\\)')
);

const rgb = ([r, g, b]) => `${(r / 255).toFixed(3)} ${(g / 255).toFixed(3)} ${(b / 255).toFixed(3)}`;

const wrapText = (text, limit) => {
  const raw = String(firstPresent(text, ' '));
  if (raw.length <= limit) return [raw];
  const words = raw.split(' ');
  const lines = [];
  let current = '';
  words.forEach((word) => {
    const next = current ? `${current} ${word}` : word;
    if (next.length <= limit) {
      current = next;
      return;
    }
    if (current) lines.push(current);
    current = word.length > limit ? word.slice(0, limit) : word;
  });
  if (current) lines.push(current);
  return lines;
};

const physicalLines = (lines) => lines.flatMap((line) => {
  const kind = line.kind || 'body';
  const limit = MAX_CHARS_BY_KIND[kind] || 94;
  return wrapText(line.text, limit).map((text, index) => ({
    text,
    kind,
    continuation: index > 0,
  }));
});

const chunkPages = (lines) => {
  const pages = [];
  let page = [];
  let y = BODY_TOP;
  lines.forEach((line) => {
    const style = STYLE[line.kind] || STYLE.body;
    if (y - style.leading < BODY_BOTTOM && page.length) {
      pages.push(page);
      page = [];
      y = BODY_TOP;
    }
    page.push(line);
    y -= style.leading;
  });
  if (page.length) pages.push(page);
  return pages.length ? pages : [[{ text: 'SwanStudios Workout Plan', kind: 'title' }]];
};

const appendText = (commands, {
  text,
  x,
  y,
  font = 'F1',
  size = 9,
  color = [31, 41, 55],
}) => {
  commands.push(`${rgb(color)} rg`);
  commands.push('BT');
  commands.push(`/${font} ${size} Tf`);
  commands.push(`${x} ${y} Td`);
  commands.push(`(${escapePdfText(text)}) Tj`);
  commands.push('ET');
};

const appendHeader = (commands, pageNumber, totalPages) => {
  commands.push('q');
  commands.push(`${rgb([0, 32, 96])} rg`);
  commands.push(`0 ${PAGE_HEIGHT - HEADER_HEIGHT} ${PAGE_WIDTH} ${HEADER_HEIGHT} re f`);
  commands.push(`${rgb([139, 92, 246])} rg`);
  commands.push(`0 ${PAGE_HEIGHT - HEADER_HEIGHT - 3} ${PAGE_WIDTH} 3 re f`);
  commands.push(`${rgb([198, 168, 75])} rg`);
  commands.push(`${PAGE_MARGIN} ${PAGE_HEIGHT - 48} ${PAGE_WIDTH - PAGE_MARGIN * 2} 1.2 re f`);
  appendText(commands, {
    text: 'SwanStudios',
    x: PAGE_MARGIN,
    y: PAGE_HEIGHT - 34,
    font: 'F3',
    size: 19,
    color: [255, 255, 255],
  });
  appendText(commands, {
    text: 'Professional Workout Plan',
    x: PAGE_WIDTH - 210,
    y: PAGE_HEIGHT - 34,
    font: 'F2',
    size: 11,
    color: [224, 236, 244],
  });
  appendText(commands, {
    text: `Page ${pageNumber} of ${totalPages}`,
    x: PAGE_WIDTH - 110,
    y: FOOTER_Y,
    font: 'F1',
    size: 8,
    color: [91, 103, 122],
  });
  appendText(commands, {
    text: 'Generated by SwanStudios - client-facing training plan',
    x: PAGE_MARGIN,
    y: FOOTER_Y,
    font: 'F1',
    size: 8,
    color: [91, 103, 122],
  });
};

const appendBand = (commands, y, style) => {
  const x = PAGE_MARGIN + style.indent - 4;
  const width = PAGE_WIDTH - PAGE_MARGIN * 2 - style.indent + 8;
  const height = style.darkBand ? 13 : 15;
  commands.push(`${rgb(style.darkBand ? [0, 48, 128] : [224, 236, 244])} rg`);
  commands.push(`${x} ${y - 4} ${width} ${height} re f`);
};

const renderPageStream = (pageLines, pageNumber, totalPages) => {
  const commands = [];
  appendHeader(commands, pageNumber, totalPages);
  let y = BODY_TOP;
  pageLines.forEach((line) => {
    const style = STYLE[line.kind] || STYLE.body;
    if (style.band && !line.continuation) appendBand(commands, y, style);
    appendText(commands, {
      text: line.text,
      x: PAGE_MARGIN + style.indent + (line.continuation ? 10 : 0),
      y,
      font: style.font,
      size: style.size,
      color: style.color,
    });
    y -= style.leading;
  });
  commands.push('Q');
  return `${commands.join('\n')}\n`;
};

export const buildWorkoutPlanPdfBuffer = (logicalLines) => {
  const pages = chunkPages(physicalLines(logicalLines));
  const objectCount = 6 + (pages.length * 2);
  const objects = Array(objectCount + 1).fill('');
  const pageIds = pages.map((_, index) => 7 + (index * 2));

  objects[1] = '<< /Type /Catalog /Pages 2 0 R >>';
  objects[2] = `<< /Type /Pages /Kids [${pageIds.map((id) => `${id} 0 R`).join(' ')}] /Count ${pages.length} >>`;
  objects[3] = '<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>';
  objects[4] = '<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica-Bold >>';
  objects[5] = '<< /Type /Font /Subtype /Type1 /BaseFont /Times-Bold >>';
  objects[6] = '<< /Type /Font /Subtype /Type1 /BaseFont /Courier >>';

  pages.forEach((pageLines, index) => {
    const pageId = 7 + (index * 2);
    const contentId = pageId + 1;
    const stream = renderPageStream(pageLines, index + 1, pages.length);
    objects[pageId] = [
      '<< /Type /Page',
      '/Parent 2 0 R',
      `/MediaBox [0 0 ${PAGE_WIDTH} ${PAGE_HEIGHT}]`,
      '/Resources << /Font << /F1 3 0 R /F2 4 0 R /F3 5 0 R /F4 6 0 R >> >>',
      `/Contents ${contentId} 0 R`,
      '>>',
    ].join(' ');
    objects[contentId] = `<< /Length ${Buffer.byteLength(stream, 'utf8')} >>\nstream\n${stream}endstream`;
  });

  let pdf = '%PDF-1.4\n';
  const offsets = [0];
  for (let id = 1; id <= objectCount; id += 1) {
    offsets[id] = Buffer.byteLength(pdf, 'utf8');
    pdf += `${id} 0 obj\n${objects[id]}\nendobj\n`;
  }
  const xrefOffset = Buffer.byteLength(pdf, 'utf8');
  pdf += `xref\n0 ${objectCount + 1}\n`;
  pdf += '0000000000 65535 f \n';
  for (let id = 1; id <= objectCount; id += 1) {
    pdf += `${String(offsets[id]).padStart(10, '0')} 00000 n \n`;
  }
  pdf += `trailer\n<< /Size ${objectCount + 1} /Root 1 0 R >>\n`;
  pdf += `startxref\n${xrefOffset}\n%%EOF\n`;
  return Buffer.from(pdf, 'utf8');
};
