/**
 * Workout Plan Exercise Guide Service
 * ===================================
 *
 * Builds the "Exercise Guide" appendix for the client-facing workout-plan PDF:
 * one entry per unique exercise in the plan explaining how to perform it
 * (description, step-by-step instructions, coach cues) plus where to watch it —
 * the SwanStudios-hosted video when one exists, otherwise the best YouTube
 * search phrase until Swan's own video library covers the movement.
 *
 * Also resolves the on-document brand identity server-side (mirror of
 * frontend/src/services/pdf/brandIdentity.ts): Move Fitness clients are
 * white-labeled to "Sean Swan at Move Fitness" with zero SwanStudios marks.
 */

import { Op } from 'sequelize';
import { getModel } from '../models/index.mjs';
import logger from '../utils/logger.mjs';
import { cleanPdfText } from './workoutPlanPdfDataService.mjs';

const MAX_GUIDE_EXERCISES = 60;
const MAX_INSTRUCTION_STEPS = 6;

export const SWANSTUDIOS_PDF_BRAND = {
  wordmark: 'SwanStudios',
  footerCredit: 'Generated by SwanStudios - client-facing training plan',
  filenamePrefix: 'SwanStudios',
};

export const MOVE_FITNESS_PDF_BRAND = {
  wordmark: 'Sean Swan at Move Fitness',
  footerCredit: 'Generated by Sean Swan at Move Fitness',
  filenamePrefix: 'MoveFitness',
};

const normalizeClientSource = (value) => (
  String(value || '').trim().toLowerCase().replace(/[\s-]+/g, '_')
);

/** Fail-safe: unknown sources brand as SwanStudios, never white-label wrongly. */
export const resolveWorkoutPlanPdfBrand = (clientSource) => (
  normalizeClientSource(clientSource) === 'move_fitness'
    ? MOVE_FITNESS_PDF_BRAND
    : SWANSTUDIOS_PDF_BRAND
);

export const resolveWorkoutPlanPdfBrandForClient = async (clientId) => {
  try {
    const User = getModel('User');
    const client = clientId
      ? await User.findByPk(clientId, { attributes: ['id', 'clientSource'] })
      : null;
    return resolveWorkoutPlanPdfBrand(client?.clientSource);
  } catch (error) {
    logger.warn('[PlanPdfGuide] brand lookup failed (%s); defaulting to SwanStudios', error.message);
    return SWANSTUDIOS_PDF_BRAND;
  }
};

const weekTrainingDays = (week) => {
  const raw = week && typeof week === 'object' ? week : {};
  return [raw.days, raw.sessions].find(Array.isArray) || [];
};

/** Unique, order-preserving exercise names across the whole plan. */
export const collectPlanExerciseNames = (planData) => {
  const weeks = Array.isArray(planData?.weeks) ? planData.weeks : [];
  const seen = new Set();
  const names = [];
  weeks.forEach((week) => weekTrainingDays(week).forEach((day) => {
    const exercises = Array.isArray(day?.exercises) ? day.exercises : [];
    exercises.forEach((exercise) => {
      const name = cleanPdfText(exercise?.exerciseName || exercise?.name, '', 160);
      const key = name.toLowerCase();
      if (!name || seen.has(key)) return;
      seen.add(key);
      names.push(name);
    });
  }));
  return names.slice(0, MAX_GUIDE_EXERCISES);
};

const fetchExerciseRecords = async (names) => {
  if (!names.length) return new Map();
  try {
    const Exercise = getModel('Exercise');
    const rows = await Exercise.findAll({
      where: { name: { [Op.iLike]: { [Op.any]: names } } },
      attributes: ['name', 'description', 'instructions', 'coachingCues', 'videoUrl'],
    });
    return new Map(rows.map((row) => [String(row.name).toLowerCase(), row]));
  } catch (error) {
    logger.warn('[PlanPdfGuide] exercise lookup failed (%s); guide falls back to search-only entries', error.message);
    return new Map();
  }
};

const youtubeSearchPhrase = (name) => (
  `YouTube search: "${name} exercise proper form tutorial"`
);

const instructionSteps = (instructions) => (
  String(instructions || '')
    .split(/\r?\n|(?<=\.)\s+(?=\d+[.)])/)
    .map((step) => cleanPdfText(step, '', 220))
    .filter(Boolean)
    .slice(0, MAX_INSTRUCTION_STEPS)
);

const guideEntryLines = (name, record) => {
  const lines = [{ text: name, kind: 'day' }];
  const description = cleanPdfText(record?.description, '', 260);
  if (description) lines.push({ text: description, kind: 'body' });

  instructionSteps(record?.instructions).forEach((step, index) => {
    lines.push({ text: `${index + 1}. ${step.replace(/^\d+[.)]\s*/, '')}`, kind: 'body' });
  });

  const cues = Array.isArray(record?.coachingCues) ? record.coachingCues : [];
  const cueText = cleanPdfText(cues.filter(Boolean).slice(0, 3).join(' - '), '', 220);
  if (cueText) lines.push({ text: `Coach cues: ${cueText}`, kind: 'meta' });

  const videoUrl = cleanPdfText(record?.videoUrl, '', 220);
  lines.push({
    text: videoUrl
      ? `Watch the demo video in your SwanStudios exercise library: ${videoUrl}`
      : youtubeSearchPhrase(name),
    kind: 'meta',
  });
  return lines;
};

/**
 * Async appendix builder. Returns [] when the plan has no exercises so
 * callers can spread the result unconditionally.
 */
export const buildWorkoutPlanExerciseGuideLines = async (planData) => {
  const names = collectPlanExerciseNames(planData);
  if (!names.length) return [];

  const records = await fetchExerciseRecords(names);
  const lines = [
    { text: 'Exercise Guide - How to Perform Each Movement', kind: 'section' },
    { text: 'Every exercise in this plan, explained. Watch the linked demo where available, or use the suggested YouTube search until the full SwanStudios video library covers it.', kind: 'meta' },
  ];
  names.forEach((name) => {
    lines.push(...guideEntryLines(name, records.get(name.toLowerCase())));
  });
  return lines;
};
