/**
 * Workout Planner PDF source adapter.
 *
 * Converts the exact saved `planData` payload into a compact SwanStudios PDF
 * file for upload. This keeps attached PDFs tied to saved plan truth, not a
 * stale UI preview snapshot.
 */
import type { jsPDF as PdfDoc } from 'jspdf';
import { normalizeClientSource } from '../../../../utils/clientSource';
import { workoutPlanHorizonForKey } from '../../../../utils/workoutPlanHorizonTokens';
import type { BuildPlanPdfFileInput, PrintablePlan } from './workoutPlannerPlanPdfData';
import {
  buildPdfPlanFromPlanData,
  clientSafePdfString,
  getClientDisplayName,
  getExerciseDose,
  getExerciseName,
  safeFilenamePart,
} from './workoutPlannerPlanPdfData';
import { renderPlanningSignalLines } from './workoutPlannerPlanPdfSignals';
const BRAND = {
  midnight: [0, 32, 96] as [number, number, number],
  royal: [0, 48, 128] as [number, number, number],
  purple: [139, 92, 246] as [number, number, number],
  gold: [198, 168, 75] as [number, number, number],
  frost: [224, 236, 244] as [number, number, number],
  ink: [31, 41, 55] as [number, number, number],
  muted: [91, 103, 122] as [number, number, number],
  white: [255, 255, 255] as [number, number, number],
};

const addPageIfNeeded = (doc: PdfDoc, y: number, needed = 12) => {
  if (y + needed <= doc.internal.pageSize.getHeight() - 18) return y;
  doc.addPage();
  return 18;
};

const addWrappedText = (doc: PdfDoc, text: string, x: number, y: number, maxWidth: number, lineHeight = 5) => {
  const lines = doc.splitTextToSize(text, maxWidth) as string[];
  doc.text(lines, x, y);
  return y + (lines.length * lineHeight);
};

const addSectionTitle = (doc: PdfDoc, title: string, y: number) => {
  const pageW = doc.internal.pageSize.getWidth();
  y = addPageIfNeeded(doc, y, 12);
  doc.setFillColor(...BRAND.frost);
  doc.rect(14, y - 5, pageW - 28, 8, 'F');
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(10);
  doc.setTextColor(...BRAND.midnight);
  doc.text(title, 16, y);
  return y + 10;
};

const addFooter = (doc: PdfDoc) => {
  const totalPages = doc.getNumberOfPages();
  const pageW = doc.internal.pageSize.getWidth();
  const pageH = doc.internal.pageSize.getHeight();

  for (let page = 1; page <= totalPages; page += 1) {
    doc.setPage(page);
    doc.setDrawColor(...BRAND.frost);
    doc.line(14, pageH - 12, pageW - 14, pageH - 12);
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(7);
    doc.setTextColor(...BRAND.muted);
    doc.text('Generated by SwanStudios', 14, pageH - 6);
    doc.text(`Page ${page} of ${totalPages}`, pageW - 14, pageH - 6, { align: 'right' });
  }
};

const renderPlanPdfBlob = (doc: PdfDoc, plan: PrintablePlan, clientName: string, clientSource?: string) => {
  const pageW = doc.internal.pageSize.getWidth();
  let y = 24;

  doc.setFillColor(...BRAND.midnight);
  doc.rect(0, 0, pageW, 18, 'F');
  doc.setFillColor(...BRAND.purple);
  doc.rect(0, 18, pageW, 1.5, 'F');
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(14);
  doc.setTextColor(...BRAND.white);
  doc.text('SwanStudios', 14, 12);
  doc.setFontSize(9);
  doc.text('WORKOUT PLAN PDF', pageW - 14, 9, { align: 'right' });
  doc.setFontSize(7);
  doc.setTextColor(...BRAND.frost);
  doc.text(clientName, pageW - 14, 14, { align: 'right' });

  if (normalizeClientSource(clientSource) === 'move_fitness') {
    doc.setFontSize(7);
    doc.setTextColor(...BRAND.gold);
    doc.text('IN PARTNERSHIP WITH MOVE FITNESS', pageW - 14, 21, { align: 'right' });
  }

  y = addSectionTitle(doc, 'Plan Summary', y);
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(9);
  doc.setTextColor(...BRAND.ink);
  [
    `Duration: ${plan.planSummary.durationWeeks} weeks`,
    `Sessions per week: ${plan.planSummary.sessionsPerWeek}`,
    `Total sessions: ${plan.planSummary.totalSessions}`,
    `Primary goal: ${plan.planSummary.primaryGoal}`,
    `Starting NASM phase: Phase ${plan.planSummary.startingPhase}`,
  ].forEach((line) => {
    y = addWrappedText(doc, line, 16, y, pageW - 32);
  });

  y = renderPlanningSignalLines({
    doc, lines: plan.planningSignalLines, y, pageW, ink: BRAND.ink, addSectionTitle, addWrappedText,
  });

  if (plan.recommendations.length > 0) {
    y += 2;
    y = addSectionTitle(doc, 'Coach Recommendations', y);
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(8);
    doc.setTextColor(...BRAND.ink);
    // fallow-ignore-next-line complexity
    plan.recommendations.forEach((recommendation) => {
      y = addPageIfNeeded(doc, y, 10);
      y = addWrappedText(doc, `- ${recommendation}`, 18, y, pageW - 36, 4.5);
    });
  }

  y += 2;
  y = addSectionTitle(doc, 'Weekly Plan', y);
  // fallow-ignore-next-line complexity
  plan.weeks.forEach((week, weekIndex) => {
    const weekNumber = week.weekNumber || weekIndex + 1;
    y = addPageIfNeeded(doc, y, 12);
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(9);
    doc.setTextColor(...BRAND.purple);
    const weekFocus = clientSafePdfString(week.focus, '', 120);
    y = addWrappedText(doc, `Week ${weekNumber}${weekFocus ? ` - ${weekFocus}` : ''}`, 16, y, pageW - 32, 5);

    const days = (week.days?.length ? week.days : week.sessions) || [];
    // fallow-ignore-next-line complexity
    days.forEach((day, dayIndex) => {
      y = addPageIfNeeded(doc, y, 14);
      doc.setFont('helvetica', 'bold');
      doc.setFontSize(8);
      doc.setTextColor(...BRAND.royal);
      const dayName = clientSafePdfString(day.name || day.dayName, `Day ${day.dayNumber || dayIndex + 1}`, 140);
      y = addWrappedText(doc, dayName, 18, y, pageW - 36, 4.5);

      doc.setFont('helvetica', 'normal');
      doc.setFontSize(8);
      doc.setTextColor(...BRAND.ink);
      const exercises = Array.isArray(day.exercises) ? day.exercises : [];
      // fallow-ignore-next-line complexity
      exercises.forEach((exercise) => {
        y = addPageIfNeeded(doc, y, 9);
        y = addWrappedText(doc, `${getExerciseName(exercise)} - ${getExerciseDose(exercise)}`, 22, y, pageW - 42, 4.5);
      });
      y += 1;
    });
  });

  addFooter(doc);
  return doc.output('blob');
};

export const buildPlanPdfFileFromPlanData = async ({
  planData,
  selectedClient,
  goal,
  nasmPhase,
  durationWeeks,
  horizonKey,
}: BuildPlanPdfFileInput): Promise<File | null> => {
  if (typeof File === 'undefined') return null;

  const pdfPlan = buildPdfPlanFromPlanData(planData, { goal, nasmPhase, durationWeeks });
  if (!pdfPlan) return null;

  const { jsPDF } = await import('jspdf');
  const doc = new jsPDF({ orientation: 'portrait', unit: 'mm', format: 'a4' });
  const clientName = getClientDisplayName(selectedClient);
  const blob = renderPlanPdfBlob(doc, pdfPlan, clientName, selectedClient?.clientSource);
  const horizonToken = workoutPlanHorizonForKey(horizonKey, pdfPlan.planSummary.durationWeeks).token;
  const filename = `SwanStudios-${horizonToken}-Plan-${safeFilenamePart(clientName)}.pdf`;

  return new File([blob], filename, { type: 'application/pdf', lastModified: Date.now() });
};
