import type {
  AppearanceProfile,
  RendererAllowlist,
} from './types';

export const MANIFEST_SCHEMA_VERSION = 1;
export const PROFILE_SCHEMA_VERSION = 1;
export const DEFAULT_STYLE_LENS_ID = 'default-safety';
export const DEFAULT_PALETTE_THEME_ID = 'crystalline-dark';

export const CORE_RENDERER_ALLOWLIST: RendererAllowlist = Object.freeze({
  shell: Object.freeze([
    'default-shell',
    'flagship-shell',
    'calm-column-shell',
    'folded-grid-shell',
    'fracture-shell',
    'instrument-shell',
    'arcade-shell',
    'recovery-cloister-shell',
    'tempo-forge-shell',
    'coach-ledger-shell',
    'signal-garden-shell',
    'split-horizon-shell',
    'prism-terminal-shell',
    'tidal-columns-shell',
    'monastic-grid-shell',
    'orbit-atlas-shell',
    'carbon-atelier-shell',
    'kinetic-kanban-shell',
    'aurora-index-shell',
    'aurora-console-shell',
    'modular-harbor-shell',
    'terrain-console-shell',
    'chronograph-board-shell',
    'glass-rail-shell',
    'meridian-magazine-shell',
    'lunar-stack-shell',
    'cedar-workshop-shell',
    'crystalline-cathedral-shell',
  ]),
  navigation: Object.freeze([
    'default-navigation',
    'flagship-navigation',
    'quiet-rail-navigation',
    'blueprint-tabs-navigation',
    'circuit-orbit-navigation',
    'instrument-strip-navigation',
    'arcade-dock-navigation',
    'cloister-bottom-navigation',
    'tempo-strip-navigation',
    'ledger-index-navigation',
    'garden-branch-navigation',
    'horizon-dock-navigation',
    'prism-command-navigation',
    'tidal-ribbon-navigation',
    'monastic-index-navigation',
    'orbital-map-navigation',
    'atelier-toolrail-navigation',
    'swimlane-pulse-navigation',
    'aurora-index-navigation',
    'aurora-console-navigation',
    'harbor-berth-navigation',
    'contour-map-navigation',
    'chrono-dial-navigation',
    'glass-spine-navigation',
    'magazine-folio-navigation',
    'lunar-beacon-navigation',
    'workshop-parts-navigation',
    'cathedral-apse-navigation',
  ]),
  recipes: Object.freeze([
    'default-recipe',
    'flagship-recipe',
    'quiet-recipe',
    'blueprint-recipe',
    'kintsugi-recipe',
    'instrument-recipe',
    'arcade-recipe',
    'recovery-cloister-recipe',
    'tempo-forge-recipe',
    'coach-ledger-recipe',
    'signal-garden-recipe',
    'split-horizon-recipe',
    'prism-terminal-recipe',
    'tidal-columns-recipe',
    'monastic-grid-recipe',
    'orbit-atlas-recipe',
    'carbon-atelier-recipe',
    'kinetic-kanban-recipe',
    'aurora-index-recipe',
    'aurora-console-recipe',
    'modular-harbor-recipe',
    'terrain-console-recipe',
    'chronograph-board-recipe',
    'glass-rail-recipe',
    'meridian-magazine-recipe',
    'lunar-stack-recipe',
    'cedar-workshop-recipe',
    'crystalline-cathedral-recipe',
  ]),
});

export const DEFAULT_APPEARANCE_PROFILE: AppearanceProfile = Object.freeze({
  profileSchemaVersion: PROFILE_SCHEMA_VERSION,
  paletteThemeId: DEFAULT_PALETTE_THEME_ID,
  styleLensId: DEFAULT_STYLE_LENS_ID,
  motionMode: 'auto',
  density: 'comfortable',
  updatedAt: '1970-01-01T00:00:00.000Z',
});
