// Cache invalidation marker: 2025-05-09T22:15:00.000Z
// This file is automatically updated to force Vite to invalidate its module cache
// Do not edit this file manually

export const CACHE_VERSION = '2025-05-09T22:15:00.000Z';
