@echo off
echo Restarting frontend with updated configuration...
cd frontend
echo Killing any existing frontend processes...
taskkill /f /im node.exe 2>nul
echo Waiting 2 seconds...
timeout /t 2 /nobreak >nul
echo Starting frontend...
npm run dev
