#!/bin/bash
echo "========================================"
echo "EMERGENCY PRODUCTION LOGIN FIX"
echo "========================================"
echo ""
echo "This script will:"
echo "1. Add missing deletedAt column"
echo "2. Create test users (admin, trainer, client)"
echo "3. Test login functionality"
echo ""
echo "Username: admin"
echo "Password: admin123"
echo ""
echo "========================================"
echo ""

cd "C:/Users/ogpsw/Desktop/quick-pt/SS-PT"
node emergency-login-fix.mjs

echo ""
echo "========================================"
echo "FIX COMPLETED"
echo "========================================"
echo ""
echo "Now test login at: https://ss-pt-new.onrender.com"
echo "Username: admin"
echo "Password: admin123"
echo ""
read -p "Press Enter to continue..."
