import { Flame, Moon, Shield, Sparkles, Target } from 'lucide-react';
import type { JobClassConfig } from './JobClassSelector.types';

export const JOB_CLASSES: JobClassConfig[] = [
  {
    id: 'paladin',
    name: 'Paladin',
    title: 'The Unyielding Guardian',
    icon: Shield,
    color: 'var(--accent-primary, #60C0F0)',
    description: 'Masters of defense and endurance. Paladins thrive under heavy loads and long training sessions. Their strength is their shield.',
    bonusText: '+15% XP from strength exercises',
    focus: 'Heavy compound lifts, powerlifting, strongman',
    xpMultiplier: 1.15,
    matchingCategories: ['strength', 'chest', 'back', 'legs'],
  },
  {
    id: 'monk',
    name: 'Monk',
    title: 'The Flowing Fist',
    icon: Flame,
    color: 'var(--accent-gold, #C6A84B)',
    description: 'Speed, precision, and bodyweight mastery. Monks combine martial discipline with explosive power. Their body is their weapon.',
    bonusText: '+15% XP from bodyweight and martial arts',
    focus: 'Calisthenics, martial arts, HIIT, plyometrics',
    xpMultiplier: 1.15,
    matchingCategories: ['bodyweight', 'cardio', 'full_body', 'plyometrics'],
  },
  {
    id: 'ranger',
    name: 'Ranger',
    title: 'The Enduring Scout',
    icon: Target,
    color: 'var(--success, #4ADE80)',
    description: 'Built for distance and endurance. Rangers excel at sustained effort across running, cycling, and swimming.',
    bonusText: '+15% XP from cardio and endurance',
    focus: 'Running, cycling, swimming, steady-state cardio',
    xpMultiplier: 1.15,
    matchingCategories: ['cardio', 'endurance', 'running', 'cycling'],
  },
  {
    id: 'white_mage',
    name: 'White Mage',
    title: 'The Restoring Light',
    icon: Sparkles,
    color: 'var(--text-primary, #E0ECF4)',
    description: 'Recovery specialists. White Mages focus on flexibility, corrective exercise, balance, and rebuilding capacity.',
    bonusText: '+15% XP from recovery and flexibility',
    focus: 'Stretching, corrective exercise, stability, balance',
    xpMultiplier: 1.15,
    matchingCategories: ['stretching', 'recovery', 'stability', 'balance'],
  },
  {
    id: 'dark_knight',
    name: 'Dark Knight',
    title: 'The Abyssal Blade',
    icon: Moon,
    color: 'var(--accent-secondary, #8B5CF6)',
    description: 'Power through intensity. Dark Knights push limits with max effort, supersets, and demanding circuits.',
    bonusText: '+15% XP from high-intensity training',
    focus: 'Max strength, supersets, circuits, power training',
    xpMultiplier: 1.15,
    matchingCategories: ['power', 'olympic', 'circuit', 'maximal_strength'],
  },
];
