services:
  - type: web
    name: swan-studios-api
    env: node
    region: oregon
    plan: starter
    buildCommand: npm install && cd frontend && npm install && npm run build
    startCommand: node server.mjs
    
    # REMOVE PLATFORM HEADERS - FULL APPLICATION CONTROL
    # Platform headers can interfere with root-level endpoints like /health
    # Let ultra-aggressive CORS in app.mjs handle everything
    # headers:
    #   - path: /*
    #     name: Access-Control-Allow-Origin
    #     value: "*"
    
    # PRODUCTION ENVIRONMENT VARIABLES
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      
      # CORS CONFIGURATION
      - key: FRONTEND_ORIGINS
        value: "https://sswanstudios.com,https://www.sswanstudios.com,https://swanstudios.com,https://www.swanstudios.com"
      
      # FORCE APPLICATION-LEVEL CORS HANDLING
      - key: FORCE_APP_CORS
        value: "true"
      
      # JWT CONFIGURATION
      - key: JWT_SECRET
        value: "your-jwt-secret-key-here"
      - key: JWT_REFRESH_SECRET
        value: "your-jwt-refresh-secret-here"
      - key: JWT_EXPIRES_IN
        value: "3h"
      - key: ACCESS_TOKEN_EXPIRY
        value: "10800"
      - key: REFRESH_TOKEN_EXPIRES_IN
        value: "7d"
      
      # ADMIN ACCESS
      - key: ADMIN_ACCESS_CODE
        value: "admin-access-code-123"
      
      # PRODUCTION SETTINGS
      - key: ENABLE_MCP_SERVICES
        value: "false"
      - key: USE_SQLITE_FALLBACK
        value: "false"
      - key: REDIS_ENABLED
        value: "false"
      - key: DISABLE_REDIS
        value: "true"
      - key: NO_REDIS
        value: "true"
