services:
  - type: web
    name: swan-studios-api
    env: node
    region: oregon
    plan: starter
    buildCommand: npm install
    startCommand: npm run render-start
    
    # ENHANCED PLATFORM-LEVEL CORS HEADERS (ULTRA-EXPLICIT FOR OPTIONS)
    # These headers are set by Render's proxy layer for ALL requests including OPTIONS
    # DUAL-LAYER APPROACH: Platform + Application handling for maximum compatibility
    headers:
      # Primary CORS headers for all requests
      - path: /*
        name: Access-Control-Allow-Origin
        value: https://sswanstudios.com
      - path: /*
        name: Access-Control-Allow-Methods
        value: GET, POST, PUT, DELETE, OPTIONS, PATCH
      - path: /*
        name: Access-Control-Allow-Headers
        value: Content-Type, Authorization, X-Requested-With, Accept, Origin, Access-Control-Request-Method, Access-Control-Request-Headers
      - path: /*
        name: Access-Control-Allow-Credentials
        value: "true"
      - path: /*
        name: Access-Control-Max-Age
        value: "86400"
      
      # EXPLICIT API ROUTE CORS (redundant but ensures coverage)
      - path: /api/*
        name: Access-Control-Allow-Origin
        value: https://sswanstudios.com
      - path: /api/*
        name: Access-Control-Allow-Methods
        value: GET, POST, PUT, DELETE, OPTIONS, PATCH
      - path: /api/*
        name: Access-Control-Allow-Headers
        value: Content-Type, Authorization, X-Requested-With, Accept, Origin, Access-Control-Request-Method, Access-Control-Request-Headers
      - path: /api/*
        name: Access-Control-Allow-Credentials
        value: "true"
      
      # HEALTH ENDPOINT CORS
      - path: /health
        name: Access-Control-Allow-Origin
        value: https://sswanstudios.com
      - path: /health
        name: Access-Control-Allow-Methods
        value: GET, OPTIONS
      - path: /health
        name: Access-Control-Allow-Credentials
        value: "true"
    
    # PRODUCTION ENVIRONMENT VARIABLES
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      
      # CORS CONFIGURATION - PRODUCTION DOMAINS ONLY
      # (localhost origins handled by defaultOrigins in code)
      - key: FRONTEND_ORIGINS
        value: "https://sswanstudios.com,https://www.sswanstudios.com,https://swanstudios.com,https://www.swanstudios.com"
      
      # JWT CONFIGURATION
      - key: JWT_SECRET
        value: "your-jwt-secret-key-here"
      - key: JWT_REFRESH_SECRET
        value: "your-jwt-refresh-secret-here"
      - key: JWT_EXPIRES_IN
        value: "3h"
      - key: ACCESS_TOKEN_EXPIRY
        value: "10800"
      - key: REFRESH_TOKEN_EXPIRES_IN
        value: "7d"
      
      # ADMIN ACCESS
      - key: ADMIN_ACCESS_CODE
        value: "admin-access-code-123"
      
      # PRODUCTION SETTINGS
      - key: ENABLE_MCP_SERVICES
        value: "false"
      - key: USE_SQLITE_FALLBACK
        value: "false"
      - key: REDIS_ENABLED
        value: "false"
