services:
  - type: web
    name: swan-studios-api
    env: node
    buildCommand: npm install
    startCommand: npm run render-start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: FRONTEND_ORIGINS
        value: "https://sswanstudios.com,https://www.sswanstudios.com,http://localhost:5173,http://localhost:5174"
      - key: ENABLE_MCP_HEALTH_CHECKS
        value: "false"
      - key: ENABLE_MCP_HEALTH_ALERTS
        value: "false"
      - key: ENABLE_MCP_SERVICES
        value: "false"
      - key: JWT_SECRET
        value: "your-production-jwt-secret-key-here-change-this"
      - key: ACCESS_TOKEN_EXPIRY
        value: "3600"
      - key: USE_SQLITE_FALLBACK
        value: "false"
    # Remove static CORS headers - let Express handle CORS dynamically
    # Static headers with * origin conflict with credentials: true