import React from 'react';
import { EXERCISE_LIBRARY_CLAIM } from '../../content/marketingStats';
import { CANONICAL_SURFACES } from '../../config/canonical-surface-names';
import {
  AdminClientDetailsRedirect,
  AdminLogWorkoutRedirect,
  AdminClientProgressView,
  AdminGalleryStudio,
  AdminGamificationView,
  AdminPackagesView,
  AdminPersonalWorkoutLogger,
  AdminPlaudCommandCenterRedirect,
  AdminViewAsWrapper,
  AdminWaiversManagerPage,
  AdminWorkoutPlansRedirect,
  AiConsentScreen,
  AutomationManager,
  AvatarHomePage,
  BadgeCreatorPage,
  BodyMapPage,
  BootcampBuilderPage,
  CanadaImmigrationTab,
  ChallengeCommandWorkspace,
  ClientCommunityPage,
  ClientChallengesPage,
  ClientHomeTab,
  ClientMealPlannerRoute,
  ClientMyWorkoutsPage,
  ClientOnboardingWizard,
  ClientProfilePage,
  ClientProgressDashboardPage,
  ClientProgressWrapper,
  ClientRewardsPage,
  ClientSelfOnboardingPage,
  ClientTrainerAssignments,
  ClientsWorkspace,
  CoachCommandCenterPage,
  ContentStudioHub,
  CreatorEconomyPage,
  EnhancedAdminSessionsView,
  EnhancedClientProgressView,
  EnhancedTrainerDataManagement,
  EnhancedUserDataManagement,
  EnhancedWorkoutLogger,
  EquipmentManagerPage,
  FeatureAccessPage,
  LiveStreamingPage,
  MarketingWorkspace,
  MessagingPageLazy,
  ModernUserManagementSystem,
  TrainerClientsWorkspace,
  NotesManager,
  OwnerSupportInboxPage,
  AdminCreateSpecialManager,
  AdminAccountAccessPage,
  LaunchControlPage,
  NutritionPlanBuilder,
  NutritionWorkspaceLazy,
  PendingOrdersAdminPanel,
  PhotoManager,
  PlaudIntelligenceWorkspacePage,
  RevenueAnalyticsPanel,
  AdminTrainerPayoutsPanel,
  RevolutionaryAdminDashboard,
  SMSLogsPanel,
  SecurityWorkspace,
  SessionAllocationManager,
  SprintPlannerPage,
  TheAestheticCodex,
  TrainerAssessmentsPage,
  TrainerEarningsPage,
  TrainerHomeTab,
  TrainerPermissionsManager,
  TrainerBuildPlanRedirect,
  TrainerWorkoutForgePage,
  TrainersManagementSection,
  UnifiedOnboardingWizard,
  UniversalSchedule,
  VideoCallPage,
  VideoLibraryPage,
  VirtualOlympicsPage,
  WorkoutLogger,
  WorkoutPlannerPage,
  WorkoutDesignLabPage,
} from './UniversalDashboardLayout.routeComponents';

export interface DashboardRouteDefinition {
  path: string;
  component: React.ElementType;
  title: string;
  description: string;
}

export interface RoleConfig {
  routes: DashboardRouteDefinition[];
  defaultPath: string;
}

export type DashboardRoleKey = 'admin' | 'trainer' | 'client';

export const roleConfigurations: Record<DashboardRoleKey, RoleConfig> = {
  admin: {
    routes: [
      { path: '/overview', component: RevolutionaryAdminDashboard, title: 'Command Center', description: 'Administrative oversight' },
      { path: '/support', component: OwnerSupportInboxPage, title: 'Report Room Inbox', description: 'Private issue triage and agent-ready repair prompts' },
      { path: '/coach-assistant', component: CoachCommandCenterPage, title: 'Coach Command Center', description: 'Review-gated Swan Coach command observatory' },
      { path: '/user-management', component: EnhancedUserDataManagement, title: 'User Data Management', description: 'Complete user data collection & lifecycle management' },
      { path: '/user-management-legacy', component: ModernUserManagementSystem, title: 'User Management (Legacy)', description: 'Traditional user management interface' },
      { path: '/trainer-management', component: EnhancedTrainerDataManagement, title: 'Trainer Data Management', description: 'Complete trainer data collection, certs & performance' },
      { path: '/trainer-management-legacy', component: TrainersManagementSection, title: 'Trainer Management (Legacy)', description: 'Traditional trainer oversight interface' },
      { path: '/client-management', component: ClientsWorkspace, title: 'Client Hub', description: 'Unified client management with selector, cards, and detail tabs' },
      { path: '/client-management/view-as/:userId', component: AdminViewAsWrapper, title: 'View As Client', description: 'Read-only admin impersonation view of a single client profile, workouts, sessions, and gamification' },
      { path: '/account-access', component: AdminAccountAccessPage, title: 'Account Access', description: 'Log in as any client or trainer (audited), plus block, deactivate, reactivate, and force-logout' },
      { path: '/launch-control', component: LaunchControlPage, title: 'Launch Control', description: 'Manage approved feature switches from inside the app — instant, no redeploy' },
      { path: '/client-details', component: AdminClientDetailsRedirect, title: 'Client Hub', description: 'Redirects legacy client details to the canonical Client Hub' },
      { path: '/client-onboarding', component: ClientOnboardingWizard, title: 'Client Onboarding', description: 'New client data collection workflow' },
      { path: '/client-progress-tracking', component: AdminClientProgressView, title: 'Client Progress Analytics', description: 'Client progress monitoring & analytics' },
      { path: '/nutrition/:clientId?', component: NutritionPlanBuilder, title: 'Nutrition Plan Builder', description: 'Create and update client nutrition plans' },
      { path: '/admin-specials', component: AdminCreateSpecialManager, title: 'Client Deals', description: 'Create per-client custom session deals (bonus-session pricing)' },
      { path: '/workouts/:clientId?', component: AdminWorkoutPlansRedirect, title: CANONICAL_SURFACES.workoutPlanner.name, description: 'Redirects legacy admin workouts links into the Workout Planner' },
      { path: '/notes/:clientId?', component: NotesManager, title: 'Client Notes Manager', description: 'Manage trainer notes and observations' },
      { path: '/photos/:clientId?', component: PhotoManager, title: 'Client Photo Manager', description: 'Upload and organize progress photos' },
      { path: '/gallery', component: AdminGalleryStudio, title: 'Photo Gallery Studio', description: 'Passcode photoshoot galleries — create events and batch-upload client shoots' },
      { path: '/automation', component: AutomationManager, title: 'Automation Manager', description: 'Manage automated client outreach sequences' },
      { path: '/sms-logs', component: SMSLogsPanel, title: 'SMS Logs', description: 'Monitor outbound SMS delivery' },
      { path: '/unified-onboarding', component: UnifiedOnboardingWizard, title: 'Unified Onboarding', description: 'Complete data collection for all user types' },
      { path: '/user-onboarding', component: UnifiedOnboardingWizard, title: 'Add New User', description: 'General user registration' },
      { path: '/trainer-onboarding', component: UnifiedOnboardingWizard, title: 'Add New Trainer', description: 'Trainer registration with certifications' },
      { path: '/admin-sessions', component: EnhancedAdminSessionsView, title: 'Session Management', description: 'Universal session control' },
      { path: '/master-schedule', component: UniversalSchedule, title: 'Universal Master Schedule', description: 'Advanced drag-and-drop scheduling command center' },
      { path: '/session-allocation', component: SessionAllocationManager, title: 'Session Allocation Manager', description: 'Manage client session counts and allocation' },
      { path: '/client-trainer-assignments', component: ClientTrainerAssignments, title: 'Client-Trainer Assignments', description: 'Drag-and-drop client assignment management' },
      { path: '/trainer-permissions', component: TrainerPermissionsManager, title: 'Trainer Permissions', description: 'Granular trainer permission control' },
      { path: '/admin-packages', component: AdminPackagesView, title: 'Package Management', description: 'Training package configuration' },
      { path: '/revenue', component: RevenueAnalyticsPanel, title: 'Revenue Analytics', description: 'Financial performance tracking' },
      { path: '/trainer-payouts', component: AdminTrainerPayoutsPanel, title: 'Trainer Payouts', description: 'Commission ledger — trainer balances, mark-paid settlement, payout history' },
      { path: '/pending-orders', component: PendingOrdersAdminPanel, title: 'Pending Orders', description: 'Order management system' },
      { path: '/gamification', component: AdminGamificationView, title: 'Gamification Engine', description: 'Achievement system control' },
      { path: '/challenges', component: ChallengeCommandWorkspace, title: 'Challenges', description: 'Challenge templates, live campaigns, results, submissions, and settings' },
      { path: '/style-guide', component: TheAestheticCodex, title: 'The Aesthetic Codex', description: 'Living style guide and design system foundation' },
      { path: '/workout-design-lab', component: WorkoutDesignLabPage, title: 'Workout Design Lab', description: '25 workout Worlds plus the full Style Lens catalog for the unified client workout workflow' },
      { path: '/content', component: ContentStudioHub, title: 'Content Studio', description: 'Video and content management' },
      { path: '/feature-access', component: FeatureAccessPage, title: 'Feature Access', description: 'Per-user feature flag management' },
      { path: '/immigration', component: CanadaImmigrationTab, title: 'Canada Immigration', description: 'Immigration tracker & study platform' },
      { path: '/log-workout', component: AdminLogWorkoutRedirect, title: 'Log Client Workout', description: 'Redirects to the Client Hub workout logger' },
      { path: '/log-my-workout', component: AdminPersonalWorkoutLogger, title: 'Log My Workout', description: 'Owner personal workout logger' },
      { path: '/plaud', component: AdminPlaudCommandCenterRedirect, title: 'Coach Command Center', description: 'Redirects PLAUD intake into the unified admin Coach Command Center' },
      { path: '/workout-planner', component: WorkoutPlannerPage, title: CANONICAL_SURFACES.workoutPlanner.name, description: `Build periodized training programs with ${EXERCISE_LIBRARY_CLAIM} exercises` },
      { path: '/equipment', component: EquipmentManagerPage, title: 'Equipment Manager', description: 'Manage training environments and equipment profiles' },
      { path: '/bootcamp', component: BootcampBuilderPage, title: 'Bootcamp Creator', description: 'Swan Coach group fitness class builder with pyramids, supersets, and flow optimization' },
      { path: '/marketing', component: MarketingWorkspace, title: 'Marketing', description: 'Campaign approvals, publishing cadence, lead follow-up, and performance signals' },
      { path: '/security', component: SecurityWorkspace, title: 'Security Intelligence', description: 'Vulnerability scanning, dependency health, and security posture' },
      { path: '/body-map', component: BodyMapPage, title: 'Pain Charts', description: 'Client pain and injury tracking (body map)' },
      { path: '/meal-planner', component: NutritionWorkspaceLazy, title: 'Nutrition Intelligence', description: 'Log meals, track macros, and explore food data' },
      { path: '/messages', component: MessagingPageLazy, title: 'Messages', description: 'Communication hub for clients and trainers' },
      { path: '/sprint-planner', component: SprintPlannerPage, title: 'Sprint Planner', description: '3-month bootcamp sprint planning + calendar' },
      { path: '/video-call', component: VideoCallPage, title: 'Video Assessment', description: 'Remote movement screens, postural analysis via video' },
      { path: '/my-home', component: AvatarHomePage, title: 'My Home', description: '3D avatar home - unlocks at Level 10' },
      { path: '/virtual-olympics', component: VirtualOlympicsPage, title: 'Virtual Olympics', description: 'Ghost Racing competitive events - Pull-ups, Push-ups, Sprint' },
      { path: '/badge-creator', component: BadgeCreatorPage, title: 'Badge Creator', description: 'AI-powered badge and icon generation studio' },
      { path: '/waivers', component: AdminWaiversManagerPage, title: 'Waiver Management', description: 'Waiver records, match approval, revocation, and manual linking' },
    ],
    defaultPath: '/master-schedule',
  },
  trainer: {
    routes: [
      { path: '/overview', component: TrainerHomeTab, title: 'Home', description: 'Your trainer operations hub' },
      { path: '/clients', component: TrainerClientsWorkspace, title: 'My Clients', description: 'Assigned-client command center: Today/Plan training, progress proof, nutrition, biometrics' },
      { path: '/earnings', component: TrainerEarningsPage, title: 'My Earnings', description: 'Commission ledger — attributed sales, unpaid balance, payout history' },
      { path: '/log-workout', component: EnhancedWorkoutLogger, title: 'Log Client Workout', description: 'Enhanced NASM-compliant workout logging interface with client integration' },
      { path: '/client-progress', component: EnhancedClientProgressView, title: 'Client Progress Analytics', description: 'Advanced client progress tracking with comparison analytics, injury risk assessment, and goal management' },
      { path: '/assessments', component: TrainerAssessmentsPage, title: 'Form Assessments', description: 'Swan Coach form checking' },
      { path: '/videos', component: VideoLibraryPage, title: 'Video Library', description: 'Training video content library' },
      { path: '/build-plan', component: TrainerWorkoutForgePage, title: CANONICAL_SURFACES.buildPlan.name, description: 'Draft a client workout with the Swan Coach copilot' },
      { path: '/workout-forge', component: TrainerBuildPlanRedirect, title: CANONICAL_SURFACES.buildPlan.name, description: 'Redirects the legacy workout-forge path to Build Plan' },
      { path: '/challenges', component: ChallengeCommandWorkspace, title: 'Challenges', description: 'Create and monitor client challenge campaigns' },
      { path: '/plaud', component: PlaudIntelligenceWorkspacePage, title: 'PLAUD Intelligence Workspace', description: 'PLAUD intake, merge review, and Swan Coach handoff' },
      { path: '/workout-planner', component: WorkoutPlannerPage, title: CANONICAL_SURFACES.workoutPlanner.name, description: `Build periodized training programs with ${EXERCISE_LIBRARY_CLAIM} exercises` },
      { path: '/meal-planner', component: NutritionWorkspaceLazy, title: 'Nutrition Intelligence', description: 'Log meals, track macros, and explore food data' },
      { path: '/nutrition/:clientId?', component: NutritionPlanBuilder, title: 'Nutrition Plan Builder', description: 'Set client nutrition targets (assignment-checked server-side)' },
      { path: '/schedule', component: UniversalSchedule, title: 'My Schedule', description: 'Personal appointment calendar' },
      { path: '/messages', component: MessagingPageLazy, title: 'Client Messages', description: 'Communication hub' },
      { path: '/live', component: LiveStreamingPage, title: 'Live Streams', description: 'Stream live workouts to clients' },
      { path: '/creators', component: CreatorEconomyPage, title: 'Creators', description: 'Creator program and content monetization' },
      { path: '/equipment', component: EquipmentManagerPage, title: 'Equipment Manager', description: 'Manage training environments and equipment profiles' },
      { path: '/bootcamp', component: BootcampBuilderPage, title: 'Bootcamp Creator', description: 'Swan Coach group fitness class builder' },
      { path: '/body-map', component: BodyMapPage, title: 'Client Pain Charts', description: 'View and manage client pain and injury tracking' },
      { path: '/sprint-planner', component: SprintPlannerPage, title: 'Sprint Planner', description: '3-month bootcamp sprint planning + calendar' },
      { path: '/video-call', component: VideoCallPage, title: 'Video Assessment', description: 'Remote movement screens, postural analysis via video' },
      { path: '/my-home', component: AvatarHomePage, title: 'My Home', description: '3D avatar home - unlocks at Level 10' },
      { path: '/coach-assistant', component: CoachCommandCenterPage, title: 'Coach Command Center', description: 'Review-gated trainer command bridge' },
      { path: '/virtual-olympics', component: VirtualOlympicsPage, title: 'Virtual Olympics', description: 'Ghost Racing competitive events' },
    ],
    defaultPath: '/schedule',
  },
  client: {
    routes: [
      { path: '/overview', component: ClientHomeTab, title: 'Home', description: 'Your fitness journey hub' },
      { path: '/overview/:tab', component: ClientHomeTab, title: 'Home', description: 'Your fitness journey hub' },
      { path: '/onboarding', component: ClientSelfOnboardingPage, title: 'Client Onboarding', description: 'Complete your SwanStudios onboarding' },
      { path: '/workouts', component: ClientMyWorkoutsPage, title: 'My Workouts', description: 'Workout history with per-set detail' },
      { path: '/log-workout', component: WorkoutLogger, title: 'Log Workout', description: 'Log your workout session' },
      { path: '/progress', component: ClientProgressDashboardPage, title: 'My Progress', description: 'Progress dashboard with stats, charts, and gamification' },
      { path: '/progress/detailed', component: ClientProgressWrapper, title: 'Detailed Analytics', description: 'NASM 14-chart analytics dashboard' },
      { path: '/ai-consent', component: AiConsentScreen, title: 'Swan Coach Privacy & Consent', description: 'Manage Swan Coach data consent' },
      { path: '/meal-planner', component: ClientMealPlannerRoute, title: 'Nutrition Intelligence', description: 'Log meals, track macros, and explore food data' },
      { path: '/schedule', component: UniversalSchedule, title: 'Book My Session', description: 'Session booking interface' },
      { path: '/community', component: ClientCommunityPage, title: 'Community', description: 'Social feed and challenges' },
      { path: '/challenges', component: ClientChallengesPage, title: 'Challenges', description: 'Active, upcoming, and completed challenge campaigns' },
      { path: '/messages', component: MessagingPageLazy, title: 'Messages', description: 'Trainer communications' },
      { path: '/live', component: LiveStreamingPage, title: 'Live Streams', description: 'Watch and join live workout streams' },
      { path: '/creators', component: CreatorEconomyPage, title: 'Creators', description: 'Creator program and content monetization' },
      { path: '/profile', component: ClientProfilePage, title: 'Profile', description: 'Personal settings and preferences' },
      { path: '/rewards', component: ClientRewardsPage, title: 'Rewards', description: 'Points, achievements, and tier progress' },
      { path: '/body-map', component: BodyMapPage, title: 'Pain & Injury Chart', description: 'Track pain areas and injury recovery' },
      { path: '/my-home', component: AvatarHomePage, title: 'My Home', description: '3D avatar home - unlocks at Level 10' },
      { path: '/coach-assistant', component: CoachCommandCenterPage, title: 'Coach Assistant', description: 'Swan Coach self-training command center' },
      { path: '/virtual-olympics', component: VirtualOlympicsPage, title: 'Virtual Olympics', description: 'Ghost Racing competitive events' },
    ],
    defaultPath: '/overview',
  },
};
