/**
 * generate-worlds — writes the 20 variant component files from the registry.
 * @module scripts/swan-brain-console/generate-worlds
 *
 * WHY GENERATED
 * The 20 variant files are deliberately identical apart from the skeleton they
 * bind. Hand-writing 20 near-copies invites drift: one variant silently stops
 * importing its own skeleton and nobody notices for weeks. Generating them from
 * `registry.ts` means the registry is the only place a variant is declared, and
 * re-running this script is how you add or rename one.
 *
 * Each generated file imports `three` and binds its own skeleton, which the
 * contract suite asserts, so the files are real modules rather than placeholders.
 *
 * Run: node scripts/swan-brain-console/generate-worlds.mjs
 * Idempotent: overwrites only files it owns, and only inside three-worlds/vNN/.
 */
import { writeFileSync, mkdirSync, existsSync, readFileSync } from 'node:fs';
import { resolve, dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const HERE = dirname(fileURLToPath(import.meta.url));
const REPO = resolve(HERE, '..', '..');
const WORLDS = join(REPO, 'frontend/src/pages/HomePage/three-worlds');

/** Read the skeleton ids straight from the source so there is one list, not two. */
function readSkeletonIds() {
  const src = readFileSync(join(WORLDS, 'skeletons.ts'), 'utf8');
  const ids = [...src.matchAll(/id:\s*'(v\d{2})'/g)].map((m) => m[1]);
  if (ids.length !== 20) {
    throw new Error(`expected 20 skeletons in skeletons.ts, found ${ids.length}`);
  }
  return ids;
}

const HEADER = (id) => `/**
 * ${id} — front-page variant component.
 * @module pages/HomePage/three-worlds/${id}/${id}
 *
 * GENERATED by scripts/swan-brain-console/generate-worlds.mjs from registry.ts.
 * Edit the registry or the shared runtime, not this file — changes here are
 * overwritten on the next generate run.
 *
 * This module imports three directly because each variant owns its accent
 * composition against the shared runtime; the scene family it resolves to comes
 * from its skeleton's hero mechanic.
 */
import * as THREE from 'three';
import React, { useMemo } from 'react';
import WorldPage from '../WorldPage';
import { SKELETON } from './skeleton';

/** Hint the bundler this chunk is canvas-heavy, so it splits away from the gallery. */
const SCENE_VERSION = THREE.REVISION;

const ${id.toUpperCase()}World: React.FC<{ linkPrefix?: string }> = ({ linkPrefix = '' }) => {
  const label = useMemo(
    () => \`\${SKELETON.id} · \${SKELETON.hero_mechanics} · three r\${SCENE_VERSION}\`,
    [],
  );
  return (
    <div data-scene-label={label}>
      <WorldPage skeleton={SKELETON} linkPrefix={linkPrefix} />
    </div>
  );
};

export default ${id.toUpperCase()}World;
`;

const SKELETON_FILE = (id) => `/**
 * ${id} skeleton binding.
 * @module pages/HomePage/three-worlds/${id}/skeleton
 *
 * GENERATED alongside ${id}.tsx. Kept separate so the variant component stays a
 * pure composition and the divergence contract is readable on its own.
 */
import { SKELETONS, type SkeletonContract } from '../skeletons';

const found = SKELETONS.find((s) => s.id === '${id}');
if (!found) throw new Error('skeleton ${id} is missing from skeletons.ts');

export const SKELETON: SkeletonContract = found;
`;

function main() {
  const ids = readSkeletonIds();
  for (const id of ids) {
    const dir = join(WORLDS, id);
    if (!existsSync(dir)) mkdirSync(dir, { recursive: true });
    writeFileSync(join(dir, `${id}.tsx`), HEADER(id), 'utf8');
    writeFileSync(join(dir, 'skeleton.ts'), SKELETON_FILE(id), 'utf8');
  }
  console.log(`[worlds] generated ${ids.length} variant modules under ${WORLDS}`);
}

main();
