import { beforeEach, describe, expect, it, vi } from 'vitest';

const findAllMock = vi.fn();
const findByPkMock = vi.fn();

vi.mock('../../models/index.mjs', () => ({
  getModel: (name) => {
    if (name === 'Exercise') return { findAll: findAllMock };
    if (name === 'User') return { findByPk: findByPkMock };
    throw new Error(`unexpected model ${name}`);
  },
}));

const {
  buildWorkoutPlanExerciseGuideLines,
  collectPlanExerciseNames,
  resolveWorkoutPlanPdfBrand,
  resolveWorkoutPlanPdfBrandForClient,
} = await import('../../services/workoutPlanExerciseGuideService.mjs');

const planData = {
  weeks: [
    {
      weekNumber: 1,
      days: [
        {
          dayNumber: 1,
          exercises: [
            { exerciseName: 'Leg Press' },
            { exerciseName: 'Seated Cable Row' },
            { exerciseName: 'leg press' }, // dup, different case
          ],
        },
      ],
      sessions: undefined,
    },
    { weekNumber: 2, sessions: [{ dayNumber: 1, exercises: [{ name: 'Pallof Press' }] }] },
  ],
};

beforeEach(() => {
  findAllMock.mockReset();
  findByPkMock.mockReset();
});

describe('workoutPlanExerciseGuideService', () => {
  it('collects unique exercise names across days and sessions', () => {
    expect(collectPlanExerciseNames(planData)).toEqual(['Leg Press', 'Seated Cable Row', 'Pallof Press']);
  });

  it('builds guide lines with DB how-to when available and YouTube search otherwise', async () => {
    findAllMock.mockResolvedValue([
      {
        name: 'Leg Press',
        description: 'Machine-based lower-body press.',
        instructions: 'Sit tall.\nPress through mid-foot.\nControl the return.',
        coachingCues: ['Neutral spine', 'Exhale on press'],
        videoUrl: 'https://cdn.sswanstudios.com/videos/leg-press.mp4',
      },
    ]);

    const lines = await buildWorkoutPlanExerciseGuideLines(planData);
    const text = lines.map((line) => line.text).join('\n');

    expect(lines[0]).toEqual({ text: 'Exercise Guide - How to Perform Each Movement', kind: 'section' });
    expect(text).toContain('Machine-based lower-body press.');
    expect(text).toContain('1. Sit tall.');
    expect(text).toContain('Coach cues: Neutral spine - Exhale on press');
    expect(text).toContain('SwanStudios exercise library: https://cdn.sswanstudios.com/videos/leg-press.mp4');
    // No DB record → falls back to the YouTube search phrase
    expect(text).toContain('YouTube search: "Pallof Press exercise proper form tutorial"');
    expect(text).toContain('YouTube search: "Seated Cable Row exercise proper form tutorial"');
  });

  it('returns [] for a plan without exercises and survives a DB failure', async () => {
    expect(await buildWorkoutPlanExerciseGuideLines({ weeks: [] })).toEqual([]);
    findAllMock.mockRejectedValue(new Error('db down'));
    const lines = await buildWorkoutPlanExerciseGuideLines(planData);
    expect(lines.map((l) => l.text).join('\n')).toContain('YouTube search: "Leg Press exercise proper form tutorial"');
  });

  it('white-labels Move Fitness clients and fails safe to SwanStudios', async () => {
    expect(resolveWorkoutPlanPdfBrand('move_fitness').wordmark).toBe('Sean Swan at Move Fitness');
    expect(resolveWorkoutPlanPdfBrand('move_fitness').footerCredit).toBe('Generated by Sean Swan at Move Fitness');
    expect(resolveWorkoutPlanPdfBrand('Move Fitness').filenamePrefix).toBe('MoveFitness');
    expect(resolveWorkoutPlanPdfBrand(undefined).wordmark).toBe('SwanStudios');

    findByPkMock.mockResolvedValue({ id: 84, clientSource: 'move_fitness' });
    expect((await resolveWorkoutPlanPdfBrandForClient(84)).wordmark).toBe('Sean Swan at Move Fitness');
    findByPkMock.mockRejectedValue(new Error('db down'));
    expect((await resolveWorkoutPlanPdfBrandForClient(84)).wordmark).toBe('SwanStudios');
  });
});
