import type { UserDashboardBackgroundRecipe } from './UserDashboardBackgrounds';

const token = {
  base: 'var(--bg-base, #030712)',
  elevated: 'var(--bg-elevated, #141419)',
  surface: 'var(--surface-primary, #003080)',
  primary: 'var(--accent-primary, #60C0F0)',
  secondary: 'var(--accent-secondary, #8B5CF6)',
  gold: 'var(--accent-gold, #C6A84B)',
  data: 'var(--accent-data, #50A0F0)',
  brand: 'var(--brand-primary, #002060)',
};

const shadowBase =
  `linear-gradient(180deg, ${token.base} 0%, color-mix(in srgb, ${token.brand} 28%, ${token.base}) 48%, ${token.base} 100%)`;

const bg = (
  id: string,
  name: string,
  mood: string,
  art: string,
  preview = art,
  markOpacity = '0.08',
  markPosition = 'center 42%',
  markSize = 'min(68vw, 900px)',
  markBlur = '0px',
): UserDashboardBackgroundRecipe => ({
  id,
  name,
  mood,
  base: shadowBase,
  art,
  preview,
  markOpacity,
  markPosition,
  markSize,
  markBlur,
});

export const USER_DASHBOARD_BACKGROUNDS = [
  bg('ghost-swan', 'Ghost Swan', 'soft logo shadow',
    `radial-gradient(ellipse at 50% 28%, color-mix(in srgb, ${token.primary} 16%, transparent), transparent 48%),
     radial-gradient(circle at 50% 45%, color-mix(in srgb, ${token.secondary} 12%, transparent), transparent 34%),
     ${shadowBase}`),
  bg('crystalline-topography', 'Crystalline Topography', 'quiet cut-glass map',
    `linear-gradient(120deg, transparent 0 28%, color-mix(in srgb, ${token.primary} 8%, transparent) 29% 30%, transparent 31% 58%, color-mix(in srgb, ${token.secondary} 7%, transparent) 59% 60%, transparent 61%),
     radial-gradient(circle at 18% 72%, color-mix(in srgb, ${token.data} 12%, transparent), transparent 42%),
     ${shadowBase}`, undefined, '0.045', '78% 68%', 'min(54vw, 720px)', '1px'),
  bg('deep-ocean-vault', 'Deep Ocean Vault', 'submerged sapphire depth',
    `radial-gradient(ellipse at 50% 0%, color-mix(in srgb, ${token.primary} 18%, transparent), transparent 56%),
     linear-gradient(180deg, color-mix(in srgb, ${token.surface} 32%, ${token.base}), ${token.base} 78%),
     radial-gradient(circle at 82% 82%, color-mix(in srgb, ${token.secondary} 9%, transparent), transparent 38%)`),
  bg('aurora-canopy', 'Aurora Canopy', 'green-blue forest glow',
    `radial-gradient(ellipse at 20% 5%, color-mix(in srgb, ${token.gold} 13%, transparent), transparent 46%),
     radial-gradient(ellipse at 72% 16%, color-mix(in srgb, ${token.primary} 18%, transparent), transparent 54%),
     linear-gradient(145deg, color-mix(in srgb, ${token.brand} 28%, ${token.base}), ${token.base})`, undefined, '0.07'),
  bg('obsidian-carbon', 'Obsidian Carbon', 'near-black texture',
    `repeating-linear-gradient(135deg, color-mix(in srgb, ${token.elevated} 42%, transparent) 0 1px, transparent 1px 22px),
     radial-gradient(circle at 78% 26%, color-mix(in srgb, ${token.secondary} 11%, transparent), transparent 34%),
     ${shadowBase}`, undefined, '0.055', '50% 52%', 'min(62vw, 820px)', '2px'),
  bg('crown-nebula', 'Crown Nebula', 'gold and violet halo',
    `radial-gradient(circle at 50% 24%, color-mix(in srgb, ${token.gold} 20%, transparent), transparent 28%),
     radial-gradient(circle at 58% 34%, color-mix(in srgb, ${token.secondary} 20%, transparent), transparent 42%),
     ${shadowBase}`, undefined, '0.08'),
  bg('training-pulse-grid', 'Training Pulse Grid', 'subtle data rhythm',
    `linear-gradient(color-mix(in srgb, ${token.primary} 7%, transparent) 1px, transparent 1px),
     linear-gradient(90deg, color-mix(in srgb, ${token.primary} 6%, transparent) 1px, transparent 1px),
     radial-gradient(circle at 28% 32%, color-mix(in srgb, ${token.data} 15%, transparent), transparent 38%),
     ${shadowBase}`, undefined, '0.045', '74% 52%', 'min(48vw, 680px)', '1px'),
  bg('glass-wing-refraction', 'Glass Wing Refraction', 'large feather prisms',
    `linear-gradient(118deg, transparent 0 18%, color-mix(in srgb, ${token.primary} 13%, transparent) 19% 26%, transparent 27% 46%, color-mix(in srgb, ${token.secondary} 10%, transparent) 47% 55%, transparent 56%),
     radial-gradient(circle at 75% 35%, color-mix(in srgb, ${token.primary} 14%, transparent), transparent 42%),
     ${shadowBase}`, undefined, '0.09', '28% 56%', 'min(58vw, 780px)', '0px'),
  bg('forge-ember-shadow', 'Forge Ember Shadow', 'warm bronze edge',
    `radial-gradient(circle at 18% 86%, color-mix(in srgb, ${token.gold} 20%, transparent), transparent 34%),
     radial-gradient(circle at 86% 18%, color-mix(in srgb, ${token.secondary} 10%, transparent), transparent 32%),
     linear-gradient(180deg, ${token.base}, color-mix(in srgb, ${token.gold} 8%, ${token.base}))`, undefined, '0.05'),
  bg('void-crystal', 'Void Crystal', 'black ice facets',
    `conic-gradient(from 210deg at 50% 50%, transparent 0 15%, color-mix(in srgb, ${token.primary} 10%, transparent) 18%, transparent 28%, color-mix(in srgb, ${token.secondary} 12%, transparent) 36%, transparent 52%),
     radial-gradient(circle at 50% 50%, color-mix(in srgb, ${token.primary} 10%, transparent), transparent 54%),
     ${shadowBase}`, undefined, '0.065', 'center', 'min(62vw, 860px)', '1px'),
  bg('sapphire-prism-storm', 'Sapphire Prism Storm', 'electric shard field',
    `linear-gradient(62deg, transparent 0 20%, color-mix(in srgb, ${token.primary} 18%, transparent) 21% 22%, transparent 23% 52%, color-mix(in srgb, ${token.data} 14%, transparent) 53% 55%, transparent 56%),
     radial-gradient(circle at 72% 24%, color-mix(in srgb, ${token.secondary} 16%, transparent), transparent 38%),
     ${shadowBase}`, undefined, '0.055'),
  bg('lunar-ice-chapel', 'Lunar Ice Chapel', 'arched quiet light',
    `radial-gradient(ellipse at 50% 0%, color-mix(in srgb, ${token.primary} 20%, transparent), transparent 40%),
     linear-gradient(90deg, transparent 0 15%, color-mix(in srgb, ${token.primary} 8%, transparent) 16% 17%, transparent 18% 82%, color-mix(in srgb, ${token.primary} 8%, transparent) 83% 84%, transparent 85%),
     ${shadowBase}`, undefined, '0.075', '50% 30%', 'min(48vw, 660px)', '0px'),
  bg('emerald-circuit-grove', 'Emerald Circuit Grove', 'organic signal lines',
    `linear-gradient(90deg, color-mix(in srgb, ${token.gold} 5%, transparent) 1px, transparent 1px),
     radial-gradient(circle at 22% 22%, color-mix(in srgb, ${token.gold} 12%, transparent), transparent 34%),
     radial-gradient(circle at 76% 70%, color-mix(in srgb, ${token.primary} 14%, transparent), transparent 44%),
     ${shadowBase}`, undefined, '0.05', '70% 58%', 'min(56vw, 740px)', '1px'),
  bg('royal-depth-marble', 'Royal Depth Marble', 'dark liquid veining',
    `radial-gradient(ellipse at 18% 12%, color-mix(in srgb, ${token.secondary} 12%, transparent), transparent 38%),
     radial-gradient(ellipse at 80% 74%, color-mix(in srgb, ${token.primary} 16%, transparent), transparent 46%),
     linear-gradient(127deg, transparent 0 44%, color-mix(in srgb, ${token.gold} 9%, transparent) 45% 46%, transparent 47%),
     ${shadowBase}`, undefined, '0.06'),
  bg('swan-eclipse', 'Swan Eclipse', 'centered shadow ring',
    `radial-gradient(circle at 50% 42%, transparent 0 18%, color-mix(in srgb, ${token.primary} 13%, transparent) 19% 21%, transparent 22% 42%),
     radial-gradient(circle at 50% 42%, color-mix(in srgb, ${token.secondary} 15%, transparent), transparent 52%),
     ${shadowBase}`, undefined, '0.1', 'center 43%', 'min(60vw, 800px)', '0px'),
  bg('neon-rain-window', 'Neon Rain Window', 'vertical light streaks',
    `repeating-linear-gradient(90deg, transparent 0 26px, color-mix(in srgb, ${token.primary} 8%, transparent) 27px 28px, transparent 29px 58px),
     radial-gradient(circle at 78% 18%, color-mix(in srgb, ${token.secondary} 16%, transparent), transparent 38%),
     ${shadowBase}`, undefined, '0.04', '22% 52%', 'min(44vw, 620px)', '2px'),
  bg('gold-feather-dust', 'Gold Feather Dust', 'small luxury sparks',
    `radial-gradient(circle at 18% 20%, color-mix(in srgb, ${token.gold} 18%, transparent) 0 1px, transparent 2px),
     radial-gradient(circle at 74% 32%, color-mix(in srgb, ${token.primary} 14%, transparent) 0 1px, transparent 2px),
     radial-gradient(circle at 44% 78%, color-mix(in srgb, ${token.gold} 12%, transparent), transparent 36%),
     ${shadowBase}`, undefined, '0.055'),
  bg('arctic-data-aurora', 'Arctic Data Aurora', 'analytics glow curtain',
    `linear-gradient(180deg, color-mix(in srgb, ${token.primary} 15%, transparent), transparent 42%),
     repeating-linear-gradient(90deg, color-mix(in srgb, ${token.data} 7%, transparent) 0 2px, transparent 2px 44px),
     radial-gradient(ellipse at 60% 18%, color-mix(in srgb, ${token.secondary} 14%, transparent), transparent 44%),
     ${shadowBase}`, undefined, '0.05'),
  bg('crimson-velvet-vault', 'Crimson Velvet Vault', 'deep rare-theme shadow',
    `radial-gradient(circle at 25% 28%, color-mix(in srgb, var(--accent-error, #EF4444) 12%, transparent), transparent 36%),
     radial-gradient(circle at 82% 70%, color-mix(in srgb, ${token.gold} 13%, transparent), transparent 38%),
     ${shadowBase}`, undefined, '0.045', '75% 48%', 'min(54vw, 700px)', '2px'),
  bg('haloed-deep-space', 'Haloed Deep Space', 'wide orbit glow',
    `radial-gradient(circle at 50% 48%, transparent 0 28%, color-mix(in srgb, ${token.primary} 12%, transparent) 29% 30%, transparent 31% 62%),
     radial-gradient(circle at 50% 48%, color-mix(in srgb, ${token.secondary} 14%, transparent), transparent 54%),
     ${shadowBase}`, undefined, '0.08', 'center', 'min(70vw, 940px)', '1px'),
  bg('forest-swan', 'Forest Swan', 'moonlit emerald wings',
    `radial-gradient(ellipse at 18% 8%, color-mix(in srgb, ${token.gold} 13%, transparent), transparent 38%),
     radial-gradient(ellipse at 72% 12%, color-mix(in srgb, ${token.primary} 16%, transparent), transparent 48%),
     repeating-linear-gradient(118deg, transparent 0 34px, color-mix(in srgb, ${token.gold} 6%, transparent) 35px 36px, transparent 37px 84px),
     ${shadowBase}`, undefined, '0.09', '18% 54%', 'min(58vw, 780px)', '1px'),
  bg('deep-space-swan', 'Deep Space Swan', 'swan orbit in black sapphire',
    `radial-gradient(circle at 52% 42%, transparent 0 18%, color-mix(in srgb, ${token.primary} 15%, transparent) 19% 20%, transparent 21% 54%),
     radial-gradient(circle at 72% 18%, color-mix(in srgb, ${token.secondary} 18%, transparent), transparent 34%),
     radial-gradient(circle at 24% 72%, color-mix(in srgb, ${token.data} 12%, transparent), transparent 38%),
     ${shadowBase}`, undefined, '0.085', 'center 45%', 'min(72vw, 980px)', '1px'),
  bg('matrix-swan', 'Matrix Swan', 'encrypted feather rain',
    `repeating-linear-gradient(90deg, color-mix(in srgb, ${token.primary} 7%, transparent) 0 1px, transparent 1px 26px),
     repeating-linear-gradient(180deg, transparent 0 18px, color-mix(in srgb, ${token.gold} 5%, transparent) 19px 20px, transparent 21px 52px),
     radial-gradient(circle at 48% 38%, color-mix(in srgb, ${token.primary} 15%, transparent), transparent 44%),
     ${shadowBase}`, undefined, '0.065', '72% 50%', 'min(50vw, 680px)', '1px'),
  bg('data-aurora-swan', 'Data Aurora Swan', 'analytics aurora wings',
    `linear-gradient(180deg, color-mix(in srgb, ${token.data} 16%, transparent), transparent 38%),
     linear-gradient(112deg, transparent 0 18%, color-mix(in srgb, ${token.primary} 12%, transparent) 19% 27%, transparent 28% 50%, color-mix(in srgb, ${token.secondary} 10%, transparent) 51% 58%, transparent 59%),
     repeating-linear-gradient(90deg, transparent 0 42px, color-mix(in srgb, ${token.data} 7%, transparent) 43px 45px, transparent 46px 86px),
     ${shadowBase}`, undefined, '0.07', '28% 44%', 'min(62vw, 820px)', '0px'),
  bg('cyberpunk-swan', 'Cyberpunk Swan', 'neon skyline reflection',
    `repeating-linear-gradient(90deg, transparent 0 30px, color-mix(in srgb, ${token.primary} 10%, transparent) 31px 33px, transparent 34px 70px),
     linear-gradient(180deg, transparent 0 48%, color-mix(in srgb, ${token.secondary} 13%, transparent) 49% 50%, transparent 51%),
     radial-gradient(circle at 80% 22%, color-mix(in srgb, ${token.secondary} 22%, transparent), transparent 34%),
     ${shadowBase}`, undefined, '0.06', '78% 62%', 'min(54vw, 720px)', '2px'),
  bg('ocean-swan', 'Ocean Swan', 'tidal sapphire feathers',
    `radial-gradient(ellipse at 50% -5%, color-mix(in srgb, ${token.primary} 20%, transparent), transparent 48%),
     repeating-radial-gradient(ellipse at 50% 0%, color-mix(in srgb, ${token.data} 7%, transparent) 0 1px, transparent 2px 48px),
     radial-gradient(circle at 22% 78%, color-mix(in srgb, ${token.secondary} 10%, transparent), transparent 38%),
     ${shadowBase}`, undefined, '0.08', '50% 36%', 'min(64vw, 860px)', '1px'),
  bg('ice-cathedral-swan', 'Ice Cathedral Swan', 'crystalline chapel silhouette',
    `radial-gradient(ellipse at 50% 0%, color-mix(in srgb, ${token.primary} 22%, transparent), transparent 38%),
     linear-gradient(90deg, transparent 0 12%, color-mix(in srgb, ${token.primary} 9%, transparent) 13% 14%, transparent 15% 32%, color-mix(in srgb, ${token.secondary} 7%, transparent) 33% 34%, transparent 35% 66%, color-mix(in srgb, ${token.secondary} 7%, transparent) 67% 68%, transparent 69% 86%, color-mix(in srgb, ${token.primary} 9%, transparent) 87% 88%, transparent 89%),
     ${shadowBase}`, undefined, '0.1', '50% 26%', 'min(50vw, 700px)', '0px'),
  bg('golden-forge-swan', 'Golden Forge Swan', 'bronze sparks and shadow',
    `radial-gradient(circle at 18% 82%, color-mix(in srgb, ${token.gold} 22%, transparent), transparent 34%),
     radial-gradient(circle at 78% 18%, color-mix(in srgb, ${token.primary} 13%, transparent), transparent 36%),
     linear-gradient(138deg, transparent 0 58%, color-mix(in srgb, ${token.gold} 10%, transparent) 59% 60%, transparent 61%),
     ${shadowBase}`, undefined, '0.065', '68% 54%', 'min(58vw, 760px)', '1px'),
  bg('violet-eclipse-swan', 'Violet Eclipse Swan', 'purple eclipse logo veil',
    `radial-gradient(circle at 50% 42%, transparent 0 20%, color-mix(in srgb, ${token.secondary} 20%, transparent) 21% 23%, transparent 24% 54%),
     radial-gradient(circle at 50% 42%, color-mix(in srgb, ${token.primary} 13%, transparent), transparent 46%),
     radial-gradient(circle at 22% 24%, color-mix(in srgb, ${token.gold} 10%, transparent), transparent 32%),
     ${shadowBase}`, undefined, '0.095', 'center 42%', 'min(66vw, 900px)', '0px'),
  bg('holographic-prism-swan', 'Holographic Prism Swan', 'glass spectrum feathers',
    `conic-gradient(from 218deg at 50% 46%, transparent 0 10%, color-mix(in srgb, ${token.primary} 13%, transparent) 13%, transparent 24%, color-mix(in srgb, ${token.secondary} 13%, transparent) 30%, transparent 42%, color-mix(in srgb, ${token.gold} 10%, transparent) 48%, transparent 60%),
     linear-gradient(118deg, transparent 0 24%, color-mix(in srgb, ${token.data} 12%, transparent) 25% 27%, transparent 28% 62%, color-mix(in srgb, ${token.primary} 10%, transparent) 63% 65%, transparent 66%),
     ${shadowBase}`, undefined, '0.09', '30% 48%', 'min(60vw, 820px)', '0px'),
] as const;

export { token as USER_DASHBOARD_BACKGROUND_TOKENS };
