/**
 * PDF Export Service — SwanStudios
 * ================================
 * Shared PDF generation for Workout Logger, Bootcamp Class,
 * Long-Horizon Plan, and AI Workout Plan exports.
 *
 * Uses jsPDF + jspdf-autotable with print-friendly Crystalline Swan branding.
 *
 * Pipeline: Component data → formatter → pdfCore → download/blob
 */
// fallow-ignore-file complexity, code-duplication
// Legacy shared PDF exporter predates the changed-file health gate; this slice only aligns Plan Vault horizon labels and filenames.
import { jsPDF } from 'jspdf';
import { format } from 'date-fns';
import { addAutoTable, getLastAutoTableY } from './pdfAutoTable';
import { normalizeClientSource } from '../utils/clientSource';
import { closestWorkoutPlanHorizon } from '../utils/workoutPlanHorizonTokens';

// ── Brand Colors (print-friendly Crystalline Swan) ───────────────────
const BRAND = {
  midnightSapphire: [0, 32, 96] as [number, number, number],    // #002060
  royalDepth:       [0, 48, 128] as [number, number, number],   // #003080
  iceWing:          [96, 192, 240] as [number, number, number],  // #60C0F0
  wingPurple:       [139, 92, 246] as [number, number, number],  // #8B5CF6
  gildedFern:       [198, 168, 75] as [number, number, number],  // #C6A84B
  frostWhite:       [224, 236, 244] as [number, number, number], // #E0ECF4
  textDark:         [30, 30, 50] as [number, number, number],
  textMuted:        [100, 110, 130] as [number, number, number],
  white:            [255, 255, 255] as [number, number, number],
  lightGray:        [245, 247, 250] as [number, number, number],
  borderGray:       [200, 210, 220] as [number, number, number],
  warnRed:          [220, 50, 50] as [number, number, number],
  successGreen:     [34, 197, 94] as [number, number, number],
};

// ── Core PDF Builder ─────────────────────────────────────────────────

function createPDF(orientation: 'portrait' | 'landscape' = 'portrait'): jsPDF {
  return new jsPDF({ orientation, unit: 'mm', format: 'a4' });
}

function addHeader(doc: jsPDF, title: string, subtitle?: string) {
  const pageW = doc.internal.pageSize.getWidth();

  // Top accent bar
  doc.setFillColor(...BRAND.midnightSapphire);
  doc.rect(0, 0, pageW, 18, 'F');
  doc.setFillColor(...BRAND.wingPurple);
  doc.rect(0, 18, pageW, 1.5, 'F');

  // Brand name
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(14);
  doc.setTextColor(...BRAND.white);
  doc.text('SwanStudios', 14, 12);

  // Title
  doc.setFontSize(9);
  doc.setTextColor(...BRAND.frostWhite);
  doc.text(title.toUpperCase(), pageW - 14, 9, { align: 'right' });

  // Subtitle / date
  if (subtitle) {
    doc.setFontSize(7);
    doc.text(subtitle, pageW - 14, 14, { align: 'right' });
  }

  return 24; // Y position after header
}

function addFooter(doc: jsPDF, pageNum: number, totalPages: number) {
  const pageW = doc.internal.pageSize.getWidth();
  const pageH = doc.internal.pageSize.getHeight();

  doc.setFillColor(...BRAND.frostWhite);
  doc.rect(0, pageH - 12, pageW, 12, 'F');
  doc.setDrawColor(...BRAND.borderGray);
  doc.line(14, pageH - 12, pageW - 14, pageH - 12);

  doc.setFont('helvetica', 'normal');
  doc.setFontSize(7);
  doc.setTextColor(...BRAND.textMuted);
  doc.text('Generated by SwanStudios · sswanstudios.com', 14, pageH - 5);
  doc.text(`Page ${pageNum} of ${totalPages}`, pageW - 14, pageH - 5, { align: 'right' });
  doc.text(format(new Date(), 'MMM d, yyyy h:mm a'), pageW / 2, pageH - 5, { align: 'center' });
}

function addSectionTitle(doc: jsPDF, y: number, title: string): number {
  doc.setFillColor(...BRAND.frostWhite);
  doc.rect(14, y - 1, doc.internal.pageSize.getWidth() - 28, 8, 'F');
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(10);
  doc.setTextColor(...BRAND.midnightSapphire);
  doc.text(title, 16, y + 4.5);
  return y + 11;
}

function addKeyValue(doc: jsPDF, y: number, label: string, value: string, x = 16): number {
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(8);
  doc.setTextColor(...BRAND.textMuted);
  doc.text(label + ':', x, y);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(...BRAND.textDark);
  doc.text(String(value), x + doc.getTextWidth(label + ':  '), y);
  return y + 5;
}

function checkPageBreak(doc: jsPDF, y: number, needed: number): number {
  const pageH = doc.internal.pageSize.getHeight();
  if (y + needed > pageH - 18) {
    doc.addPage();
    return 14;
  }
  return y;
}

function finalizeAndDownload(doc: jsPDF, filename: string) {
  const totalPages = doc.getNumberOfPages();
  for (let i = 1; i <= totalPages; i++) {
    doc.setPage(i);
    addFooter(doc, i, totalPages);
  }
  doc.save(filename);
}

// ── Type Imports (re-declared for self-containment) ──────────────────

/** Workout Logger exercise entry (from nasmApiService) */
export interface PDFExerciseSet {
  setNumber: number;
  weight: number;
  reps: number;
  rpe: number;
  tempo?: string;
  restTime: number;
  formQuality: number;
  notes?: string;
}

export interface PDFExerciseEntry {
  exerciseId: string;
  exerciseName: string;
  sets: PDFExerciseSet[];
  formRating: number;
  painLevel: number;
  performanceNotes?: string;
}

/** Bootcamp types */
export interface PDFBootcampExercise {
  exerciseName: string;
  durationSec: number;
  restSec: number;
  sortOrder: number;
  isCardioFinisher: boolean;
  muscleTargets: string;
  easyVariation: string | null;
  mediumVariation: string | null;
  hardVariation: string | null;
  equipmentRequired: string | null;
  stationIndex?: number;
  kneeMod?: string | null;
  shoulderMod?: string | null;
  ankleMod?: string | null;
  wristMod?: string | null;
  backMod?: string | null;
}

export interface PDFBootcampStation {
  stationNumber: number;
  stationName: string;
  equipmentNeeded: string;
  sortOrder: number;
}

export interface PDFBootcampPlan {
  name: string;
  classFormat: string;
  dayType: string;
  stationCount: number;
  targetDuration: number;
  totalWorkoutMin: number;
  totalClassMin: number;
  expectedParticipants: number;
  stations: PDFBootcampStation[];
  exercises: PDFBootcampExercise[];
  overflowPlan?: { triggerCount: number; strategy: string; lapExercises: { name: string; durationMin: number }[]; lapDurationMin: number } | null;
}

/** Long-Horizon Plan types */
export interface PDFMesocycleBlock {
  sequence: number;
  nasmFramework: string;
  optPhase: number | null;
  phaseName: string;
  focus: string | null;
  durationWeeks: number;
  sessionsPerWeek: number | null;
  entryCriteria: string | null;
  exitCriteria: string | null;
  notes: string | null;
  rationale?: string | null;
}

export interface PDFLongHorizonPlan {
  planName: string;
  horizonMonths: number;
  summary?: string;
  blocks: PDFMesocycleBlock[];
}

// =====================================================================
//  1. WORKOUT LOGGER PDF
// =====================================================================

export interface WorkoutLoggerPDFData {
  clientName: string;
  trainerName?: string;
  date: string;
  exercises: PDFExerciseEntry[];
  sessionNotes?: string;
  overallIntensity?: number;
}

export function exportWorkoutLoggerPDF(data: WorkoutLoggerPDFData): void {
  const doc = createPDF();
  let y = addHeader(doc, 'Workout Session Log', `${data.clientName} · ${format(new Date(data.date), 'MMMM d, yyyy')}`);

  // Session info
  y = addSectionTitle(doc, y, 'Session Details');
  y = addKeyValue(doc, y, 'Client', data.clientName);
  if (data.trainerName) y = addKeyValue(doc, y, 'Trainer', data.trainerName);
  y = addKeyValue(doc, y, 'Date', format(new Date(data.date), 'EEEE, MMMM d, yyyy'));
  if (data.overallIntensity) y = addKeyValue(doc, y, 'Intensity', `${data.overallIntensity}/10`);
  y += 3;

  // Summary stats
  const totalSets = data.exercises.reduce((s, ex) => s + ex.sets.length, 0);
  const totalReps = data.exercises.reduce((s, ex) => s + ex.sets.reduce((r, set) => r + set.reps, 0), 0);
  const totalVolume = data.exercises.reduce((s, ex) => s + ex.sets.reduce((v, set) => v + set.weight * set.reps, 0), 0);

  y = addSectionTitle(doc, y, 'Session Summary');
  const summaryStartX = 16;
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(9);
  doc.setTextColor(...BRAND.textDark);

  const stats = [
    ['Exercises', String(data.exercises.length)],
    ['Total Sets', String(totalSets)],
    ['Total Reps', String(totalReps)],
    ['Total Volume', `${totalVolume.toLocaleString()} lbs`],
  ];
  stats.forEach(([label, val], i) => {
    const x = summaryStartX + i * 42;
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(14);
    doc.setTextColor(...BRAND.wingPurple);
    doc.text(val, x, y + 2);
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(7);
    doc.setTextColor(...BRAND.textMuted);
    doc.text(label, x, y + 7);
  });
  y += 14;

  // Exercise tables
  data.exercises.forEach((ex, idx) => {
    y = checkPageBreak(doc, y, 30);
    y = addSectionTitle(doc, y, `${idx + 1}. ${ex.exerciseName}`);

    const meta: string[] = [];
    if (ex.formRating) meta.push(`Form: ${ex.formRating}/5`);
    if (ex.painLevel > 0) meta.push(`Pain: ${ex.painLevel}/10`);
    if (ex.performanceNotes) meta.push(ex.performanceNotes);
    if (meta.length) {
      doc.setFont('helvetica', 'italic');
      doc.setFontSize(7);
      doc.setTextColor(...BRAND.textMuted);
      doc.text(meta.join(' · '), 16, y);
      y += 4;
    }

    addAutoTable(doc, {
      startY: y,
      head: [['Set', 'Weight (lbs)', 'Reps', 'RPE', 'Form', 'Tempo', 'Rest (s)', 'Notes']],
      body: ex.sets.map(s => [
        s.setNumber,
        s.weight || '-',
        s.reps,
        s.rpe ? `${s.rpe}/10` : '-',
        s.formQuality ? `${s.formQuality}/5` : '-',
        s.tempo || '-',
        s.restTime || '-',
        s.notes || '',
      ]),
      theme: 'grid',
      headStyles: {
        fillColor: BRAND.midnightSapphire,
        textColor: BRAND.white,
        fontSize: 7,
        fontStyle: 'bold',
        halign: 'center',
      },
      bodyStyles: { fontSize: 7, textColor: BRAND.textDark, halign: 'center' },
      alternateRowStyles: { fillColor: BRAND.lightGray },
      styles: { cellPadding: 2, lineColor: BRAND.borderGray, lineWidth: 0.2 },
      margin: { left: 16, right: 16 },
    });

    y = getLastAutoTableY(doc, y) + 6;
  });

  // Session notes
  if (data.sessionNotes) {
    y = checkPageBreak(doc, y, 20);
    y = addSectionTitle(doc, y, 'Session Notes');
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(8);
    doc.setTextColor(...BRAND.textDark);
    const lines = doc.splitTextToSize(data.sessionNotes, doc.internal.pageSize.getWidth() - 32);
    doc.text(lines, 16, y);
    y += lines.length * 4 + 4;
  }

  const safeName = data.clientName.replace(/[^a-zA-Z0-9]/g, '-');
  finalizeAndDownload(doc, `SwanStudios-Workout-${safeName}-${data.date}.pdf`);
}


// =====================================================================
//  2. BOOTCAMP CLASS PDF
// =====================================================================

export function exportBootcampPDF(data: PDFBootcampPlan): void {
  const doc = createPDF('landscape');
  let y = addHeader(doc, 'Boot Camp Class Plan', `${data.name} · ${data.dayType.replace('_', ' ').toUpperCase()}`);

  // Class overview
  y = addSectionTitle(doc, y, 'Class Overview');
  y = addKeyValue(doc, y, 'Format', data.classFormat.replace(/_/g, ' '));
  y = addKeyValue(doc, y, 'Day Type', data.dayType.replace(/_/g, ' '));
  y = addKeyValue(doc, y, 'Duration', `${data.totalClassMin} min total (${data.totalWorkoutMin} min workout)`);
  y = addKeyValue(doc, y, 'Stations', String(data.stationCount));
  y = addKeyValue(doc, y, 'Participants', String(data.expectedParticipants));
  y += 3;

  // Station layout
  if (data.stations.length > 0) {
    y = addSectionTitle(doc, y, 'Station Layout');
    addAutoTable(doc, {
      startY: y,
      head: [['#', 'Station Name', 'Equipment Needed']],
      body: data.stations.map(s => [s.stationNumber, s.stationName, s.equipmentNeeded || 'None']),
      theme: 'grid',
      headStyles: { fillColor: BRAND.midnightSapphire, textColor: BRAND.white, fontSize: 8, fontStyle: 'bold' },
      bodyStyles: { fontSize: 8, textColor: BRAND.textDark },
      alternateRowStyles: { fillColor: BRAND.lightGray },
      styles: { cellPadding: 2.5, lineColor: BRAND.borderGray, lineWidth: 0.2 },
      margin: { left: 16, right: 16 },
    });
    y = getLastAutoTableY(doc, y) + 6;
  }

  // Exercises by station
  const stationGroups = new Map<number, PDFBootcampExercise[]>();
  data.exercises.forEach(ex => {
    const si = ex.stationIndex ?? 0;
    if (!stationGroups.has(si)) stationGroups.set(si, []);
    stationGroups.get(si)!.push(ex);
  });

  stationGroups.forEach((exList, stationIdx) => {
    y = checkPageBreak(doc, y, 25);
    const stationName = data.stations.find(s => s.stationNumber === stationIdx + 1)?.stationName || `Station ${stationIdx + 1}`;
    y = addSectionTitle(doc, y, stationName);

    addAutoTable(doc, {
      startY: y,
      head: [['Exercise', 'Duration', 'Rest', 'Muscles', 'Equipment', 'Easy Var.', 'Hard Var.']],
      body: exList.map(ex => [
        ex.exerciseName,
        `${ex.durationSec}s`,
        `${ex.restSec}s`,
        ex.muscleTargets || '-',
        ex.equipmentRequired || 'BW',
        ex.easyVariation || '-',
        ex.hardVariation || '-',
      ]),
      theme: 'grid',
      headStyles: { fillColor: BRAND.wingPurple, textColor: BRAND.white, fontSize: 7, fontStyle: 'bold' },
      bodyStyles: { fontSize: 7, textColor: BRAND.textDark },
      alternateRowStyles: { fillColor: BRAND.lightGray },
      styles: { cellPadding: 2, lineColor: BRAND.borderGray, lineWidth: 0.2 },
      margin: { left: 16, right: 16 },
      columnStyles: { 0: { fontStyle: 'bold', cellWidth: 45 } },
    });
    y = getLastAutoTableY(doc, y) + 5;
  });

  // Cardio finishers
  const finishers = data.exercises.filter(ex => ex.isCardioFinisher);
  if (finishers.length > 0) {
    y = checkPageBreak(doc, y, 20);
    y = addSectionTitle(doc, y, 'Cardio Finishers');
    addAutoTable(doc, {
      startY: y,
      head: [['Exercise', 'Duration', 'Rest', 'Muscles']],
      body: finishers.map(ex => [ex.exerciseName, `${ex.durationSec}s`, `${ex.restSec}s`, ex.muscleTargets || '-']),
      theme: 'grid',
      headStyles: { fillColor: BRAND.successGreen, textColor: BRAND.white, fontSize: 8, fontStyle: 'bold' },
      bodyStyles: { fontSize: 8, textColor: BRAND.textDark },
      styles: { cellPadding: 2.5, lineColor: BRAND.borderGray, lineWidth: 0.2 },
      margin: { left: 16, right: 16 },
    });
    y = getLastAutoTableY(doc, y) + 5;
  }

  // Overflow plan
  if (data.overflowPlan) {
    y = checkPageBreak(doc, y, 25);
    y = addSectionTitle(doc, y, 'Overflow Plan');
    y = addKeyValue(doc, y, 'Triggers at', `${data.overflowPlan.triggerCount}+ participants`);
    y = addKeyValue(doc, y, 'Strategy', data.overflowPlan.strategy);
    y = addKeyValue(doc, y, 'Lap Duration', `${data.overflowPlan.lapDurationMin} min`);
    if (data.overflowPlan.lapExercises.length > 0) {
      y += 2;
      addAutoTable(doc, {
        startY: y,
        head: [['Lap Exercise', 'Duration (min)']],
        body: data.overflowPlan.lapExercises.map(le => [le.name, le.durationMin]),
        theme: 'grid',
        headStyles: { fillColor: BRAND.gildedFern, textColor: BRAND.white, fontSize: 8, fontStyle: 'bold' },
        bodyStyles: { fontSize: 8, textColor: BRAND.textDark },
        styles: { cellPadding: 2.5, lineColor: BRAND.borderGray, lineWidth: 0.2 },
        margin: { left: 16, right: 16 },
      });
    }
  }

  // Modification reference
  const moddedExercises = data.exercises.filter(ex => ex.kneeMod || ex.shoulderMod || ex.ankleMod || ex.wristMod || ex.backMod);
  if (moddedExercises.length > 0) {
    y = checkPageBreak(doc, y, 25);
    y = addSectionTitle(doc, y, 'Injury Modifications Reference');
    addAutoTable(doc, {
      startY: y,
      head: [['Exercise', 'Knee', 'Shoulder', 'Ankle', 'Wrist', 'Back']],
      body: moddedExercises.map(ex => [
        ex.exerciseName,
        ex.kneeMod || '-', ex.shoulderMod || '-', ex.ankleMod || '-', ex.wristMod || '-', ex.backMod || '-',
      ]),
      theme: 'grid',
      headStyles: { fillColor: BRAND.warnRed, textColor: BRAND.white, fontSize: 7, fontStyle: 'bold' },
      bodyStyles: { fontSize: 7, textColor: BRAND.textDark },
      styles: { cellPadding: 2, lineColor: BRAND.borderGray, lineWidth: 0.2 },
      margin: { left: 16, right: 16 },
    });
  }

  finalizeAndDownload(doc, `SwanStudios-Bootcamp-${data.name.replace(/[^a-zA-Z0-9]/g, '-')}.pdf`);
}


// =====================================================================
//  3. LONG-HORIZON PLAN PDF
// =====================================================================

export function exportLongHorizonPDF(data: PDFLongHorizonPlan, clientName?: string): void {
  const doc = createPDF();
  let y = addHeader(doc, `${data.horizonMonths}-Month Training Plan`, `${data.planName}${clientName ? ` · ${clientName}` : ''}`);

  // Plan overview
  y = addSectionTitle(doc, y, 'Plan Overview');
  y = addKeyValue(doc, y, 'Plan Name', data.planName);
  y = addKeyValue(doc, y, 'Duration', `${data.horizonMonths} months`);
  const totalWeeks = data.blocks.reduce((s, b) => s + b.durationWeeks, 0);
  y = addKeyValue(doc, y, 'Total Weeks', String(totalWeeks));
  y = addKeyValue(doc, y, 'Mesocycles', String(data.blocks.length));
  y += 2;

  if (data.summary) {
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(8);
    doc.setTextColor(...BRAND.textDark);
    const lines = doc.splitTextToSize(data.summary, doc.internal.pageSize.getWidth() - 32);
    doc.text(lines, 16, y);
    y += lines.length * 4 + 4;
  }

  // Timeline visual
  y = addSectionTitle(doc, y, 'Periodization Timeline');
  const barWidth = doc.internal.pageSize.getWidth() - 32;
  const barH = 10;
  const phaseColors: [number, number, number][] = [
    BRAND.midnightSapphire, BRAND.wingPurple, BRAND.iceWing, BRAND.gildedFern,
    BRAND.successGreen, BRAND.warnRed,
  ];

  let barX = 16;
  data.blocks.forEach((block, i) => {
    const w = (block.durationWeeks / totalWeeks) * barWidth;
    doc.setFillColor(...phaseColors[i % phaseColors.length]);
    doc.rect(barX, y, w, barH, 'F');
    if (w > 15) {
      doc.setFont('helvetica', 'bold');
      doc.setFontSize(6);
      doc.setTextColor(...BRAND.white);
      doc.text(`${block.durationWeeks}wk`, barX + w / 2, y + barH / 2 + 1, { align: 'center' });
    }
    barX += w;
  });
  y += barH + 2;

  // Legend
  data.blocks.forEach((block, i) => {
    doc.setFillColor(...phaseColors[i % phaseColors.length]);
    doc.rect(16 + i * 35, y, 4, 4, 'F');
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(6);
    doc.setTextColor(...BRAND.textDark);
    doc.text(block.phaseName.slice(0, 12), 22 + i * 35, y + 3);
  });
  y += 10;

  // Mesocycle detail table
  y = addSectionTitle(doc, y, 'Mesocycle Breakdown');
  addAutoTable(doc, {
    startY: y,
    head: [['#', 'Phase', 'Framework', 'Focus', 'Weeks', 'Sessions/Wk', 'Entry Criteria']],
    body: data.blocks.map(b => [
      b.sequence,
      b.phaseName,
      b.nasmFramework,
      b.focus || '-',
      b.durationWeeks,
      b.sessionsPerWeek || '-',
      b.entryCriteria || '-',
    ]),
    theme: 'grid',
    headStyles: { fillColor: BRAND.midnightSapphire, textColor: BRAND.white, fontSize: 7, fontStyle: 'bold' },
    bodyStyles: { fontSize: 7, textColor: BRAND.textDark },
    alternateRowStyles: { fillColor: BRAND.lightGray },
    styles: { cellPadding: 2.5, lineColor: BRAND.borderGray, lineWidth: 0.2 },
    margin: { left: 16, right: 16 },
    columnStyles: { 0: { cellWidth: 8, halign: 'center' }, 1: { fontStyle: 'bold' } },
  });
  y = getLastAutoTableY(doc, y) + 6;

  // Detailed phase cards
  data.blocks.forEach((block, i) => {
    y = checkPageBreak(doc, y, 35);
    y = addSectionTitle(doc, y, `Phase ${block.sequence}: ${block.phaseName}`);
    y = addKeyValue(doc, y, 'Framework', block.nasmFramework);
    if (block.focus) y = addKeyValue(doc, y, 'Focus', block.focus);
    y = addKeyValue(doc, y, 'Duration', `${block.durationWeeks} weeks · ${block.sessionsPerWeek || '?'} sessions/week`);
    if (block.entryCriteria) y = addKeyValue(doc, y, 'Entry Criteria', block.entryCriteria);
    if (block.exitCriteria) y = addKeyValue(doc, y, 'Exit Criteria', block.exitCriteria);
    if (block.notes) {
      doc.setFont('helvetica', 'italic');
      doc.setFontSize(7);
      doc.setTextColor(...BRAND.textMuted);
      const noteLines = doc.splitTextToSize(block.notes, doc.internal.pageSize.getWidth() - 36);
      doc.text(noteLines, 18, y);
      y += noteLines.length * 3.5 + 3;
    }
    if (block.rationale) {
      doc.setFont('helvetica', 'italic');
      doc.setFontSize(7);
      doc.setTextColor(...BRAND.wingPurple);
      const rLines = doc.splitTextToSize(`Rationale: ${block.rationale}`, doc.internal.pageSize.getWidth() - 36);
      doc.text(rLines, 18, y);
      y += rLines.length * 3.5 + 4;
    }
    y += 2;
  });

  const fname = clientName ? clientName.replace(/[^a-zA-Z0-9]/g, '-') : 'Plan';
  finalizeAndDownload(doc, `SwanStudios-${data.horizonMonths}mo-Plan-${fname}.pdf`);
}


// =====================================================================
//  4. POPULATED LONG-HORIZON PLAN PDF (L3, 2026-05-02)
// =====================================================================
//
// Renders the per-day exercise breakdown for a plan whose
// `weeks[].days[].exercises[]` are populated by the L1 backend
// (workoutBuilderService). Distinct from `exportLongHorizonPDF` above —
// that exporter renders mesocycle SUMMARY only; this one walks every
// session in the horizon. For a 24-week × 4×/wk plan that is ~96
// session sections and ~576 exercise rows.
//
// Co-branding: Move Fitness clients get a text-based MF mark in the
// header. The receipt §G8 listed an MF logo image asset as a non-
// engineering blocker (Sean to confirm MF's approval before bundling
// the image asset). When that lands, swap the text mark for an
// `addImage()` call alongside the Swan brand bar.
//
// Light palette: receipt §6 flagged a Crystalline Swan light variant as
// a Gemini consult prerequisite. The conservative print-friendly
// palette below uses the existing BRAND constants (white bg, midnight-
// sapphire/wing-purple accents on dark text) — when the documented
// light variant lands, swap the per-section accent colors here.

export interface PDFLongHorizonExercise {
  exerciseId?: string;
  exerciseName?: string;
  name?: string;
  sets?: number | unknown[];
  reps?: number | string;
  targetReps?: number | string;
  restSeconds?: number;
  restTime?: number;
  tempo?: string;
  notes?: string;
  rotationFallback?: boolean;
}

export interface PDFLongHorizonDay {
  dayNumber: number;
  name?: string;
  dayName?: string;
  focus?: string;
  category?: string;
  exercises: PDFLongHorizonExercise[];
}

export interface PDFLongHorizonWeek {
  weekNumber: number;
  focus?: string;
  mesocycle?: number;
  nasmPhase?: number;
  days?: PDFLongHorizonDay[];
  sessions?: PDFLongHorizonDay[];
}

export interface PDFLongHorizonMesocycle {
  mesocycle: number | string;
  weeks: number | string;
  nasmPhase?: number;
  phaseName?: string;
  focus?: string;
  params?: { sets?: string; reps?: string; intensity?: string; tempo?: string; rest?: string };
  overloadStrategy?: string;
  deloadWeek?: number | null;
}

export interface PDFLongHorizonRecommendationDetail {
  type: string;
  text: string;
  sourceCitation?: string;
}

export interface PDFPopulatedPlan {
  planSummary: {
    durationWeeks: number;
    sessionsPerWeek: number;
    totalSessions: number;
    primaryGoal: string;
    startingPhase: number;
  };
  mesocycles: PDFLongHorizonMesocycle[];
  weeks: PDFLongHorizonWeek[];
  recommendations: string[];
  recommendationDetails?: PDFLongHorizonRecommendationDetail[];
}

export type PDFClientSource = string | null | undefined;

const pickFirstNonEmpty = <T>(...arrays: (T[] | undefined)[]): T[] => {
  for (const a of arrays) if (Array.isArray(a) && a.length > 0) return a;
  return [];
};

const addPopulatedPlanHeader = (
  doc: jsPDF,
  plan: PDFPopulatedPlan,
  horizon: ReturnType<typeof closestWorkoutPlanHorizon>,
  clientName?: string,
  clientSource?: PDFClientSource,
): number => {
  const titleLine = `${horizon.label} Periodized Plan`;
  const subtitle = `${plan.planSummary.totalSessions} sessions · ${plan.planSummary.sessionsPerWeek}×/week${clientName ? ` · ${clientName}` : ''}`;
  const y = addHeader(doc, titleLine, subtitle);

  if (normalizeClientSource(clientSource) === 'move_fitness') {
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(7);
    doc.setTextColor(...BRAND.gildedFern);
    doc.text('IN PARTNERSHIP WITH MOVE FITNESS', doc.internal.pageSize.getWidth() - 14, 19, { align: 'right' });
  }

  return y;
};

const addPopulatedPlanSummary = (
  doc: jsPDF,
  y: number,
  plan: PDFPopulatedPlan,
  horizon: ReturnType<typeof closestWorkoutPlanHorizon>,
): number => {
  let nextY = addSectionTitle(doc, y, 'Plan Summary');
  nextY = addKeyValue(doc, nextY, 'Duration', `${plan.planSummary.durationWeeks} weeks (${horizon.label} arc)`);
  nextY = addKeyValue(doc, nextY, 'Sessions per week', String(plan.planSummary.sessionsPerWeek));
  nextY = addKeyValue(doc, nextY, 'Total sessions', String(plan.planSummary.totalSessions));
  nextY = addKeyValue(doc, nextY, 'Primary goal', plan.planSummary.primaryGoal);
  nextY = addKeyValue(doc, nextY, 'Starting NASM phase', `Phase ${plan.planSummary.startingPhase}`);
  return nextY + 2;
};

const addPopulatedPlanMesocycles = (doc: jsPDF, y: number, plan: PDFPopulatedPlan): number => {
  let nextY = addSectionTitle(doc, y, 'Mesocycles');
  addAutoTable(doc, {
    startY: nextY,
    head: [['#', 'Phase', 'Weeks', 'Focus', 'Sets', 'Reps', 'Intensity', 'Rest']],
    body: plan.mesocycles.map((m) => [
      String(m.mesocycle),
      m.phaseName ? `${m.phaseName} (P${m.nasmPhase ?? '?'})` : `Phase ${m.nasmPhase ?? '?'}`,
      String(m.weeks),
      m.focus || '-',
      m.params?.sets || '-',
      m.params?.reps || '-',
      m.params?.intensity || '-',
      m.params?.rest || '-',
    ]),
    theme: 'grid',
    headStyles: { fillColor: BRAND.midnightSapphire, textColor: BRAND.white, fontSize: 7, fontStyle: 'bold' },
    bodyStyles: { fontSize: 7, textColor: BRAND.textDark },
    alternateRowStyles: { fillColor: BRAND.lightGray },
    styles: { cellPadding: 2, lineColor: BRAND.borderGray, lineWidth: 0.2 },
    margin: { left: 16, right: 16 },
    columnStyles: { 0: { cellWidth: 8, halign: 'center' }, 1: { fontStyle: 'bold' } },
  });
  nextY = getLastAutoTableY(doc, nextY) + 6;
  return nextY;
};

const addPopulatedPlanRecommendations = (doc: jsPDF, y: number, plan: PDFPopulatedPlan): number => {
  if (plan.recommendations.length === 0) return y;

  let nextY = checkPageBreak(doc, y, 12 + plan.recommendations.length * 5);
  nextY = addSectionTitle(doc, nextY, 'AI Recommendations');
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(8);

  plan.recommendations.forEach((rec, i) => {
    const detail = plan.recommendationDetails?.[i];
    const bullet = `• ${rec}`;
    doc.setTextColor(...BRAND.textDark);
    const lines = doc.splitTextToSize(bullet, doc.internal.pageSize.getWidth() - 36);
    doc.text(lines, 18, nextY);
    nextY += lines.length * 4;
    if (detail?.type) {
      doc.setFont('helvetica', 'italic');
      doc.setFontSize(6.5);
      doc.setTextColor(...BRAND.textMuted);
      doc.text(`  source type: ${detail.type}`, 22, nextY);
      nextY += 3.5;
      doc.setFont('helvetica', 'normal');
      doc.setFontSize(8);
    }
    nextY += 1;
  });

  return nextY + 2;
};

const getPopulatedPlanSetCount = (exercise: PDFLongHorizonExercise): number => {
  if (Array.isArray(exercise.sets)) return exercise.sets.length;
  return typeof exercise.sets === 'number' ? exercise.sets : 3;
};

const buildPopulatedExerciseRow = (exercise: PDFLongHorizonExercise): string[] => {
  const reps = exercise.targetReps ?? exercise.reps ?? '10';
  const rest = exercise.restSeconds ?? exercise.restTime ?? '';
  const restCell = rest ? `${rest}s` : '-';
  const noteCell = [
    exercise.tempo ? `tempo ${exercise.tempo}` : null,
    exercise.rotationFallback ? '⚑ fallback' : null,
    exercise.notes || null,
  ].filter(Boolean).join(' · ') || '-';

  return [
    exercise.exerciseName || exercise.name || 'Unknown',
    String(getPopulatedPlanSetCount(exercise)),
    String(reps),
    restCell,
    noteCell,
  ];
};

const addPopulatedPlanDay = (doc: jsPDF, y: number, day: PDFLongHorizonDay): number => {
  const dayLabel = day.name || day.dayName || `Day ${day.dayNumber}`;
  let nextY = checkPageBreak(doc, y, 18 + (day.exercises?.length || 0) * 5);

  doc.setFont('helvetica', 'bold');
  doc.setFontSize(8);
  doc.setTextColor(...BRAND.midnightSapphire);
  doc.text(`${dayLabel}${day.focus ? ` · ${day.focus}` : ''}`, 18, nextY);
  nextY += 4;

  if (Array.isArray(day.exercises) && day.exercises.length > 0) {
    addAutoTable(doc, {
      startY: nextY,
      head: [['Exercise', 'Sets', 'Reps', 'Rest', 'Notes']],
      body: day.exercises.map(buildPopulatedExerciseRow),
      theme: 'grid',
      headStyles: { fillColor: BRAND.royalDepth, textColor: BRAND.white, fontSize: 7, fontStyle: 'bold' },
      bodyStyles: { fontSize: 7, textColor: BRAND.textDark },
      alternateRowStyles: { fillColor: BRAND.lightGray },
      styles: { cellPadding: 1.5, lineColor: BRAND.borderGray, lineWidth: 0.15 },
      margin: { left: 18, right: 16 },
      columnStyles: {
        0: { fontStyle: 'bold', cellWidth: 60 },
        1: { cellWidth: 12, halign: 'center' },
        2: { cellWidth: 16, halign: 'center' },
        3: { cellWidth: 14, halign: 'center' },
      },
    });
    return getLastAutoTableY(doc, nextY) + 4;
  }

  doc.setFont('helvetica', 'italic');
  doc.setFontSize(7);
  doc.setTextColor(...BRAND.textMuted);
  doc.text('(no exercises populated)', 22, nextY);
  return nextY + 5;
};

const addPopulatedPlanWeek = (
  doc: jsPDF,
  y: number,
  week: PDFLongHorizonWeek,
  weekIndex: number,
): number => {
  let nextY = y;
  if (weekIndex % 4 === 0) {
    nextY = checkPageBreak(doc, nextY, 14);
    nextY = addSectionTitle(doc, nextY, `Month ${Math.floor(weekIndex / 4) + 1}`);
  }

  nextY = checkPageBreak(doc, nextY, 10);
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(9);
  doc.setTextColor(...BRAND.wingPurple);
  doc.text(`Week ${week.weekNumber}${week.focus ? ` — ${week.focus}` : ''}`, 16, nextY);
  nextY += 5;

  const days = pickFirstNonEmpty(week.days, week.sessions);
  if (days.length === 0) {
    doc.setFont('helvetica', 'italic');
    doc.setFontSize(7);
    doc.setTextColor(...BRAND.textMuted);
    doc.text('(no sessions populated for this week)', 18, nextY);
    return nextY + 7;
  }

  days.forEach((day) => {
    nextY = addPopulatedPlanDay(doc, nextY, day);
  });

  return nextY + 2;
};

const addPopulatedPlanWeeks = (doc: jsPDF, y: number, plan: PDFPopulatedPlan): number => {
  if (!Array.isArray(plan.weeks) || plan.weeks.length === 0) return y;
  return plan.weeks.reduce(
    (nextY, week, weekIndex) => addPopulatedPlanWeek(doc, nextY, week, weekIndex),
    y,
  );
};

const buildPopulatedPlanFilename = (horizonToken: string, clientName?: string): string => {
  const fname = clientName ? clientName.replace(/[^a-zA-Z0-9]/g, '-') : 'Plan';
  return `SwanStudios-${horizonToken}-Plan-${fname}.pdf`;
};

/**
 * L3 (2026-05-02) - branded PDF export of the populated long-horizon
 * workout plan. Walks every week in the horizon and prints each day's
 * exercises in a compact table. Co-brands with Move Fitness when the
 * client is an MF-tier client (text mark for now; image asset can drop
 * in later when MF approves logo licensing per receipt §G8).
 */
export function exportPopulatedPlanPDF(
  plan: PDFPopulatedPlan,
  clientName?: string,
  clientSource?: PDFClientSource,
): void {
  const doc = createPDF();
  const horizon = closestWorkoutPlanHorizon(plan.planSummary.durationWeeks);
  let y = addPopulatedPlanHeader(doc, plan, horizon, clientName, clientSource);
  y = addPopulatedPlanSummary(doc, y, plan, horizon);
  y = addPopulatedPlanMesocycles(doc, y, plan);
  y = addPopulatedPlanRecommendations(doc, y, plan);
  addPopulatedPlanWeeks(doc, y, plan);
  finalizeAndDownload(doc, buildPopulatedPlanFilename(horizon.token, clientName));
}
