/**
 * brandIdentity — resolves the on-document brand identity for a client-facing
 * PDF from the client's source.
 *
 * White-labels Move Fitness clients so NOTHING SwanStudios reaches an MF gym
 * member (a plan stamped "SwanStudios" on a gym's own member reads as poaching
 * the gym's client). SwanStudios clients get SwanStudios branding; unknown /
 * external sources fail SAFE to SwanStudios so a mis-tagged client is never
 * wrongly white-labeled to Move Fitness.
 *
 * Slice A1a scope: TEXT-level identity only (wordmark, footer credit, filename
 * prefix, recommendations heading) for the workout-plan PDF. Logo images, saved
 * per-owner presets, and the SwanStudios-client Move Fitness cross-promo credit
 * arrive with the preset store (A2) and the export editor (A3) — so
 * `moveFitnessCrossPromo` is off unless an override opts in.
 */
import { normalizeClientSource } from '../../utils/clientSource';

export type BrandKey = 'swanstudios' | 'move_fitness';

export interface BrandIdentity {
  /** which brand this resolved to */
  brandKey: BrandKey;
  /** header wordmark, e.g. "SwanStudios" | "Move Fitness" */
  wordmark: string;
  /** footer credit line (no SwanStudios URL on an MF doc) */
  footerCredit: string;
  /** filename brand prefix, e.g. "SwanStudios" | "MoveFitness" */
  filenamePrefix: string;
  /** recommendations section heading (Swan Coach vs. neutral) */
  recommendationsHeading: string;
  /** true only for SwanStudios docs (cover watermark etc. in later slices) */
  showSwanWatermark: boolean;
  /** discreet "in partnership with Move Fitness" credit on Sean's OWN clients (opt-in; wired in A3) */
  moveFitnessCrossPromo: boolean;
}

const SWANSTUDIOS_IDENTITY: BrandIdentity = {
  brandKey: 'swanstudios',
  wordmark: 'SwanStudios',
  footerCredit: 'Generated by SwanStudios · sswanstudios.com',
  filenamePrefix: 'SwanStudios',
  recommendationsHeading: 'Swan Coach Recommendations',
  showSwanWatermark: true,
  moveFitnessCrossPromo: false,
};

const MOVE_FITNESS_IDENTITY: BrandIdentity = {
  brandKey: 'move_fitness',
  wordmark: 'Move Fitness',
  footerCredit: 'Generated by Move Fitness',
  filenamePrefix: 'MoveFitness',
  recommendationsHeading: 'Coaching Recommendations',
  showSwanWatermark: false,
  moveFitnessCrossPromo: false,
};

export interface BrandIdentityOverrides {
  /** SwanStudios docs only: add a discreet Move Fitness cross-promo credit. Ignored on MF docs. */
  moveFitnessCrossPromo?: boolean;
}

/**
 * Resolve the brand identity for a client-facing document from the client's source.
 * - `move_fitness` → full white-label (Move Fitness only).
 * - `swanstudios` / `external` / unrecognized → SwanStudios (fail-safe: an
 *   unknown source never white-labels to Move Fitness).
 * Cross-promo is honored only on SwanStudios docs and never adds SwanStudios to an MF doc.
 */
export function resolveBrandIdentity(
  clientSource?: string | null,
  overrides?: BrandIdentityOverrides,
): BrandIdentity {
  const normalized = normalizeClientSource(clientSource);
  const base = normalized === 'move_fitness' ? MOVE_FITNESS_IDENTITY : SWANSTUDIOS_IDENTITY;
  if (base.brandKey === 'swanstudios' && overrides?.moveFitnessCrossPromo) {
    return { ...base, moveFitnessCrossPromo: true };
  }
  return base;
}
