import { describe, it, expect } from 'vitest';
import { resolveBrandIdentity } from './brandIdentity';

describe('resolveBrandIdentity', () => {
  it('fully white-labels move_fitness to Move Fitness (no SwanStudios/Swan Coach anywhere)', () => {
    const b = resolveBrandIdentity('move_fitness');
    expect(b.brandKey).toBe('move_fitness');
    expect(b.wordmark).toBe('Sean Swan at Move Fitness');
    expect(b.footerCredit).toBe('Generated by Sean Swan at Move Fitness');
    expect(b.filenamePrefix).toBe('MoveFitness');
    expect(b.recommendationsHeading).toBe('Coaching Recommendations');
    expect(b.showSwanWatermark).toBe(false);
    const serialized = JSON.stringify(b);
    expect(serialized).not.toContain('SwanStudios');
    expect(serialized).not.toContain('Swan Coach');
  });

  it('normalizes human/hyphenated Move Fitness inputs to the MF identity', () => {
    for (const src of [' Move Fitness ', 'move-fitness', 'move_fitness']) {
      expect(resolveBrandIdentity(src).brandKey).toBe('move_fitness');
    }
  });

  it('brands swanstudios as SwanStudios', () => {
    const b = resolveBrandIdentity('swanstudios');
    expect(b.brandKey).toBe('swanstudios');
    expect(b.wordmark).toBe('SwanStudios');
    expect(b.filenamePrefix).toBe('SwanStudios');
    expect(b.recommendationsHeading).toBe('Swan Coach Recommendations');
    expect(b.showSwanWatermark).toBe(true);
    expect(b.moveFitnessCrossPromo).toBe(false);
  });

  it('fails safe to SwanStudios for external / unknown / empty / null / undefined (never MF)', () => {
    for (const src of ['external', 'literally-anything', '', null, undefined]) {
      expect(resolveBrandIdentity(src).brandKey).toBe('swanstudios');
    }
  });

  it('honors a Move Fitness cross-promo only on SwanStudios docs, never on MF docs', () => {
    expect(
      resolveBrandIdentity('swanstudios', { moveFitnessCrossPromo: true }).moveFitnessCrossPromo,
    ).toBe(true);
    // An MF doc must ignore the override — a white-labeled MF plan never carries a SwanStudios-side credit.
    expect(
      resolveBrandIdentity('move_fitness', { moveFitnessCrossPromo: true }).moveFitnessCrossPromo,
    ).toBe(false);
  });
});
