/**
 * swanPdfKit
 * ==========
 * SwanStudios branded PDF document kit - the single source of the studio's
 * print identity (palette, header band, section titles, wrapped text, page
 * breaks, footer) shared by every generated document: workout plans, session
 * logs, and progress reports. One kit means every PDF a client receives
 * reads as the same studio.
 *
 * Print-safe by design: PDFs are paper documents, so the kit renders
 * ink-on-white with brand accents rather than the app's dark theme.
 *
 * Extracted from workoutPlannerPlanPdfAdapter (Phase P6) - the adapter now
 * consumes this kit, so its output is pixel-identical to before extraction.
 */
import type { jsPDF as PdfDoc } from 'jspdf';

export type PdfRgb = [number, number, number];

export const SWAN_PDF_BRAND = {
  midnight: [0, 32, 96] as PdfRgb,
  royal: [0, 48, 128] as PdfRgb,
  purple: [139, 92, 246] as PdfRgb,
  gold: [198, 168, 75] as PdfRgb,
  frost: [224, 236, 244] as PdfRgb,
  ink: [31, 41, 55] as PdfRgb,
  muted: [91, 103, 122] as PdfRgb,
  white: [255, 255, 255] as PdfRgb,
};

export const addPageIfNeeded = (doc: PdfDoc, y: number, needed = 12): number => {
  if (y + needed <= doc.internal.pageSize.getHeight() - 18) return y;
  doc.addPage();
  return 18;
};

export const addWrappedText = (
  doc: PdfDoc,
  text: string,
  x: number,
  y: number,
  maxWidth: number,
  lineHeight = 5,
): number => {
  const lines = doc.splitTextToSize(text, maxWidth) as string[];
  // Line-by-line with page breaks: a hostile-length title/note would
  // otherwise render past the page bottom and silently vanish (and push
  // every later section off-page with it). Non-breaking output is
  // position-identical to the previous single text() call.
  let cursor = y;
  for (const line of lines) {
    cursor = addPageIfNeeded(doc, cursor, lineHeight);
    doc.text(line, x, cursor);
    cursor += lineHeight;
  }
  return cursor;
};

export const addSectionTitle = (doc: PdfDoc, title: string, y: number): number => {
  const pageW = doc.internal.pageSize.getWidth();
  y = addPageIfNeeded(doc, y, 12);
  doc.setFillColor(...SWAN_PDF_BRAND.frost);
  doc.rect(14, y - 5, pageW - 28, 8, 'F');
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(10);
  doc.setTextColor(...SWAN_PDF_BRAND.midnight);
  doc.text(title, 16, y);
  return y + 10;
};

export interface SwanPdfHeaderInput {
  /** Right-aligned document label, e.g. "WORKOUT PLAN PDF". */
  docLabel: string;
  /** Right-aligned meta line under the label, e.g. the client name. */
  metaLine: string;
  /** Optional gold accent line below the band, e.g. a partnership credit. */
  accentLine?: string;
}

/** Renders the branded top band on the current page; returns the content start y. */
export const addBrandHeader = (doc: PdfDoc, { docLabel, metaLine, accentLine }: SwanPdfHeaderInput): number => {
  const pageW = doc.internal.pageSize.getWidth();

  doc.setFillColor(...SWAN_PDF_BRAND.midnight);
  doc.rect(0, 0, pageW, 18, 'F');
  doc.setFillColor(...SWAN_PDF_BRAND.purple);
  doc.rect(0, 18, pageW, 1.5, 'F');
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(14);
  doc.setTextColor(...SWAN_PDF_BRAND.white);
  doc.text('SwanStudios', 14, 12);
  doc.setFontSize(9);
  doc.text(docLabel, pageW - 14, 9, { align: 'right' });
  doc.setFontSize(7);
  doc.setTextColor(...SWAN_PDF_BRAND.frost);
  doc.text(metaLine, pageW - 14, 14, { align: 'right' });

  if (accentLine) {
    doc.setFontSize(7);
    doc.setTextColor(...SWAN_PDF_BRAND.gold);
    doc.text(accentLine, pageW - 14, 21, { align: 'right' });
  }

  return 24;
};

/** Stamps the branded footer (divider, credit, page X of Y) on every page. */
export const addBrandFooter = (doc: PdfDoc): void => {
  const totalPages = doc.getNumberOfPages();
  const pageW = doc.internal.pageSize.getWidth();
  const pageH = doc.internal.pageSize.getHeight();

  for (let page = 1; page <= totalPages; page += 1) {
    doc.setPage(page);
    doc.setDrawColor(...SWAN_PDF_BRAND.frost);
    doc.line(14, pageH - 12, pageW - 14, pageH - 12);
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(7);
    doc.setTextColor(...SWAN_PDF_BRAND.muted);
    doc.text('Generated by SwanStudios', 14, pageH - 6);
    doc.text(`Page ${page} of ${totalPages}`, pageW - 14, pageH - 6, { align: 'right' });
  }
};

/** Lazy-loads jspdf (keeps it out of the main bundle) and opens an A4 portrait doc. */
export const createSwanPdfDoc = async (): Promise<PdfDoc> => {
  const { jsPDF } = await import('jspdf');
  return new jsPDF({ orientation: 'portrait', unit: 'mm', format: 'a4' });
};
