import { describe, expect, it } from 'vitest';
import {
  SWAN_PDF_BRAND,
  addBrandFooter,
  addBrandHeader,
  addPageIfNeeded,
  addSectionTitle,
  addWrappedText,
} from './swanPdfKit';
import type { jsPDF as PdfDoc } from 'jspdf';
import { resolveBrandIdentity } from './brandIdentity';

const createFakeDoc = () => {
  const text: string[] = [];
  let pages = 1;
  const doc = {
    internal: { pageSize: { getWidth: () => 210, getHeight: () => 297 } },
    setFillColor: () => {},
    setDrawColor: () => {},
    rect: () => {},
    line: () => {},
    setFont: () => {},
    setFontSize: () => {},
    setTextColor: () => {},
    addPage: () => { pages += 1; },
    setPage: () => {},
    getNumberOfPages: () => pages,
    splitTextToSize: (value: string) => [value],
    text: (value: string | string[]) => { text.push(...(Array.isArray(value) ? value : [value])); },
  };
  return { doc: doc as unknown as PdfDoc, text, pageCount: () => pages };
};

describe('swanPdfKit', () => {
  it('brand header stamps the studio wordmark, label, and meta line; accent only when provided', () => {
    const { doc, text } = createFakeDoc();
    const y = addBrandHeader(doc, { docLabel: 'PROGRESS REPORT', metaLine: 'Client FortyTwo' });
    expect(y).toBe(24);
    expect(text).toContain('SwanStudios');
    expect(text).toContain('PROGRESS REPORT');
    expect(text).toContain('Client FortyTwo');
    expect(text.join(' ')).not.toContain('PARTNERSHIP');

    const accent = createFakeDoc();
    addBrandHeader(accent.doc, { docLabel: 'X', metaLine: 'Y', accentLine: 'IN PARTNERSHIP WITH MOVE FITNESS' });
    expect(accent.text).toContain('IN PARTNERSHIP WITH MOVE FITNESS');
  });

  it('white-labels the header + footer wordmark for a Move Fitness brand (no SwanStudios)', () => {
    const mf = resolveBrandIdentity('move_fitness');
    const { doc, text } = createFakeDoc();
    addBrandHeader(doc, { docLabel: 'PROGRESS REPORT', metaLine: 'MF Client' }, mf);
    addBrandFooter(doc, mf);
    expect(text).toContain('Move Fitness');
    expect(text).toContain('Generated by Move Fitness');
    expect(text.join(' ')).not.toContain('SwanStudios');
  });

  it('brand footer stamps page numbers on every page', () => {
    const { doc, text } = createFakeDoc();
    doc.addPage();
    addBrandFooter(doc);
    expect(text).toContain('Page 1 of 2');
    expect(text).toContain('Page 2 of 2');
    expect(text.filter((line) => line === 'Generated by SwanStudios')).toHaveLength(2);
  });

  it('section titles advance the cursor and page breaks trigger past the bottom margin', () => {
    const { doc, pageCount } = createFakeDoc();
    expect(addSectionTitle(doc, 'Weekly Plan', 30)).toBe(40);
    expect(addPageIfNeeded(doc, 20, 12)).toBe(20);
    expect(pageCount()).toBe(1);
    expect(addPageIfNeeded(doc, 290, 12)).toBe(18);
    expect(pageCount()).toBe(2);
  });

  it('wrapped text advances by line count and the brand palette stays print-safe ink-on-white', () => {
    const { doc } = createFakeDoc();
    expect(addWrappedText(doc, 'hello', 16, 50, 100, 5)).toBe(55);
    expect(SWAN_PDF_BRAND.white).toEqual([255, 255, 255]);
    expect(SWAN_PDF_BRAND.midnight).toEqual([0, 32, 96]);
  });
});
