/**
 * stages/render.mjs — RENDER stage (S1): compile the LayoutIR into a real HTML file.
 * ==================================================================================
 * Crude by design (S1 renders static HTML with Crystalline tokens, not production
 * React — S8 owns the production compiler), but REAL: the render is a file on
 * disk whose DOM stamps its structural provenance so VERIFY can prove the code
 * matches the IR (`data-skeleton`, `data-zone` — Grok 4.1's anti IR-A/code-B
 * round-trip check). Rule 6: every color is var(--token, #fallback).
 */
import { createHash } from 'node:crypto';
import { writeFileSync } from 'node:fs';
import { join } from 'node:path';

/** Crystalline Swan tokens (fallbacks are the palette of record — CLAUDE.md Active Palette). */
export const TOKENS = {
  bg: ['--bg-base', '#0A0A0F'],
  surface: ['--surface-royal', '#003080'],
  text: ['--text-frost', '#E0ECF4'],
  accent: ['--accent-primary', '#60C0F0'],
  gold: ['--accent-gold', '#C6A84B'],
};

const v = (t) => `var(${TOKENS[t][0]}, ${TOKENS[t][1]})`;

/**
 * The hero's actual layout varies with the skeleton's hero_mechanics — the
 * selected structure must reach PIXELS, not just a data attribute (panel:
 * "brief ≠ pixels"). S1 keeps this coarse; S2's IR compiler owns real zones.
 */
export function heroLayoutCss(heroMechanics) {
  const m = heroMechanics.toLowerCase();
  if (m.includes('split') || m.includes('asymmetric')) return 'display:grid;grid-template-columns:7fr 5fr;gap:24px;align-items:start;';
  if (m.includes('kpi') || m.includes('no-hero')) return 'display:flex;flex-wrap:wrap;gap:16px;align-items:center;padding-top:20px;padding-bottom:20px;';
  if (m.includes('editorial') || m.includes('single-column')) return 'max-width:680px;margin:0 auto;';
  if (m.includes('centered')) return 'text-align:center;';
  return '';
}

export function renderHtml(ir, content, opts = {}) {
  const textToken = opts.textToken ?? 'text';
  const sections = ir.zones
    .filter((z) => z.zone !== 'hero')
    .map((z) => {
      const s = content.sections.find((c) => c.slot === z.content_slot);
      if (!s) throw new Error(`zone ${z.zone} binds content slot "${z.content_slot}" which the content model does not carry`);
      return `
  <section data-zone="${z.zone}" style="padding:32px 24px;background:${v('bg')};">
    <h2 style="color:${v(textToken)};font-size:1.5rem;">${s.heading}</h2>
    <ul style="color:${v(textToken)};line-height:1.6;">
      ${s.facts.map((f) => `<li>${f}</li>`).join('\n      ')}
    </ul>
  </section>`;
    })
    .join('\n');

  const hero = content.sections.find((c) => c.slot === 'hero');
  return `<!-- generated by design-brain loop S1 — skeleton ${ir.skeleton_id} -->
<main data-skeleton="${ir.skeleton_id}" data-nav-model="${ir.nav_model}" data-grid="${ir.grid}"
      style="background:${v('bg')};min-height:100vh;font-family:'Plus Jakarta Sans',sans-serif;">
  <section data-zone="hero" data-hero-mechanics="${ir.hero_mechanics}"
           style="padding:56px 24px;background:${v('surface')};${heroLayoutCss(ir.hero_mechanics)}">
    <h1 style="color:${v(textToken)};font-size:2.25rem;max-width:22ch;">${content.primary_claim}</h1>
    <ul style="color:${v(textToken)};line-height:1.7;">
      ${(hero?.facts ?? []).map((f) => `<li>${f}</li>`).join('\n      ')}
    </ul>
    <a href="#book" data-cta style="display:inline-block;min-height:44px;min-width:44px;padding:12px 28px;
       background:${v('accent')};color:${v('bg')};border-radius:8px;font-weight:600;">${content.cta_label}</a>
  </section>
${sections}
</main>`;
}

export function renderStage(ctx) {
  const ir = ctx.artifacts.ir;
  const content = ctx.artifacts.content;
  const html = renderHtml(ir, content, ctx.renderOpts ?? {});
  const htmlPath = join(ctx.runDir, 'render.html');
  writeFileSync(htmlPath, html);
  return {
    render_id: `render-${ir.layout_ir_id}`,
    layout_ir_id: ir.layout_ir_id,
    content_model_id: content.content_model_id,
    html_path: htmlPath,
    html_hash: createHash('sha256').update(html).digest('hex').slice(0, 16),
  };
}
