/**
 * SwanMark3D — the SwanStudios header swan as a live 3-D object.
 *
 * One canvas, one geometry, sized entirely by CSS. Drop it in a container and
 * set that container's width/height; every size renders from the same mesh, so
 * there is no per-size asset and no size prop to keep in sync. Passing `size`
 * is a convenience for the common case, not a requirement.
 *
 * Progressive enhancement, on purpose
 * -----------------------------------
 * `three` and the 323 KB spec are dynamically imported, so they land in their own
 * chunks and never touch the header bundle. Until the chunks arrive - and forever
 * if WebGL is unavailable, the import fails, or the user prefers reduced motion
 * and we choose not to animate - the component shows a PNG. The layout box is
 * identical in both states, so there is no shift and no flash.
 *
 * That PNG is `assets/Logo.mark128.png`, NOT the 1.2 MB `Logo.png` brand asset.
 * The mark is laid out at 28-52 CSS px, so pointing the fallback at a 1024x1024
 * file made every page transfer 1.15 MiB to draw a 36px logo - and handed the
 * browser a 36:1 downscale, the regime where its resampler is worst. 128px is
 * matched to the sizes actually used; it was chosen by in-browser measurement at
 * dpr 1 and dpr 2 (`evidence/fallback_asset_audit.py`) and regenerated by
 * `evidence/make_fallback_mark.py`.
 *
 * The header can therefore adopt this without risking its first paint.
 */
import React, { useEffect, useRef, useState } from 'react';
import styled from 'styled-components';
import logoFallback from '../../assets/Logo.mark128.png';
import type { SwanMarkScene } from './swanMarkScene';

export interface SwanMark3DProps {
  /** CSS size in px. Omit to fill the parent element (the CSS-driven path). */
  size?: number | string;
  className?: string;
  style?: React.CSSProperties;
  /** Shown until WebGL is live, and permanently if it never is. */
  fallbackSrc?: string;
  alt?: string;
  /** True when an ancestor already labels the control (the header link does). */
  decorative?: boolean;
  yaw?: number;
  pitch?: number;
  /** Idle yaw drift, radians/second. Ignored under reduced motion. Default 0. */
  drift?: number;
  badgeDepth?: number;
  relief?: number;
  /** Backing-store multiple of css size. Default 2 - see swanMarkScene.ts. */
  supersample?: number;
  /** Lower bound on the backing store, in device px. Default 1 (no floor). */
  minBacking?: number;
  /** Upper bound on the backing store, in device px. Default 1024. */
  maxBacking?: number;
}

const Frame = styled.span<{ $size?: number | string }>`
  position: relative;
  display: inline-block;
  /* Without this the frame is baseline-aligned inside its parent's line box, and
     when the mark is SHORTER than the parent's line strut the descender pushes it
     down by a pixel. Measured at 16px: the canvas sat at y=129 while its box was
     at y=128. Every larger size escaped it only by being taller than the strut,
     which is exactly the kind of accident that breaks later. vertical-align: top
     is ignored when the parent is a flex container, so it costs nothing there. */
  vertical-align: top;
  width: ${(p) => (p.$size === undefined ? '100%' : typeof p.$size === 'number' ? `${p.$size}px` : p.$size)};
  height: ${(p) => (p.$size === undefined ? '100%' : typeof p.$size === 'number' ? `${p.$size}px` : p.$size)};
  aspect-ratio: 1 / 1;
  flex-shrink: 0;
  line-height: 0;
`;

const Canvas = styled.canvas`
  position: absolute;
  inset: 0;
  width: 100%;
  height: 100%;
  display: block;
`;

const FallbackImg = styled.img`
  position: absolute;
  inset: 0;
  width: 100%;
  height: 100%;
  display: block;
  object-fit: contain;
`;

const DEFAULT_FALLBACK = logoFallback;

function prefersReducedMotion(): boolean {
  return (
    typeof window !== 'undefined' &&
    typeof window.matchMedia === 'function' &&
    window.matchMedia('(prefers-reduced-motion: reduce)').matches
  );
}

export const SwanMark3D: React.FC<SwanMark3DProps> = ({
  size,
  className,
  style,
  fallbackSrc = DEFAULT_FALLBACK,
  alt = 'SwanStudios',
  decorative = false,
  yaw = 0,
  pitch = 0,
  drift = 0,
  badgeDepth,
  relief,
  supersample = 2,
  minBacking = 1,
  maxBacking = 1024,
}) => {
  const hostRef = useRef<HTMLSpanElement | null>(null);
  const canvasRef = useRef<HTMLCanvasElement | null>(null);
  const sceneRef = useRef<SwanMarkScene | null>(null);
  const [live, setLive] = useState(false);
  // Read once, synchronously, so the first effect run already knows.
  const reducedRef = useRef<boolean>(prefersReducedMotion());

  useEffect(() => {
    const host = hostRef.current;
    const canvas = canvasRef.current;
    if (!host || !canvas) return;

    let cancelled = false;
    let scene: SwanMarkScene | null = null;
    let ro: ResizeObserver | null = null;
    let motionQuery: MediaQueryList | null = null;
    let onMotionChange: (() => void) | null = null;
    let dprQuery: MediaQueryList | null = null;
    let dprListener: (() => void) | null = null;

    const applySize = () => {
      if (!scene) return;
      const r = host.getBoundingClientRect();
      // A hidden ancestor reports 0x0. Sizing to that would allocate a 1px
      // backing store and lose the render; wait for the observer to fire again.
      if (r.width < 1 || r.height < 1) return;
      scene.setSize(r.width, r.height);
      // Surfaced on the element so the QA harness (and a curious human in
      // devtools) can see both backing stores without reaching into the scene.
      const b = scene.backing;
      host.dataset.swanbacking = `${b.width}x${b.height}`;
      host.dataset.swangl = `${b.glWidth}x${b.glHeight}`;
    };

    (async () => {
      try {
        // Both dynamic: this pulls `three` (~600 KB) and the 323 KB spec into
        // their own chunks, so neither touches the header bundle.
        const [{ createSwanMarkScene }, specModule] = await Promise.all([
          import('./swanMarkScene'),
          import('../../three/swanMark/swan-mark.mesh.json'),
        ]);
        if (cancelled) return;

        const spec = (specModule as { default: unknown }).default;

        scene = createSwanMarkScene({
          canvas,
          spec: spec as never,
          supersample,
          minBacking,
          maxBacking,
          yaw,
          pitch,
          drift: reducedRef.current ? 0 : drift,
          ...(badgeDepth !== undefined ? { badgeDepth } : {}),
          ...(relief !== undefined ? { relief } : {}),
        });
        sceneRef.current = scene;

        applySize();
        setLive(true);

        if (typeof ResizeObserver !== 'undefined') {
          ro = new ResizeObserver(applySize);
          ro.observe(host);
        } else {
          window.addEventListener('resize', applySize);
        }

        // A ResizeObserver does NOT fire when only the device pixel ratio changes,
        // which happens when a window is dragged to a display with a different
        // density. Without this the backing store would stay sized for the old
        // monitor and the mark would render soft. The media query is pinned to the
        // CURRENT ratio, so it fires once per change and is then re-armed.
        if (typeof window.matchMedia === 'function') {
          const watchDpr = () => {
            if (cancelled) return;
            dprQuery = window.matchMedia(`(resolution: ${window.devicePixelRatio}dppx)`);
            dprListener = () => {
              applySize();
              watchDpr();
            };
            dprQuery.addEventListener?.('change', dprListener, { once: true });
          };
          watchDpr();
        }

        // Honour a preference change made mid-session, e.g. the user turning
        // reduced motion on while the page is open.
        if (typeof window.matchMedia === 'function') {
          motionQuery = window.matchMedia('(prefers-reduced-motion: reduce)');
          onMotionChange = () => {
            reducedRef.current = motionQuery!.matches;
            scene?.setDrift(motionQuery!.matches ? 0 : drift);
          };
          motionQuery.addEventListener?.('change', onMotionChange);
        }
      } catch (err) {
        // Any failure at all leaves the PNG in place. A logo is not worth a
        // broken header, so this is deliberately silent in production.
        if (import.meta.env.DEV) {
          // eslint-disable-next-line no-console
          console.warn('[SwanMark3D] falling back to the static mark:', err);
        }
        if (!cancelled) setLive(false);
      }
    })();

    return () => {
      cancelled = true;
      ro?.disconnect();
      window.removeEventListener('resize', applySize);
      if (motionQuery && onMotionChange) motionQuery.removeEventListener?.('change', onMotionChange);
      if (dprQuery && dprListener) dprQuery.removeEventListener?.('change', dprListener);
      scene?.dispose();
      sceneRef.current = null;
    };
    // Intentionally mount-once: prop changes below are applied through the scene
    // API, and re-creating the renderer on every prop change would thrash GL.
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);

  // View changes are cheap and must not rebuild the scene.
  useEffect(() => {
    sceneRef.current?.setView(yaw, pitch);
  }, [yaw, pitch]);

  // `drift` is a documented prop, so changing it has to reach the scene - the
  // mount-once effect above deliberately does not re-run, which meant a new drift
  // rate was silently dropped. Reduced motion still wins, and `setDrift` is a
  // no-op when the value is unchanged, so this costs nothing at mount.
  useEffect(() => {
    sceneRef.current?.setDrift(reducedRef.current ? 0 : drift);
  }, [drift]);

  return (
    <Frame
      ref={hostRef}
      className={className}
      style={style}
      $size={size}
      role={decorative ? undefined : 'img'}
      aria-label={decorative ? undefined : alt}
      aria-hidden={decorative ? true : undefined}
      data-swanmark3d={live ? 'live' : 'fallback'}
    >
      {/* The canvas stays mounted so the GL context is created against a stable
          element; the PNG simply covers it until the scene is live. */}
      <Canvas ref={canvasRef} aria-hidden="true" />
      {!live && <FallbackImg src={fallbackSrc} alt="" aria-hidden="true" draggable={false} />}
    </Frame>
  );
};

export default SwanMark3D;
