import { readFileSync } from 'node:fs';
import { resolve } from 'node:path';

const readSource = (path: string) => readFileSync(resolve(process.cwd(), path), 'utf8');

describe('ClaimAccountPage claim token contract', () => {
  it('allows manual entry of the full SWAN-XXXXXXXX code generated by the backend', () => {
    const pageSource = readSource('src/pages/ClaimAccountPage.tsx');
    const claimTokenSource = readSource('../backend/services/claimTokenService.mjs');

    expect(claimTokenSource).toContain('crypto.randomBytes(8)');
    expect(claimTokenSource).toContain('const plainToken = `SWAN-${suffix}`;');
    expect(pageSource).toContain("const CLAIM_TOKEN_PLACEHOLDER = 'SWAN-XXXXXXXX';");
    expect(pageSource).toContain('const CLAIM_TOKEN_MAX_LENGTH = CLAIM_TOKEN_PLACEHOLDER.length;');
    expect(pageSource).toContain('placeholder={CLAIM_TOKEN_PLACEHOLDER}');
    expect(pageSource).toContain('maxLength={CLAIM_TOKEN_MAX_LENGTH}');
  });
});
