export interface SwanStyleLensVisualReceipt {
  signatureMoment: string;
  assetTier: "static-css";
  primaryActionMinHeight: number;
  textContrast: number;
  foregroundToken: string;
  backgroundToken: string;
  foregroundFallback: string;
  backgroundFallback: string;
  blueButtonGlowToken: "wing-purple";
  purpleButtonGlowToken: "ice-wing";
  accentFallback?: string;
  accentBackgroundFallback?: string;
  accentContrast?: number;
  accentUsage?: "decorative" | "text";
  /** Catalog grouping (Lab v6). One of the five §4.2 families. */
  moodFamily?: "playful" | "calm" | "technical" | "luxe" | "atmospheric";
}

export const SWAN_STYLE_LENS_VISUALS: Record<
  string,
  SwanStyleLensVisualReceipt
> = {
  "quiet-meridian": { moodFamily: "calm",
    signatureMoment:
      "A luminous meridian line aligns the active decision path.",
    assetTier: "static-css",
    primaryActionMinHeight: 48,
    textContrast: 14.57,
    foregroundToken: "frost-white",
    backgroundToken: "quiet-meridian-canvas",
    foregroundFallback: "#e0ecf4",
    backgroundFallback: "#06183a",
    blueButtonGlowToken: "wing-purple",
    purpleButtonGlowToken: "ice-wing",
  },
  "blueprint-fold": { moodFamily: "technical",
    signatureMoment:
      "Drafting planes fold from navigation into the working canvas.",
    assetTier: "static-css",
    primaryActionMinHeight: 48,
    textContrast: 12.7,
    foregroundToken: "frost-white",
    backgroundToken: "midnight-sapphire",
    foregroundFallback: "#e0ecf4",
    backgroundFallback: "#002060",
    blueButtonGlowToken: "wing-purple",
    purpleButtonGlowToken: "ice-wing",
  },
  "kintsugi-circuit": { moodFamily: "playful",
    signatureMoment: "A gilded circuit seam joins asymmetric working regions.",
    assetTier: "static-css",
    primaryActionMinHeight: 48,
    textContrast: 10.07,
    foregroundToken: "frost-white",
    backgroundToken: "royal-depth",
    foregroundFallback: "#e0ecf4",
    backgroundFallback: "#003080",
    blueButtonGlowToken: "wing-purple",
    purpleButtonGlowToken: "ice-wing",
    accentFallback: "#c6a84b",
    accentBackgroundFallback: "#003080",
    accentContrast: 5.25,
    accentUsage: "decorative",
  },
  "analog-flight-recorder": { moodFamily: "technical",
    signatureMoment:
      "A recorder status band turns the dashboard into an instrument.",
    assetTier: "static-css",
    primaryActionMinHeight: 48,
    textContrast: 15.28,
    foregroundToken: "frost-white",
    backgroundToken: "carbon",
    foregroundFallback: "#e0ecf4",
    backgroundFallback: "#141419",
    blueButtonGlowToken: "wing-purple",
    purpleButtonGlowToken: "ice-wing",
    accentFallback: "#c6a84b",
    accentBackgroundFallback: "#141419",
    accentContrast: 7.96,
    accentUsage: "decorative",
  },
  "candy-glass-arcade": { moodFamily: "playful",
    signatureMoment:
      "A responsive glass action dock frames the next best move.",
    assetTier: "static-css",
    primaryActionMinHeight: 48,
    textContrast: 12.01,
    foregroundToken: "frost-white",
    backgroundToken: "candy-glass-composite",
    foregroundFallback: "#e0ecf4",
    backgroundFallback: "#2e2152",
    blueButtonGlowToken: "wing-purple",
    purpleButtonGlowToken: "ice-wing",
  },
  "recovery-cloister": { moodFamily: "calm",
    signatureMoment: "A quiet readiness ring anchors the lower-action sanctuary.",
    assetTier: "static-css", primaryActionMinHeight: 48, textContrast: 13.2,
    foregroundToken: "frost-white", backgroundToken: "recovery-cloister-canvas",
    foregroundFallback: "#e0ecf4", backgroundFallback: "#08243a",
    blueButtonGlowToken: "wing-purple", purpleButtonGlowToken: "ice-wing",
  },
  "tempo-forge": { moodFamily: "playful",
    signatureMoment: "Cadence bands preserve a tempo-safe working zone.",
    assetTier: "static-css", primaryActionMinHeight: 48, textContrast: 15.28,
    foregroundToken: "frost-white", backgroundToken: "carbon",
    foregroundFallback: "#e0ecf4", backgroundFallback: "#141419",
    blueButtonGlowToken: "wing-purple", purpleButtonGlowToken: "ice-wing",
  },
  "coach-ledger": { moodFamily: "technical",
    signatureMoment: "A gilded annotation margin turns coaching history into an index.",
    assetTier: "static-css", primaryActionMinHeight: 48, textContrast: 14.36,
    foregroundToken: "frost-white", backgroundToken: "graphite",
    foregroundFallback: "#e0ecf4", backgroundFallback: "#1a1a24",
    blueButtonGlowToken: "wing-purple", purpleButtonGlowToken: "ice-wing",
  },
  "signal-garden": { moodFamily: "playful",
    signatureMoment: "A branching progress rail grows toward the next best action.",
    assetTier: "static-css", primaryActionMinHeight: 48, textContrast: 11.97,
    foregroundToken: "frost-white", backgroundToken: "signal-garden-canvas",
    foregroundFallback: "#e0ecf4", backgroundFallback: "#062e3a",
    blueButtonGlowToken: "wing-purple", purpleButtonGlowToken: "ice-wing",
  },
  "split-horizon": { moodFamily: "atmospheric",
    signatureMoment: "A luminous horizon separates live work from decision insight.",
    assetTier: "static-css", primaryActionMinHeight: 48, textContrast: 13.59,
    foregroundToken: "frost-white", backgroundToken: "split-horizon-canvas",
    foregroundFallback: "#e0ecf4", backgroundFallback: "#101d46",
    blueButtonGlowToken: "wing-purple", purpleButtonGlowToken: "ice-wing",
  },  "prism-terminal": { moodFamily: "technical", signatureMoment: "A faceted command plane refracts status into action.", assetTier: "static-css", primaryActionMinHeight: 48, textContrast: 13.55, foregroundToken: "frost-white", backgroundToken: "prism-terminal-canvas", foregroundFallback: "#e0ecf4", backgroundFallback: "#10203a", blueButtonGlowToken: "wing-purple", purpleButtonGlowToken: "ice-wing" },
  "tidal-columns": { moodFamily: "atmospheric", signatureMoment: "Three offset currents carry orientation, work, and insight.", assetTier: "static-css", primaryActionMinHeight: 48, textContrast: 12.33, foregroundToken: "frost-white", backgroundToken: "tidal-columns-canvas", foregroundFallback: "#e0ecf4", backgroundFallback: "#062a42", blueButtonGlowToken: "wing-purple", purpleButtonGlowToken: "ice-wing" },
  "monastic-grid": { moodFamily: "calm", signatureMoment: "Measured cells let the working facts become the atmosphere.", assetTier: "static-css", primaryActionMinHeight: 48, textContrast: 14.47, foregroundToken: "frost-white", backgroundToken: "monastic-grid-canvas", foregroundFallback: "#e0ecf4", backgroundFallback: "#181a20", blueButtonGlowToken: "wing-purple", purpleButtonGlowToken: "ice-wing" },
  "orbit-atlas": { moodFamily: "playful", signatureMoment: "Concentric planning paths reveal the longer training horizon.", assetTier: "static-css", primaryActionMinHeight: 48, textContrast: 14.68, foregroundToken: "frost-white", backgroundToken: "orbit-atlas-canvas", foregroundFallback: "#e0ecf4", backgroundFallback: "#0e1638", blueButtonGlowToken: "wing-purple", purpleButtonGlowToken: "ice-wing" },
  "carbon-atelier": { moodFamily: "luxe", signatureMoment: "A tactile tool rail opens onto a generous craft canvas.", assetTier: "static-css", primaryActionMinHeight: 48, textContrast: 14.87, foregroundToken: "frost-white", backgroundToken: "carbon-atelier-canvas", foregroundFallback: "#e0ecf4", backgroundFallback: "#17171b", blueButtonGlowToken: "wing-purple", purpleButtonGlowToken: "ice-wing" },  "kinetic-kanban": { moodFamily: "playful", signatureMoment: "Weighted swimlanes make momentum and priority visible.", assetTier: "static-css", primaryActionMinHeight: 48, textContrast: 14.18, foregroundToken: "frost-white", backgroundToken: "kinetic-kanban-canvas", foregroundFallback: "#e0ecf4", backgroundFallback: "#131b33", blueButtonGlowToken: "wing-purple", purpleButtonGlowToken: "ice-wing" },
  "aurora-index": { moodFamily: "atmospheric", signatureMoment: "A luminous index reveals the dashboard in a guided sequence.", assetTier: "static-css", primaryActionMinHeight: 48, textContrast: 13.16, foregroundToken: "frost-white", backgroundToken: "aurora-index-canvas", foregroundFallback: "#e0ecf4", backgroundFallback: "#0a2340", blueButtonGlowToken: "wing-purple", purpleButtonGlowToken: "ice-wing" },
  "modular-harbor": { moodFamily: "playful", signatureMoment: "Docked work berths gather tools around a stable command pier.", assetTier: "static-css", primaryActionMinHeight: 48, textContrast: 12.83, foregroundToken: "frost-white", backgroundToken: "modular-harbor-canvas", foregroundFallback: "#e0ecf4", backgroundFallback: "#0b2738", blueButtonGlowToken: "wing-purple", purpleButtonGlowToken: "ice-wing" },
  "terrain-console": { moodFamily: "technical", signatureMoment: "Contour rings translate readiness into navigable terrain.", assetTier: "static-css", primaryActionMinHeight: 48, textContrast: 13.88, foregroundToken: "frost-white", backgroundToken: "terrain-console-canvas", foregroundFallback: "#e0ecf4", backgroundFallback: "#182018", blueButtonGlowToken: "wing-purple", purpleButtonGlowToken: "ice-wing" },
  "chronograph-board": { moodFamily: "technical", signatureMoment: "A precision dial makes cadence and recovery the organizing axis.", assetTier: "static-css", primaryActionMinHeight: 48, textContrast: 14.32, foregroundToken: "frost-white", backgroundToken: "chronograph-board-canvas", foregroundFallback: "#e0ecf4", backgroundFallback: "#1c1a22", blueButtonGlowToken: "wing-purple", purpleButtonGlowToken: "ice-wing" },  "glass-rail": { moodFamily: "luxe", signatureMoment: "A floating glass spine keeps every tool within calm reach.", assetTier: "static-css", primaryActionMinHeight: 48, textContrast: 13.08, foregroundToken: "frost-white", backgroundToken: "glass-rail-canvas", foregroundFallback: "#e0ecf4", backgroundFallback: "#10243a", blueButtonGlowToken: "wing-purple", purpleButtonGlowToken: "ice-wing" },
  "meridian-magazine": { moodFamily: "luxe", signatureMoment: "An editorial spread makes the primary decision the largest idea.", assetTier: "static-css", primaryActionMinHeight: 48, textContrast: 14.36, foregroundToken: "frost-white", backgroundToken: "graphite", foregroundFallback: "#e0ecf4", backgroundFallback: "#1a1a24", blueButtonGlowToken: "wing-purple", purpleButtonGlowToken: "ice-wing" },
  "lunar-stack": { moodFamily: "calm", signatureMoment: "Mission plates reveal work, proof, and action by depth.", assetTier: "static-css", primaryActionMinHeight: 48, textContrast: 14.65, foregroundToken: "frost-white", backgroundToken: "lunar-stack-canvas", foregroundFallback: "#e0ecf4", backgroundFallback: "#12182c", blueButtonGlowToken: "wing-purple", purpleButtonGlowToken: "ice-wing" },
  "cedar-workshop": { moodFamily: "atmospheric", signatureMoment: "A parts wall and workbench frame durable daily practice.", assetTier: "static-css", primaryActionMinHeight: 48, textContrast: 13.22, foregroundToken: "frost-white", backgroundToken: "cedar-workshop-canvas", foregroundFallback: "#e0ecf4", backgroundFallback: "#1d241c", blueButtonGlowToken: "wing-purple", purpleButtonGlowToken: "ice-wing" },
  "crystalline-cathedral": { moodFamily: "luxe", signatureMoment: "A vaulted crystalline nave aligns identity, evidence, and next action.", assetTier: "static-css", primaryActionMinHeight: 48, textContrast: 14.24, foregroundToken: "frost-white", backgroundToken: "crystalline-cathedral-canvas", foregroundFallback: "#e0ecf4", backgroundFallback: "#071b3a", blueButtonGlowToken: "wing-purple", purpleButtonGlowToken: "ice-wing" },
  "aurora-console": { moodFamily: "atmospheric", signatureMoment: "A state-reactive aurora sheet makes the console's presence readable as weather.", assetTier: "static-css", primaryActionMinHeight: 48, textContrast: 13.16, foregroundToken: "frost-white", backgroundToken: "aurora-console-canvas", foregroundFallback: "#e0ecf4", backgroundFallback: "#0a2340", blueButtonGlowToken: "wing-purple", purpleButtonGlowToken: "ice-wing" },};
