#!/usr/bin/env node
/**
 * ============================================================================
 * FILE: scripts/creator-brains/test/readiness.test.mjs
 * PURPOSE: Keep the readiness receipt honest — the gate must pass it, and the
 *          committed receipt must be the one the generator produces today.
 * PART OF: Creator Brains — SS-PT acquisition engine (review repair HR26)
 * ADDED: 2026-09-13
 * ============================================================================
 *
 * WHY THIS IS A TEST AND NOT A ONE-OFF COMMAND:
 *   HR26's complaint was a receipt whose claims had drifted from the artifacts —
 *   stale counts, a mutation figure the document did not support, a status that
 *   contradicted another status. A receipt that is verified once will drift again.
 *   These assertions make drift a test failure:
 *
 *     1. the INSTALLED readiness integrity gate passes the committed receipt;
 *     2. the committed receipt equals what the generator builds right now — which
 *        also re-hashes every evidence file, so an edited log makes this fail until
 *        the receipt is regenerated (`node scripts/creator-brains/readiness.mjs
 *        --write`);
 *     3. the generated requirement map exists and lists every finding HR01–HR26;
 *     4. the receipt claims no review as passed, and names what is NOT built.
 *
 * RUN: node --experimental-test-isolation=none --test scripts/creator-brains/test/readiness.test.mjs
 * @module creator-brains/test/readiness
 */

import assert from 'node:assert/strict';
import { test } from 'node:test';
import { execFileSync } from 'node:child_process';
import { readFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const HERE = dirname(fileURLToPath(import.meta.url));
const ENGINE = join(HERE, '..');
const REPO = join(ENGINE, '..', '..');
const RECEIPT = join(REPO, 'docs', 'ai-workflow', 'AI-HANDOFF', 'CREATOR-BRAINS-READINESS-RECEIPT-2026-09-13.json');
const MAP = join(REPO, 'docs', 'ai-workflow', 'AI-HANDOFF', 'CREATOR-BRAINS-REQUIREMENT-MAP-2026-09-13.md');

test('R1 the installed readiness gate passes the committed receipt', () => {
  const gate = join(REPO, 'scripts', 'build-protocol', 'check-readiness.mjs');
  const stdout = execFileSync(process.execPath, [gate, RECEIPT], { encoding: 'utf8' });
  const verdict = JSON.parse(stdout);
  assert.equal(verdict.structurallyReady, true, `gate errors: ${JSON.stringify(verdict.errors)}`);
  assert.deepEqual(verdict.errors, [], 'the gate reports no structural errors');
  // The gate's own limitation is quoted so nobody reads this as a behaviour claim.
  assert.match(verdict.limitation, /Reference integrity only/);
});

test('R2 the committed receipt is the one the generator produces now (hashes included)', async () => {
  const { buildReceipt } = await import('../readiness.mjs');
  const fresh = JSON.stringify(buildReceipt(), null, 2);
  const onDisk = readFileSync(RECEIPT, 'utf8').replace(/\n$/, '');
  assert.equal(onDisk, fresh,
    'the receipt has drifted from its sources — regenerate with: '
    + 'node scripts/creator-brains/readiness.mjs --write '
    + '(an edited evidence file or a changed mapping does this)');
});

test('R3 the requirement map covers HR01–HR26 and names a test for each', () => {
  const text = readFileSync(MAP, 'utf8');
  for (let i = 1; i <= 26; i += 1) {
    const id = `HR${String(i).padStart(2, '0')}`;
    assert.match(text, new RegExp(`\\*\\*${id}\\*\\*`), `${id} is mapped to tests`);
  }
  assert.match(text, /GENERATED by scripts\/creator-brains\/readiness\.mjs/,
    'the map says it is generated, so nobody hand-edits it');
});

test('R4 the receipt separates what is built from what is not, and claims no review as passed', async () => {
  const { buildReceipt } = await import('../readiness.mjs');
  const receipt = buildReceipt();
  assert.deepEqual(receipt.blockers, [], 'no open blocker is claimed against this receipt');
  assert.match(receipt.nextSlice, /HR10 live authorization/, 'the next slice is named');
  assert.deepEqual(receipt.scope.deferred, ['semantic retrieval (lexical search only)']);
  assert.deepEqual(receipt.scope.notRun, ['live OAuth authorization', 'vault copy to the headless machine (owner-run)']);
  assert.match(receipt.scope.unreconciled[0], /MISSING/, 'the unseen spec stays unreconciled');
  assert.match(receipt.reviewIdentity.notClaimed, /NOT recorded as approved/,
    'the review is not claimed as passed');
  assert.equal(receipt.phase, 'implementation');
  for (const t of receipt.tests) {
    assert.equal(t.status, 'PASS', `${t.id} must be PASS in an implementation receipt`);
  }
});
