/**
 * v11 — front-page variant component.
 * @module pages/HomePage/three-worlds/v11/v11
 *
 * GENERATED by scripts/swan-brain-console/generate-worlds.mjs from registry.ts.
 * Edit the registry or the shared runtime, not this file — changes here are
 * overwritten on the next generate run.
 *
 * This module imports three directly because each variant owns its accent
 * composition against the shared runtime; the scene family it resolves to comes
 * from its skeleton's hero mechanic.
 */
import * as THREE from 'three';
import React, { useMemo } from 'react';
import WorldPage from '../WorldPage';
import { SKELETON } from './skeleton';

/** Hint the bundler this chunk is canvas-heavy, so it splits away from the gallery. */
const SCENE_VERSION = THREE.REVISION;

const V11World: React.FC<{ linkPrefix?: string }> = ({ linkPrefix = '' }) => {
  const label = useMemo(
    () => `${SKELETON.id} · ${SKELETON.hero_mechanics} · three r${SCENE_VERSION}`,
    [],
  );
  return (
    <div data-scene-label={label}>
      <WorldPage skeleton={SKELETON} linkPrefix={linkPrefix} />
    </div>
  );
};

export default V11World;
