import type { ConceptRegistryItem } from './conceptRegistry.types';
import { CONCEPT_PALETTE } from './conceptRegistry.types';
import { DesertObservatory } from './concepts/DesertObservatory';
import { RedwoodTitanStudio } from './concepts/RedwoodTitanStudio';
import { TropicalStormPerformanceDeck } from './concepts/TropicalStormPerformanceDeck';
import { CoralReefMovementLab } from './concepts/CoralReefMovementLab';
import { MoonbaseCoachConsole } from './concepts/MoonbaseCoachConsole';
import { RainyTokyoTrainingNight } from './concepts/RainyTokyoTrainingNight';
import { LondonAthleticArchive } from './concepts/LondonAthleticArchive';
import { MediterraneanTrainingVilla } from './concepts/MediterraneanTrainingVilla';
import { SwissPrecisionLab } from './concepts/SwissPrecisionLab';
import { CaribbeanSunriseEnergy } from './concepts/CaribbeanSunriseEnergy';
import { DeepOceanTrenchObservatory } from './concepts/DeepOceanTrenchObservatory';
import { CrystallineSwanWorld } from './concepts/CrystallineSwanWorld';

export const CONCEPT_REGISTRY_PART_TWO: ConceptRegistryItem[] = [
  {
    id: "desert-observatory",
    number: "14",
    name: "Desert Observatory",
    description: "sandstone night grid",
    environmentFamily: "Desert",
    interactionModel: "star-grid logging",
    paletteTokens: CONCEPT_PALETTE,
    typographyDirection: "minimal astronomy",
    backgroundStrategy: "sandstone night grid",
    component: DesertObservatory,
    writeCapability: "prototype-only",
    reducedMotion: "reduced",
    primaryActionLabel: "Record desert set",
  },
  {
    id: "redwood-titan-studio",
    number: "15",
    name: "Redwood Titan Studio",
    description: "redwood ring field",
    environmentFamily: "Forest",
    interactionModel: "tree-ring milestones",
    paletteTokens: CONCEPT_PALETTE,
    typographyDirection: "timeless strength",
    backgroundStrategy: "redwood ring field",
    component: RedwoodTitanStudio,
    writeCapability: "prototype-only",
    reducedMotion: "reduced",
    primaryActionLabel: "Add growth ring",
  },
  {
    id: "tropical-storm-performance-deck",
    number: "16",
    name: "Tropical Storm Performance Deck",
    description: "storm vector field",
    environmentFamily: "Storm",
    interactionModel: "adaptive deck",
    paletteTokens: CONCEPT_PALETTE,
    typographyDirection: "weather command",
    backgroundStrategy: "storm vector field",
    component: TropicalStormPerformanceDeck,
    writeCapability: "prototype-only",
    reducedMotion: "reduced",
    primaryActionLabel: "Adapt deck intensity",
  },
  {
    id: "coral-reef-movement-lab",
    number: "17",
    name: "Coral Reef Movement Lab",
    description: "reef depth field",
    environmentFamily: "Ocean",
    interactionModel: "ecosystem groups",
    paletteTokens: CONCEPT_PALETTE,
    typographyDirection: "fluid movement",
    backgroundStrategy: "reef depth field",
    component: CoralReefMovementLab,
    writeCapability: "prototype-only",
    reducedMotion: "reduced",
    primaryActionLabel: "Balance movement ecosystem",
  },
  {
    id: "moonbase-coach-console",
    number: "18",
    name: "Moonbase Coach Console",
    description: "lunar module grid",
    environmentFamily: "Space",
    interactionModel: "mission modules",
    paletteTokens: CONCEPT_PALETTE,
    typographyDirection: "crisp technical",
    backgroundStrategy: "lunar module grid",
    component: MoonbaseCoachConsole,
    writeCapability: "prototype-only",
    reducedMotion: "reduced",
    primaryActionLabel: "Assemble mission plan",
  },
  {
    id: "rainy-tokyo-training-night",
    number: "19",
    name: "Rainy Tokyo Training Night",
    description: "neon rain geometry",
    environmentFamily: "City",
    interactionModel: "compact night logger",
    paletteTokens: CONCEPT_PALETTE,
    typographyDirection: "disciplined compact",
    backgroundStrategy: "neon rain geometry",
    component: RainyTokyoTrainingNight,
    writeCapability: "prototype-only",
    reducedMotion: "reduced",
    primaryActionLabel: "Commit night session",
  },
  {
    id: "london-athletic-archive",
    number: "20",
    name: "London Athletic Archive",
    description: "ledger line field",
    environmentFamily: "City",
    interactionModel: "editorial archive",
    paletteTokens: CONCEPT_PALETTE,
    typographyDirection: "classic editorial",
    backgroundStrategy: "ledger line field",
    component: LondonAthleticArchive,
    writeCapability: "prototype-only",
    reducedMotion: "reduced",
    primaryActionLabel: "File session record",
  },
  {
    id: "mediterranean-training-villa",
    number: "21",
    name: "Mediterranean Training Villa",
    description: "limestone sea field",
    environmentFamily: "Coast",
    interactionModel: "airy plan table",
    paletteTokens: CONCEPT_PALETTE,
    typographyDirection: "refined humanist",
    backgroundStrategy: "limestone sea field",
    component: MediterraneanTrainingVilla,
    writeCapability: "prototype-only",
    reducedMotion: "reduced",
    primaryActionLabel: "Set villa plan",
  },
  {
    id: "swiss-precision-lab",
    number: "22",
    name: "Swiss Precision Lab",
    description: "measurement grid",
    environmentFamily: "Technical",
    interactionModel: "calibration grid",
    paletteTokens: CONCEPT_PALETTE,
    typographyDirection: "precision grotesk",
    backgroundStrategy: "measurement grid",
    component: SwissPrecisionLab,
    writeCapability: "prototype-only",
    reducedMotion: "reduced",
    primaryActionLabel: "Calibrate working set",
  },
  {
    id: "caribbean-sunrise-energy",
    number: "23",
    name: "Caribbean Sunrise Energy",
    description: "sunrise energy field",
    environmentFamily: "Coast",
    interactionModel: "positive quick start",
    paletteTokens: CONCEPT_PALETTE,
    typographyDirection: "bright athletic",
    backgroundStrategy: "sunrise energy field",
    component: CaribbeanSunriseEnergy,
    writeCapability: "prototype-only",
    reducedMotion: "reduced",
    primaryActionLabel: "Start sunrise session",
  },
  {
    id: "deep-ocean-trench-observatory",
    number: "24",
    name: "Deep-Ocean Trench Observatory",
    description: "trench sonar grid",
    environmentFamily: "Ocean",
    interactionModel: "sonar diagnostics",
    paletteTokens: CONCEPT_PALETTE,
    typographyDirection: "diagnostic mono",
    backgroundStrategy: "trench sonar grid",
    component: DeepOceanTrenchObservatory,
    writeCapability: "prototype-only",
    reducedMotion: "reduced",
    primaryActionLabel: "Confirm pressure data",
  },
  {
    id: "crystalline-swan-world",
    number: "25",
    name: "Crystalline Swan World",
    description: "glacier-ocean-nebula field",
    environmentFamily: "Swan Signature",
    interactionModel: "flagship synthesis",
    paletteTokens: CONCEPT_PALETTE,
    typographyDirection: "Crystalline Swan",
    backgroundStrategy: "glacier-ocean-nebula field",
    component: CrystallineSwanWorld,
    writeCapability: "prototype-only",
    reducedMotion: "reduced",
    primaryActionLabel: "Stage Swan signature",
    recommended: true,
  },
];
