import type { ConceptRegistryItem } from './conceptRegistry.types';
import { CONCEPT_PALETTE } from './conceptRegistry.types';
import { AlpineGlacierCommand } from './concepts/AlpineGlacierCommand';
import { EvergreenRainforestTraining } from './concepts/EvergreenRainforestTraining';
import { UndergroundOceanCity } from './concepts/UndergroundOceanCity';
import { SouthPoleExpedition } from './concepts/SouthPoleExpedition';
import { SouthernCaliforniaCoast } from './concepts/SouthernCaliforniaCoast';
import { NewYorkTrainingDistrict } from './concepts/NewYorkTrainingDistrict';
import { CanadaBorealPerformance } from './concepts/CanadaBorealPerformance';
import { JamesWebbNebulaObservatory } from './concepts/JamesWebbNebulaObservatory';
import { SolarSystemMissionControl } from './concepts/SolarSystemMissionControl';
import { CometVelocityLab } from './concepts/CometVelocityLab';
import { GasCloudStrengthStudio } from './concepts/GasCloudStrengthStudio';
import { AuroraBorealisRecovery } from './concepts/AuroraBorealisRecovery';
import { VolcanicCoreTraining } from './concepts/VolcanicCoreTraining';

export const CONCEPT_REGISTRY_PART_ONE: ConceptRegistryItem[] = [
  {
    id: "alpine-glacier-command",
    number: "01",
    name: "Alpine Glacier Command",
    description: "crystalline contours",
    environmentFamily: "Polar",
    interactionModel: "precision logging",
    paletteTokens: CONCEPT_PALETTE,
    typographyDirection: "sharp geometric",
    backgroundStrategy: "crystalline contours",
    component: AlpineGlacierCommand,
    writeCapability: "prototype-only",
    reducedMotion: "reduced",
    primaryActionLabel: "Stage precision route",
  },
  {
    id: "evergreen-rainforest-training",
    number: "02",
    name: "Evergreen Rainforest Training",
    description: "mist and canopy gradients",
    environmentFamily: "Forest",
    interactionModel: "vertical growth trail",
    paletteTokens: CONCEPT_PALETTE,
    typographyDirection: "organic professional",
    backgroundStrategy: "mist and canopy gradients",
    component: EvergreenRainforestTraining,
    writeCapability: "prototype-only",
    reducedMotion: "reduced",
    primaryActionLabel: "Advance growth trail",
  },
  {
    id: "underground-ocean-city",
    number: "03",
    name: "Underground Ocean City",
    description: "bioluminescent city grid",
    environmentFamily: "Ocean",
    interactionModel: "transit destinations",
    paletteTokens: CONCEPT_PALETTE,
    typographyDirection: "technical transit",
    backgroundStrategy: "bioluminescent city grid",
    component: UndergroundOceanCity,
    writeCapability: "prototype-only",
    reducedMotion: "reduced",
    primaryActionLabel: "Route next destination",
  },
  {
    id: "south-pole-expedition",
    number: "04",
    name: "South Pole Expedition",
    description: "snowfield markers",
    environmentFamily: "Polar",
    interactionModel: "expedition route",
    paletteTokens: CONCEPT_PALETTE,
    typographyDirection: "expedition utility",
    backgroundStrategy: "snowfield markers",
    component: SouthPoleExpedition,
    writeCapability: "prototype-only",
    reducedMotion: "reduced",
    primaryActionLabel: "Advance expedition",
  },
  {
    id: "southern-california-coast",
    number: "05",
    name: "Southern California Coast",
    description: "coastal light bands",
    environmentFamily: "Coast",
    interactionModel: "quick-log horizon",
    paletteTokens: CONCEPT_PALETTE,
    typographyDirection: "relaxed athletic",
    backgroundStrategy: "coastal light bands",
    component: SouthernCaliforniaCoast,
    writeCapability: "prototype-only",
    reducedMotion: "reduced",
    primaryActionLabel: "Set coastal session",
  },
  {
    id: "new-york-training-district",
    number: "06",
    name: "New York Training District",
    description: "editorial grid",
    environmentFamily: "City",
    interactionModel: "subway workflow",
    paletteTokens: CONCEPT_PALETTE,
    typographyDirection: "condensed editorial",
    backgroundStrategy: "editorial grid",
    component: NewYorkTrainingDistrict,
    writeCapability: "prototype-only",
    reducedMotion: "reduced",
    primaryActionLabel: "Dispatch training line",
  },
  {
    id: "canada-boreal-performance",
    number: "07",
    name: "Canada Boreal Performance",
    description: "boreal season field",
    environmentFamily: "Forest",
    interactionModel: "seasonal blocks",
    paletteTokens: CONCEPT_PALETTE,
    typographyDirection: "calm resilient",
    backgroundStrategy: "boreal season field",
    component: CanadaBorealPerformance,
    writeCapability: "prototype-only",
    reducedMotion: "reduced",
    primaryActionLabel: "Lock seasonal block",
  },
  {
    id: "james-webb-nebula-observatory",
    number: "08",
    name: "James Webb Nebula Observatory",
    description: "CSS infrared nebula",
    environmentFamily: "Space",
    interactionModel: "celestial observation",
    paletteTokens: CONCEPT_PALETTE,
    typographyDirection: "observatory data",
    backgroundStrategy: "CSS infrared nebula",
    component: JamesWebbNebulaObservatory,
    writeCapability: "prototype-only",
    reducedMotion: "reduced",
    primaryActionLabel: "Log observation",
  },
  {
    id: "solar-system-mission-control",
    number: "09",
    name: "Solar System Mission Control",
    description: "planetary orbit grid",
    environmentFamily: "Space",
    interactionModel: "orbit stages",
    paletteTokens: CONCEPT_PALETTE,
    typographyDirection: "aerospace command",
    backgroundStrategy: "planetary orbit grid",
    component: SolarSystemMissionControl,
    writeCapability: "prototype-only",
    reducedMotion: "reduced",
    primaryActionLabel: "Authorize mission stage",
  },
  {
    id: "comet-velocity-lab",
    number: "10",
    name: "Comet Velocity Lab",
    description: "comet light trail",
    environmentFamily: "Space",
    interactionModel: "momentum vector",
    paletteTokens: CONCEPT_PALETTE,
    typographyDirection: "velocity display",
    backgroundStrategy: "comet light trail",
    component: CometVelocityLab,
    writeCapability: "prototype-only",
    reducedMotion: "reduced",
    primaryActionLabel: "Launch velocity set",
  },
  {
    id: "gas-cloud-strength-studio",
    number: "11",
    name: "Gas Cloud Strength Studio",
    description: "CSS gas cloud",
    environmentFamily: "Space",
    interactionModel: "pressure layers",
    paletteTokens: CONCEPT_PALETTE,
    typographyDirection: "atmospheric strength",
    backgroundStrategy: "CSS gas cloud",
    component: GasCloudStrengthStudio,
    writeCapability: "prototype-only",
    reducedMotion: "reduced",
    primaryActionLabel: "Set training pressure",
  },
  {
    id: "aurora-borealis-recovery",
    number: "12",
    name: "Aurora Borealis Recovery",
    description: "aurora light ribbons",
    environmentFamily: "Polar",
    interactionModel: "recovery bands",
    paletteTokens: CONCEPT_PALETTE,
    typographyDirection: "soft technical",
    backgroundStrategy: "aurora light ribbons",
    component: AuroraBorealisRecovery,
    writeCapability: "prototype-only",
    reducedMotion: "reduced",
    primaryActionLabel: "Stage recovery arc",
  },
  {
    id: "volcanic-core-training",
    number: "13",
    name: "Volcanic Core Training",
    description: "ember mineral field",
    environmentFamily: "Geologic",
    interactionModel: "controlled pressure",
    paletteTokens: CONCEPT_PALETTE,
    typographyDirection: "strong mineral",
    backgroundStrategy: "ember mineral field",
    component: VolcanicCoreTraining,
    writeCapability: "prototype-only",
    reducedMotion: "reduced",
    primaryActionLabel: "Temper core session",
  },
];
