/** Read-only comparison surface for eight unified logger concepts. */
import React,{useMemo,useState}from'react';
import{CheckCircle2,ChevronRight,Database,Sparkles}from'lucide-react';
import{WORKOUT_DESIGN_CONCEPTS}from'./workoutDesignConcepts';
import{CompareNote,ConceptButton,ConceptNav,ExerciseCard,Eyebrow,Hero,HeroNote,LabShell,Panel,Pill,PillRow,PrimaryAction,Signal,Workbench}from'./WorkoutDesignLab.styles';
const exercises=[['Goblet squat','Lower body · stability','3 × 10'],['Half-kneeling cable press','Push · anti-rotation','3 × 8'],['Stability-ball row','Pull · core','3 × 12']];
const WorkoutDesignLabPage:React.FC=()=>{const[activeId,setActiveId]=useState(WORKOUT_DESIGN_CONCEPTS[0].id);const[activeSignal,setActiveSignal]=useState('Readiness 82');const active=useMemo(()=>WORKOUT_DESIGN_CONCEPTS.find(item=>item.id===activeId)??WORKOUT_DESIGN_CONCEPTS[0],[activeId]);return <LabShell style={{'--lab-accent':active.accent,'--lab-glow':active.glow}as React.CSSProperties}>
<Hero><div><Eyebrow>System / Workout Design Lab / {active.family} direction</Eyebrow><h1>{active.number}. {active.name}</h1><p>{active.thesis}</p></div><HeroNote><strong>Prototype only — no client data is written.</strong><br/>All directions preserve <code>/api/exercises/library</code>.</HeroNote></Hero>
<ConceptNav aria-label="Choose a workout design concept">{WORKOUT_DESIGN_CONCEPTS.map(concept=><ConceptButton key={concept.id}$active={concept.id===active.id}onClick={()=>setActiveId(concept.id)}aria-pressed={concept.id===active.id}><strong>{concept.number} · {concept.name}</strong><span>{concept.family==='swan'?'Crystalline Swan':'Wild direction'}</span></ConceptButton>)}</ConceptNav>
<Workbench $layout={active.layout}><Panel><Eyebrow>Orientation</Eyebrow><h3>Client & intent</h3><ExerciseCard type="button"><i/><span><strong>Demo Client</strong><small>Today · coached session</small></span><ChevronRight size={18}/></ExerciseCard><PillRow>{['Today','Tomorrow','Backfill'].map((item,index)=><Pill key={item}$active={index===0}>{item}</Pill>)}</PillRow><h3>Client-sensitive signals</h3>{['Readiness 82','Left knee 2/10','Missed Tuesday'].map(signal=><Signal key={signal}onClick={()=>setActiveSignal(signal)}><strong>{signal}</strong><br/><small>{signal===activeSignal?'Driving this draft':'Available context'}</small></Signal>)}</Panel>
<Panel $featured><Eyebrow>{active.signature}</Eyebrow><h2>Build today without leaving the client</h2><PillRow><Pill $active><Database size={15}/> Rolodex</Pill><Pill><Sparkles size={15}/> Coach draft</Pill><Pill>History</Pill><Pill>Plan horizon</Pill></PillRow>{exercises.map(([name,meta,prescription])=><ExerciseCard type="button"key={name}><i/><span><strong>{name}</strong><small>{meta}</small></span><b>{prescription}</b></ExerciseCard>)}<PrimaryAction type="button"onClick={()=>window.alert('Prototype: final review receipt.')}>Review & log session</PrimaryAction></Panel>
<Panel><Eyebrow>Trust before speed</Eyebrow><h3>Review receipt</h3><Signal><CheckCircle2 size={16}/> 3 exercises from active plan</Signal><Signal><CheckCircle2 size={16}/> Knee constraint applied</Signal><Signal><CheckCircle2 size={16}/> 1 missing day needs confirmation</Signal><p><strong>Suggested data is never silently presented as observed.</strong> Backfilled workouts remain pending until a trainer confirms date, source, and confidence.</p><PillRow><Pill>Generate draft</Pill><Pill>Review missing days</Pill><Pill>Save plan</Pill></PillRow></Panel></Workbench>
<CompareNote><strong>What changes:</strong> {active.signature} Shared client, workout, exercise-library, plan, and audit contracts remain fixed so this compares interaction models—not disconnected implementations.</CompareNote></LabShell>};
export default WorkoutDesignLabPage;
