export type ConceptFamily = 'swan' | 'wild';
export interface WorkoutDesignConcept { id: string; number: string; name: string; family: ConceptFamily; thesis: string; signature: string; layout: string; accent: string; glow: string; }
export const WORKOUT_DESIGN_CONCEPTS: WorkoutDesignConcept[] = [
  { id: 'flight-deck', number: '01', name: 'Coach Flight Deck', family: 'swan', thesis: 'Client, date, exercise intelligence, and session construction remain visible in one command surface.', signature: 'A persistent readiness rail turns missing context into clear preflight checks.', layout: 'deck', accent: '#60C0F0', glow: '#8B5CF6' },
  { id: 'living-ledger', number: '02', name: 'Living Training Ledger', family: 'swan', thesis: 'The workout is an evidence record first, with history and confidence beside every coaching choice.', signature: 'A provenance strip distinguishes observed, coach-confirmed, and suggested data.', layout: 'ledger', accent: '#C6A84B', glow: '#60C0F0' },
  { id: 'horizon-ribbon', number: '03', name: 'Horizon Ribbon', family: 'swan', thesis: 'Today, this week, and the active long-range plan read as one programming story.', signature: 'A seven-horizon ribbon exposes where this session belongs without another planner.', layout: 'timeline', accent: '#8B5CF6', glow: '#60C0F0' },
  { id: 'session-focus', number: '04', name: 'Session Focus', family: 'swan', thesis: 'A calm one-task-at-a-time logger with the Rolodex one keystroke away.', signature: 'The active exercise becomes a coaching stage while the rest collapse into a queue.', layout: 'focus', accent: '#4070C0', glow: '#8B5CF6' },
  { id: 'training-orbit', number: '05', name: 'Training Orbit', family: 'wild', thesis: 'Client signals orbit the workout core so every change visibly affects recommendations.', signature: 'Signal satellites reveal why Swan Coach changed the draft.', layout: 'orbit', accent: '#60C0F0', glow: '#C6A84B' },
  { id: 'swan-forge', number: '06', name: 'Swan Forge', family: 'wild', thesis: 'Exercises are materials, supersets are assemblies, and the session is forged spatially.', signature: 'Exercise ingots flow from Rolodex into warm-up, work, and recovery lanes.', layout: 'forge', accent: '#E5484D', glow: '#C6A84B' },
  { id: 'constellation-map', number: '07', name: 'Constellation Map', family: 'wild', thesis: 'Movement patterns become a map that makes balance, gaps, and repetition obvious.', signature: 'The session silhouette lights up as movement families gain coverage.', layout: 'map', accent: '#8B5CF6', glow: '#60C0F0' },
  { id: 'coach-concierge', number: '08', name: 'Coach Concierge', family: 'wild', thesis: 'A conversational review queue prepares drafts and missing-day suggestions for approval.', signature: 'Confidence cards show source, uncertainty, and affected dates before approval.', layout: 'concierge', accent: '#C6A84B', glow: '#8B5CF6' },
];
