/**
 * bracket.mjs — describe, see options, pick, refine.
 *
 * THE MISSING MIDDLE. Kimi K3's round-5 ruling, quoted because it was right:
 * "Three slices of rigor infrastructure, zero user-visible capability... 127
 * green tests and Sean still can't pick one of three pictures. That is the only
 * metric he will ever quote." The compiler was `describe`; the ledger was
 * `commit`; `see options` did not exist.
 *
 * WHY RE-ROLL AND NOT SEED. Seeds are dead on this model — probed with three
 * arms, same prompt + same seed gave different bytes. So N options from one
 * brief are N re-rolls of an identical prompt, and the natural variance IS the
 * spread. That is recorded honestly: every option row carries intent 'reroll'
 * and the same promptSha, so nobody later mistakes the spread for prompt
 * engineering.
 *
 * WHAT MAKES IT USABLE RATHER THAN DECORATIVE: every option writes its IMAGE TO
 * DISK and its path into the ledger row. Five images were generated before this
 * existed and all five were discarded — the system could describe what it made
 * and could not show it.
 *
 * FAILURE IS PARTIAL, NOT FATAL. One option failing a safety check must not
 * void the other two; a bracket of 2 is still a choice. Failures are recorded
 * as rows with status 'safety-reject' or 'error', so the rejection rate is
 * queryable rather than anecdotal.
 */

import { createHash } from 'node:crypto';
import { mkdirSync, writeFileSync, existsSync, readdirSync, statSync } from 'node:fs';
import { join } from 'node:path';
import { compileImage } from './swanPromptCompiler.mjs';
import { appendRun, buildRecord, readRuns, RUN_DIR } from './variantRun.mjs';
import { imageDimensions, toBuffer } from './imageDimensions.mjs';

export const IMAGE_DIR = join(RUN_DIR, 'images');

/** Extension from the format the bytes actually declare, never from a guess. */
function extFor(bytes) {
  const d = imageDimensions(bytes);
  return d ? ({ png: '.png', jpeg: '.jpg', webp: '.webp', gif: '.gif' }[d.format] || '.bin') : '.bin';
}

/**
 * Persist one image and return what the ledger needs to point at it.
 * Filename is the variantId, which is generated by this module and matches
 * `/^v_[0-9a-f]{16}$/` — so it cannot carry a path separator.
 */
export function saveImage(variantId, payload, root = process.cwd()) {
  const bytes = toBuffer(payload);
  if (!bytes.length) return { imageRef: null, imageSha: null, imageBytes: null };
  const dir = join(root, IMAGE_DIR);
  mkdirSync(dir, { recursive: true });
  const file = `${variantId}${extFor(bytes)}`;
  writeFileSync(join(dir, file), bytes);
  return {
    imageRef: join(IMAGE_DIR, file).split('\\').join('/'),
    imageSha: createHash('sha256').update(bytes).digest('hex').slice(0, 16),
    imageBytes: bytes.length,
  };
}

/**
 * Generate N options for one brief.
 *
 * @param {object} brief
 * @param {object} deps  { generate, capabilities }  — the provider, injected so
 *   this is testable without spending money. Not a default import: a module that
 *   can only be exercised by paying is a module that stays untested.
 * @param {object} [opts] { n = 3, root, runId }
 */
export async function generateBracket(brief, deps, opts = {}) {
  const { generate, capabilities } = deps;
  const { n = 3, root = process.cwd() } = opts;
  const runId = opts.runId || `r_${createHash('sha256')
    .update(`${brief.briefId}:${brief.text}`).digest('hex').slice(0, 10)}`;

  const caps = capabilities();
  const compiled = compileImage(brief, caps);          // throws on law violation
  const options = [];

  /**
   * PER-BRACKET COST CEILING — stop the bracket, not the wallet.
   *
   * Retries mean one option can now cost several times its nominal price, and a
   * provider having a bad day multiplies that across every option. Nothing
   * previously bounded the total: a bracket would keep buying until it ran out
   * of options to try.
   *
   * PROVENANCE: a generation is OBSERVED at $0.0037-$0.0061 (measured across
   * every run in this ledger; dearest was an image-input call at $0.006136). A
   * 3-option bracket at the top of that range is ~$0.018, so the default ceiling
   * of $0.50 tolerates roughly 27x the expected spend before refusing — loose
   * enough never to fire in normal use, tight enough that a runaway is bounded
   * in cents rather than discovered on an invoice.
   */
  const ceilingUsd = opts.maxSpendUsd ?? 0.50;
  let spent = 0;

  for (let i = 0; i < n; i += 1) {
    if (spent >= ceilingUsd) {
      options.push(appendRun({
        briefId: brief.briefId || 'unnamed', runId,
        provider: caps.provider, model: caps.modelVersion || caps.provider,
        serializer: compiled.promptStyle, promptText: compiled.promptText,
        status: 'error', intent: 'reroll', parentVariantId: null,
        notes: `E_SPEND_CEILING: stopped at $${spent.toFixed(4)} of $${ceilingUsd} after ${i} option(s)`,
      }, root));
      break;
    }
    const t0 = Date.now();
    const base = {
      briefId: brief.briefId || 'unnamed', runId,
      provider: caps.provider, model: caps.modelVersion || caps.provider,
      brainVersion: compiled.brainVersion, serializer: compiled.promptStyle,
      promptText: compiled.promptText, aspectRequested: compiled.aspect,
      // Every option is a re-roll of the SAME prompt. Stated, not implied.
      intent: i === 0 ? 'root' : 'reroll',
      parentVariantId: i === 0 ? null : options.find((o) => o.intent === 'root')?.variantId ?? null,
    };

    try {
      const res = await generate(compiled, { root });
      const rec = buildRecord({ ...base, status: 'ok' });
      const img = saveImage(rec.variantId, res.images[0], root);
      spent += res.costUsd || 0;
      options.push(appendRun({
        ...base, variantId: rec.variantId, status: 'ok',
        actualWidth: res.actualWidth, actualHeight: res.actualHeight,
        costUsd: res.costUsd, wallMs: Date.now() - t0, retries: res.retries ?? 0, ...img,
      }, root));
    } catch (e) {
      // A rejected option must not void the bracket. Two options is still a choice.
      options.push(appendRun({
        ...base,
        status: e.code === 'E_PROVIDER_SAFETY_REJECT' ? 'safety-reject' : 'error',
        wallMs: Date.now() - t0,
        safetyEvents: e.code === 'E_PROVIDER_SAFETY_REJECT' ? [{ code: e.code }] : [],
        notes: `${e.code}: ${String(e.message).slice(0, 160)}`,
      }, root));
    }
  }

  const ok = options.filter((o) => o.status === 'ok');
  return {
    runId,
    ceilingUsd,
    ceilingHit: options.some((o) => String(o.notes || '').startsWith('E_SPEND_CEILING')),
    promptText: compiled.promptText,
    options,
    ok,
    costUsd: ok.reduce((s, o) => s + (o.costUsd || 0), 0),
    // Honest about partial failure rather than reporting a clean count.
    failed: options.length - ok.length,
  };
}

/**
 * How big the artifact store has grown, and whether retention is overdue.
 *
 * WHY THIS EXISTS: a retention policy that has never executed is a DOCUMENT, not
 * a policy. `forge-prune.mjs` was written, tested, and then never run — so the
 * true statement about this store was "runs accumulate forever; a pruning script
 * exists and has never been used."
 *
 * This makes the check automatic and free: every generation reports the store's
 * size against the budget. DELETION stays manual and opt-in, because it is
 * irreversible and Rule 34 says so — but "nobody ever looked" is no longer one of
 * the failure modes.
 *
 * PROVENANCE for the default: generated images are OBSERVED at 1.7-2.4 MB each,
 * so 500 MB is roughly 200-300 images — months of ordinary use before a human is
 * ever asked to think about it.
 */
export function storeStatus(root = process.cwd(), budgetMb = 500) {
  // WALKS THE WHOLE ARTIFACT ROOT, not just IMAGE_DIR. The first version counted
  // only `forge-runs/images/` and reported 3.6 MB while 14.1 MB sat on disk —
  // the A/B harness writes to a SIBLING directory (`ab-avoid/`) that retention
  // never looked at. A budget that guards one subdirectory and lets another grow
  // without limit is not a budget; it is a budget-shaped object.
  const base = join(root, RUN_DIR);
  if (!existsSync(base)) return { files: 0, mb: 0, budgetMb, overBudget: false, dirs: [] };
  let bytes = 0;
  let files = 0;
  const dirs = new Set();
  const walk = (dir, label) => {
    let entries;
    try { entries = readdirSync(dir, { withFileTypes: true }); } catch { return; }
    for (const e of entries) {
      const p = join(dir, e.name);
      if (e.isDirectory()) { walk(p, label || e.name); continue; }
      if (!/\.(png|jpe?g|webp|gif)$/i.test(e.name)) continue;
      try { bytes += statSync(p).size; files += 1; if (label) dirs.add(label); } catch { /* raced deletion */ }
    }
  };
  walk(base, null);
  const mb = bytes / 1_048_576;
  return {
    files, mb: Number(mb.toFixed(1)), budgetMb, overBudget: mb > budgetMb,
    dirs: [...dirs].sort(),
  };
}

/** Fetch a variant by id prefix, so a human can type the first few characters. */
export function findVariant(idPrefix, root = process.cwd()) {
  const { runs } = readRuns(root);
  const hits = runs.filter((r) => r.variantId.startsWith(idPrefix));
  if (hits.length === 0) throw new Error(`No variant matches "${idPrefix}".`);
  if (hits.length > 1) {
    throw new Error(`"${idPrefix}" matches ${hits.length} variants — use more characters.`);
  }
  return hits[0];
}
