// Cache invalidation marker: 2025-06-30T17:38:16.066Z
// This file is automatically updated to force Vite to invalidate its module cache
// Do not edit this file manually

export const CACHE_VERSION = '2025-06-30T17:38:16.066Z';
