// Cache invalidation marker: 2025-06-09T20:00:35.133Z
// This file is automatically updated to force Vite to invalidate its module cache
// Do not edit this file manually

export const CACHE_VERSION = '2025-06-09T20:00:35.133Z';
