// Cache invalidation marker: 2025-05-20T21:54:27.129Z
// This file is automatically updated to force Vite to invalidate its module cache
// Do not edit this file manually

export const CACHE_VERSION = '2025-05-20T21:54:27.129Z';
