import React from 'react';
import styled from 'styled-components';
import { Camera, ChevronUp, HeartPulse, Send } from 'lucide-react';
import { ConceptProps, PrototypeNote, workoutRows } from './conceptShared';

const World=styled.div`min-height:calc(100vh - 96px);display:grid;place-items:center;padding:24px;background:radial-gradient(circle at 20% 20%,var(--stories-purple,#8b5cf6),transparent 30%),radial-gradient(circle at 80% 85%,var(--stories-pink,#e5488f),transparent 32%),var(--stories-night,#11111b);color:var(--stories-white,#ffffff);font-family:'Plus Jakarta Sans',sans-serif;`;
const Phone=styled.div`width:min(460px,100%);min-height:720px;border-radius:42px;padding:16px;background:linear-gradient(180deg,color-mix(in srgb,var(--stories-night,#11111b) 15%,transparent),var(--stories-night,#11111b));box-shadow:0 40px 100px color-mix(in srgb,var(--stories-night,#11111b) 70%,transparent);display:flex;flex-direction:column;`;
const Steps=styled.div`display:grid;grid-template-columns:repeat(5,1fr);gap:5px;i{height:3px;border-radius:4px;background:color-mix(in srgb,var(--stories-white,#ffffff) 28%,transparent)}i:first-child,i:nth-child(2){background:var(--stories-white,#ffffff)}`;
const Profile=styled.div`display:flex;align-items:center;gap:10px;padding:14px 2px;span{width:38px;height:38px;border-radius:50%;display:grid;place-items:center;background:linear-gradient(135deg,var(--stories-orange,#ff8a3d),var(--stories-pink,#e5488f));font-weight:800}`;
const Feature=styled.div`flex:1;border-radius:30px;padding:24px;background:linear-gradient(150deg,color-mix(in srgb,var(--stories-purple,#8b5cf6) 88%,transparent),color-mix(in srgb,var(--stories-pink,#e5488f) 78%,transparent));display:flex;flex-direction:column;justify-content:space-between;h2{font-size:clamp(42px,9vw,68px);line-height:.9;margin:16px 0}small{font-weight:700;text-transform:uppercase;letter-spacing:.12em}`;
const Cards=styled.div`display:grid;gap:8px;p{margin:0;padding:12px;border-radius:16px;background:color-mix(in srgb,var(--stories-night,#11111b) 32%,transparent);display:flex;justify-content:space-between}`;
const Reply=styled.button`min-height:52px;margin-top:12px;border:1px solid color-mix(in srgb,var(--stories-white,#ffffff) 44%,transparent);border-radius:999px;background:color-mix(in srgb,var(--stories-night,#11111b) 35%,transparent);color:var(--stories-white,#ffffff);font-weight:750;cursor:pointer;&:focus-visible{outline:3px solid var(--stories-white,#ffffff);outline-offset:2px}`;
export const AfterDarkStories:React.FC<ConceptProps>=({onAction})=><World><Phone aria-label="After Dark Stories workout interface"><Steps>{[1,2,3,4,5].map(n=><i key={n}/>)}</Steps><Profile><span>DC</span><div><strong>Demo Client</strong><br/><small>Coach story · now</small></div><Camera size={20}/></Profile><Feature><div><small><HeartPulse size={15}/> readiness changed the plan</small><h2>Today,<br/>we build control.</h2><PrototypeNote/></div><Cards>{workoutRows.map(row=><p key={row.name}><span>{row.name}</span><strong>{row.dose}</strong></p>)}</Cards></Feature><Reply onClick={()=>onAction('Stories opened the swipe-up Rolodex')}><ChevronUp size={18}/> Swipe into Rolodex <Send size={16}/></Reply></Phone></World>;
