import React from 'react';
import styled from 'styled-components';
import { ArrowUpRight, Feather } from 'lucide-react';
import { ConceptProps, PrototypeNote, workoutRows } from './conceptShared';

const Paper=styled.div`min-height:calc(100vh - 96px);padding:clamp(26px,5vw,90px);background:var(--atelier-paper,#f0eadc);color:var(--atelier-ink,#211d18);font-family:'Cormorant Garamond',Georgia,serif;`;
const Mast=styled.header`display:grid;grid-template-columns:1fr auto 1fr;align-items:end;border-bottom:1px solid var(--atelier-ink,#211d18);padding-bottom:12px;font-family:'Fira Code',monospace;font-size:11px;text-transform:uppercase;span:last-child{text-align:right}@media(max-width:700px){grid-template-columns:1fr;gap:8px;span:last-child{text-align:left}}`;
const Layout=styled.div`display:grid;grid-template-columns:minmax(0,1.5fr) minmax(260px,.5fr);gap:clamp(32px,6vw,100px);margin-top:50px;@media(max-width:850px){grid-template-columns:1fr}`;
const Headline=styled.h2`font-size:clamp(72px,12vw,190px);font-weight:400;font-style:italic;line-height:.72;letter-spacing:-.07em;margin:0 0 38px;`;
const Deck=styled.div`columns:2;column-gap:32px;font-family:'Plus Jakarta Sans',sans-serif;font-size:15px;line-height:1.75;@media(max-width:620px){columns:1}`;
const Folio=styled.aside`border-top:4px solid var(--atelier-ink,#211d18);padding-top:18px;h3{font-size:34px;font-weight:400;margin:0 0 20px}p{padding:14px 0;border-bottom:1px solid color-mix(in srgb,var(--atelier-ink,#211d18) 28%,transparent);margin:0;font-family:'Plus Jakarta Sans',sans-serif;display:flex;justify-content:space-between;gap:12px}`;
const Commission=styled.button`min-height:56px;width:100%;margin-top:24px;background:var(--atelier-ink,#211d18);color:var(--atelier-paper,#f0eadc);border:0;font:700 12px/1 'Fira Code',monospace;text-transform:uppercase;cursor:pointer;&:focus-visible{outline:3px solid var(--gilded-fern,#c6a84b);outline-offset:3px}`;
export const AtelierEditorial:React.FC<ConceptProps>=({onAction})=><Paper aria-label="Atelier Editorial workout interface"><Mast><span>Issue 042 · Training Arts</span><PrototypeNote/><span>Friday / Strength</span></Mast><Layout><article><Headline>The art of controlled force.</Headline><Deck><p><Feather size={17}/> Today’s program responds to readiness rather than forcing the calendar. The left knee signal reduces axial demand while maintaining the intent of the phase.</p><p>Three movements form the chapter: a grounded squat, an anti-rotation press, and a supported pull. Each earns its place.</p></Deck></article><Folio><h3>Today’s composition</h3>{workoutRows.map(row=><p key={row.name}><span>{row.name}</span><strong>{row.dose}</strong></p>)}<Commission onClick={()=>onAction('Atelier opened the movement folio')}>Edit the composition <ArrowUpRight size={16}/></Commission></Folio></Layout></Paper>;
