import React from 'react';
import styled from 'styled-components';
import { Activity, Command, Search } from 'lucide-react';
import { ConceptProps, PrototypeNote, clientSignals, workoutRows } from './conceptShared';

const Terminal=styled.div`min-height:calc(100vh - 96px);padding:clamp(18px,3vw,48px);background:var(--terminal-black,#050807);color:var(--terminal-green,#9cffb7);font-family:'Fira Code',monospace;`;
const Bar=styled.div`display:flex;justify-content:space-between;gap:18px;padding-bottom:14px;border-bottom:1px solid var(--terminal-green,#9cffb7);font-size:12px;`;
const Grid=styled.div`display:grid;grid-template-columns:minmax(230px,.55fr) minmax(460px,1.8fr) minmax(220px,.65fr);gap:1px;margin-top:24px;background:color-mix(in srgb,var(--terminal-green,#9cffb7) 25%,transparent);border:1px solid color-mix(in srgb,var(--terminal-green,#9cffb7) 25%,transparent);@media(max-width:1000px){grid-template-columns:1fr}`;
const Pane=styled.section`background:var(--terminal-black,#050807);padding:20px;h2{font-size:clamp(28px,4vw,60px);margin:0 0 18px;letter-spacing:-.06em}h3{font-size:12px;text-transform:uppercase;letter-spacing:.1em;color:var(--terminal-amber,#ffc857)}`;
const Metric=styled.div`padding:12px 0;border-bottom:1px dashed color-mix(in srgb,var(--terminal-green,#9cffb7) 30%,transparent);display:flex;justify-content:space-between;`;
const Table=styled.div`div{display:grid;grid-template-columns:44px minmax(150px,1fr) 150px 90px;gap:12px;padding:13px 0;border-bottom:1px solid color-mix(in srgb,var(--terminal-green,#9cffb7) 18%,transparent)}@media(max-width:620px){div{grid-template-columns:34px 1fr;span:nth-child(3),span:nth-child(4){grid-column:2}}}`;
const Execute=styled.button`min-height:52px;width:100%;margin-top:20px;border:1px solid var(--terminal-green,#9cffb7);background:var(--terminal-green,#9cffb7);color:var(--terminal-black,#050807);font:800 13px/1 'Fira Code',monospace;cursor:pointer;&:focus-visible{outline:3px solid var(--terminal-amber,#ffc857);outline-offset:3px}`;
export const CommandTerminal:React.FC<ConceptProps>=({onAction})=><Terminal aria-label="Command Terminal workout interface"><Bar><span>SWAN_OS / TRAINING_KERNEL / CLIENT_042</span><PrototypeNote/></Bar><Grid><Pane><h3>Signal stack</h3>{clientSignals.map(signal=><Metric key={signal}><span>{signal}</span><Activity size={15}/></Metric>)}</Pane><Pane><h3>Session compiler</h3><h2>STABILITY_<br/>STRENGTH</h2><Table>{workoutRows.map((row,i)=><div key={row.name}><span>0{i+1}</span><strong>{row.name}</strong><span>{row.meta}</span><span>{row.dose}</span></div>)}</Table><Execute onClick={()=>onAction('Terminal entered exercise search mode')}><Command size={16}/> EXECUTE: OPEN_ROLODEX</Execute></Pane><Pane><h3>Coach audit</h3><Metric><span>plan match</span><strong>96%</strong></Metric><Metric><span>knee load</span><strong>LOW</strong></Metric><Metric><span>missing logs</span><strong>01</strong></Metric><p><Search size={15}/> Every recommendation exposes its source.</p></Pane></Grid></Terminal>;
