import React from 'react';
import styled, { keyframes } from 'styled-components';
import { Crosshair, Gamepad2, ShieldCheck } from 'lucide-react';
import { ConceptProps, PrototypeNote, workoutRows } from './conceptShared';

const pulse=keyframes`50%{box-shadow:0 0 40px color-mix(in srgb,var(--mission-cyan,#60c0f0) 42%,transparent)}`;
const World=styled.div`min-height:calc(100vh - 96px);padding:clamp(20px,4vw,68px);background:radial-gradient(circle at 50% 20%,var(--mission-blue,#102b64),var(--mission-night,#070b18) 58%);color:var(--mission-white,#eaf7ff);font-family:'Sora',sans-serif;overflow:hidden;`;
const HUD=styled.header`display:flex;justify-content:space-between;align-items:center;gap:18px;text-transform:uppercase;letter-spacing:.12em;font-size:11px;`;
const Mission=styled.div`display:grid;grid-template-columns:minmax(230px,.55fr) minmax(0,1.45fr) minmax(220px,.5fr);gap:24px;align-items:center;max-width:1600px;margin:clamp(40px,8vh,100px) auto;@media(max-width:980px){grid-template-columns:1fr}`;
const Radar=styled.div`aspect-ratio:1;border-radius:50%;border:1px solid var(--mission-cyan,#60c0f0);background:repeating-radial-gradient(circle,color-mix(in srgb,var(--mission-cyan,#60c0f0) 12%,transparent) 0 1px,transparent 1px 36px),linear-gradient(90deg,transparent 49.7%,var(--mission-cyan,#60c0f0) 50%,transparent 50.3%);display:grid;place-items:center;animation:${pulse} 2.8s ease-in-out infinite;strong{font-size:64px}@media(prefers-reduced-motion:reduce){animation:none}`;
const Center=styled.section`h2{font-size:clamp(52px,8vw,118px);line-height:.78;letter-spacing:-.07em;text-transform:uppercase;margin:0 0 28px}h2 span{display:block;color:var(--mission-cyan,#60c0f0)}p{color:var(--mission-muted,#a8c8dc)}`;
const Quest=styled.div`display:grid;grid-template-columns:42px 1fr auto;gap:12px;align-items:center;padding:14px;margin:8px 0;border:1px solid color-mix(in srgb,var(--mission-cyan,#60c0f0) 24%,transparent);clip-path:polygon(10px 0,100% 0,100% calc(100% - 10px),calc(100% - 10px) 100%,0 100%,0 10px);background:color-mix(in srgb,var(--mission-blue,#102b64) 48%,transparent);`;
const Launch=styled.button`min-height:60px;width:100%;border:1px solid var(--mission-cyan,#60c0f0);clip-path:polygon(12px 0,100% 0,100% calc(100% - 12px),calc(100% - 12px) 100%,0 100%,0 12px);background:var(--wing-purple,#8b5cf6);color:var(--mission-white,#eaf7ff);font-weight:850;text-transform:uppercase;cursor:pointer;&:focus-visible{outline:3px solid var(--mission-cyan,#60c0f0);outline-offset:4px}`;
const Side=styled.aside`padding:20px;border-left:1px solid var(--mission-cyan,#60c0f0);strong{display:block;font-size:28px;margin:8px 0 24px}`;
export const ConsoleMission:React.FC<ConceptProps>=({onAction})=><World aria-label="Console Mission workout interface"><HUD><span><Gamepad2 size={16}/> Mission control</span><PrototypeNote/><span>Player: Demo Client</span></HUD><Mission><Radar><div><Crosshair size={28}/><strong>82</strong><small>READINESS</small></div></Radar><Center><p>MISSION 04 / STABILITY STRENGTH</p><h2>Build the<span>clean rep.</span></h2>{workoutRows.map((row,i)=><Quest key={row.name}><ShieldCheck size={20}/><span>Objective {i+1}<br/><strong>{row.name}</strong></span><b>{row.dose}</b></Quest>)}</Center><Side><small>MISSION REWARD</small><strong>Better data.<br/>Better next move.</strong><Launch onClick={()=>onAction('Mission loaded the movement armory')}>Open armory</Launch></Side></Mission></World>;
