import React from 'react';
import styled from 'styled-components';
import { Check, PenLine, Plus } from 'lucide-react';
import { ConceptProps, PrototypeNote, clientSignals, workoutRows } from './conceptShared';

const Book=styled.div`min-height:calc(100vh - 96px);padding:clamp(24px,5vw,82px);background-color:var(--field-paper,#eee9d8);background-image:linear-gradient(color-mix(in srgb,var(--field-blue,#295f9e) 12%,transparent) 1px,transparent 1px),linear-gradient(90deg,color-mix(in srgb,var(--field-blue,#295f9e) 12%,transparent) 1px,transparent 1px);background-size:24px 24px;color:var(--field-ink,#17365d);font-family:'Fira Code',monospace;`;
const Cover=styled.header`display:flex;justify-content:space-between;gap:18px;border-bottom:3px double var(--field-ink,#17365d);padding-bottom:14px;text-transform:uppercase;font-size:11px;`;
const Pages=styled.div`display:grid;grid-template-columns:minmax(240px,.55fr) minmax(0,1.45fr);gap:clamp(30px,6vw,100px);max-width:1450px;margin:50px auto;@media(max-width:850px){grid-template-columns:1fr}`;
const Margin=styled.aside`border-left:3px solid var(--field-red,#b54444);padding-left:22px;h2{font:italic 500 clamp(48px,7vw,96px)/.9 'Cormorant Garamond',serif;margin:0 0 30px;color:var(--field-red,#b54444)}p{padding:10px 0;border-bottom:1px dashed var(--field-blue,#295f9e)}`;
const Sheet=styled.section`h3{font-size:13px;text-transform:uppercase;letter-spacing:.12em;margin-bottom:24px}`;
const Entry=styled.div`display:grid;grid-template-columns:34px 1fr auto;gap:12px;align-items:start;padding:18px 0;border-bottom:2px solid color-mix(in srgb,var(--field-blue,#295f9e) 25%,transparent);span:first-child{width:24px;height:24px;border:2px solid var(--field-blue,#295f9e);display:grid;place-items:center}strong{font-size:18px}`;
const Write=styled.button`min-height:56px;width:100%;margin-top:28px;border:2px solid var(--field-ink,#17365d);background:transparent;color:var(--field-ink,#17365d);font:800 13px/1 'Fira Code',monospace;text-transform:uppercase;cursor:pointer;box-shadow:6px 6px 0 var(--field-ink,#17365d);&:focus-visible{outline:3px solid var(--field-red,#b54444);outline-offset:4px}`;
export const FieldManual:React.FC<ConceptProps>=({onAction})=><Book aria-label="Field Manual workout interface"><Cover><span><PenLine size={16}/> Coach field manual · sheet 042</span><PrototypeNote/></Cover><Pages><Margin><h2>Today’s working notes.</h2>{clientSignals.map(signal=><p key={signal}>{signal}</p>)}<p>Source: active plan + confirmed history.</p></Margin><Sheet><h3>Session checklist / Friday</h3>{workoutRows.map((row,i)=><Entry key={row.name}><span>{i===0&&<Check size={15}/>}</span><div><strong>{row.name}</strong><br/><small>{row.meta}</small></div><b>{row.dose}</b></Entry>)}<Write onClick={()=>onAction('Field Manual opened a blank Rolodex index card')}><Plus size={18}/> Add exercise from index</Write></Sheet></Pages></Book>;
