import React from 'react';
import styled from 'styled-components';
import { Flag, Gauge, RadioTower } from 'lucide-react';
import { ConceptProps, PrototypeNote, workoutRows } from './conceptShared';

const Wall=styled.div`min-height:calc(100vh - 96px);padding:clamp(18px,3vw,48px);background:var(--pit-black,#080808);color:var(--pit-white,#f4f4f0);font-family:'Sora',sans-serif;`;
const Timing=styled.header`display:grid;grid-template-columns:auto 1fr auto;gap:18px;align-items:center;border-bottom:4px solid var(--pit-red,#e5484d);padding-bottom:12px;text-transform:uppercase;font-size:11px;letter-spacing:.11em;span:nth-child(2){height:1px;background:color-mix(in srgb,var(--pit-white,#f4f4f0) 20%,transparent)}`;
const Grid=styled.div`display:grid;grid-template-columns:minmax(250px,.55fr) minmax(0,1.45fr);gap:1px;background:color-mix(in srgb,var(--pit-white,#f4f4f0) 14%,transparent);margin-top:20px;border:1px solid color-mix(in srgb,var(--pit-white,#f4f4f0) 14%,transparent);@media(max-width:880px){grid-template-columns:1fr}`;
const Panel=styled.section`background:var(--pit-black,#080808);padding:24px;h2{font-size:clamp(54px,8vw,126px);line-height:.75;letter-spacing:-.08em;margin:12px 0 32px;text-transform:uppercase}h3{font:700 12px/1 'Fira Code',monospace;color:var(--pit-red,#e5484d);text-transform:uppercase;letter-spacing:.12em}`;
const Dial=styled.div`display:grid;grid-template-columns:1fr auto;align-items:end;padding:18px 0;border-bottom:1px solid color-mix(in srgb,var(--pit-white,#f4f4f0) 14%,transparent);strong{font:700 46px/1 'Fira Code',monospace;color:var(--pit-lime,#d8ff3e)}`;
const Lap=styled.div`display:grid;grid-template-columns:52px 1fr 120px 90px;gap:14px;padding:16px 0;border-bottom:1px solid color-mix(in srgb,var(--pit-white,#f4f4f0) 14%,transparent);font-family:'Fira Code',monospace;span:first-child{color:var(--pit-red,#e5484d)}@media(max-width:650px){grid-template-columns:42px 1fr;span:nth-child(n+3){grid-column:2}}`;
const Radio=styled.button`min-height:56px;width:100%;margin-top:24px;border:0;background:var(--pit-red,#e5484d);color:var(--pit-white,#f4f4f0);font-weight:850;text-transform:uppercase;cursor:pointer;&:focus-visible{outline:3px solid var(--pit-lime,#d8ff3e);outline-offset:3px}`;
export const PitWall:React.FC<ConceptProps>=({onAction})=><Wall aria-label="Pit Wall workout interface"><Timing><span><Flag size={16}/> SWAN PERFORMANCE</span><span/><PrototypeNote/></Timing><Grid><Panel><h3>Live telemetry</h3><Dial><span>Readiness<br/><small>optimal window</small></span><strong>82</strong></Dial><Dial><span>Knee signal<br/><small>load modifier</small></span><strong>2.0</strong></Dial><Dial><span>Plan match<br/><small>session integrity</small></span><strong>96%</strong></Dial></Panel><Panel><h3>Session strategy / lap 04</h3><h2>Control<br/>the load.</h2>{workoutRows.map((row,i)=><Lap key={row.name}><span>L{i+1}</span><strong>{row.name}</strong><span>{row.meta}</span><b>{row.dose}</b></Lap>)}<Radio onClick={()=>onAction('Pit Wall called the Rolodex strategy channel')}><RadioTower size={18}/> Radio: request movement <Gauge size={18}/></Radio></Panel></Grid></Wall>;
