import React from 'react';
import styled from 'styled-components';
import { Box, Layers3, MoveUpRight } from 'lucide-react';
import { ConceptProps, PrototypeNote, clientSignals, workoutRows } from './conceptShared';

const Space=styled.div`min-height:calc(100vh - 96px);padding:clamp(22px,4vw,70px);background:radial-gradient(circle at 50% 10%,var(--spatial-sky,#c7e8ff),var(--spatial-mist,#e9edf5) 42%,var(--spatial-deep,#b8c2d8));color:var(--spatial-ink,#141821);font-family:'Plus Jakarta Sans',sans-serif;perspective:1200px;overflow:hidden;`;
const Nav=styled.div`display:flex;justify-content:space-between;align-items:center;color:var(--spatial-ink,#141821);`;
const Scene=styled.div`display:grid;grid-template-columns:minmax(250px,.55fr) minmax(420px,1.45fr) minmax(230px,.55fr);gap:clamp(20px,4vw,64px);align-items:center;max-width:1700px;margin:clamp(40px,8vh,100px) auto;@media(max-width:1000px){grid-template-columns:1fr}`;
const Glass=styled.section`padding:24px;border:1px solid color-mix(in srgb,var(--spatial-white,#ffffff) 70%,transparent);border-radius:32px;background:color-mix(in srgb,var(--spatial-white,#ffffff) 42%,transparent);box-shadow:0 30px 80px color-mix(in srgb,var(--spatial-ink,#141821) 18%,transparent);backdrop-filter:blur(30px) saturate(1.2);`;
const Orb=styled(Glass)`aspect-ratio:1;border-radius:50%;display:grid;place-items:center;text-align:center;transform:rotateY(8deg) rotateX(5deg);strong{display:block;font-size:clamp(70px,8vw,120px);letter-spacing:-.08em}p{margin:0}`;
const Canvas=styled(Glass)`transform:translateZ(30px);h2{font-size:clamp(46px,7vw,100px);line-height:.85;letter-spacing:-.07em;margin:0 0 32px}article{display:grid;grid-template-columns:1fr auto;gap:12px;padding:15px 0;border-bottom:1px solid color-mix(in srgb,var(--spatial-ink,#141821) 12%,transparent)}`;
const Chip=styled.button`min-height:50px;width:100%;margin-top:10px;border:1px solid color-mix(in srgb,var(--spatial-white,#ffffff) 80%,transparent);border-radius:999px;background:color-mix(in srgb,var(--spatial-white,#ffffff) 50%,transparent);color:var(--spatial-ink,#141821);font-weight:750;cursor:pointer;&:focus-visible{outline:3px solid var(--wing-purple,#8b5cf6);outline-offset:2px}`;
export const SpatialStudio:React.FC<ConceptProps>=({onAction})=><Space aria-label="Spatial Studio workout interface"><Nav><strong><Layers3 size={18}/> Spatial training</strong><PrototypeNote/></Nav><Scene><Orb><div><Box size={26}/><strong>82</strong><p>readiness volume</p></div></Orb><Canvas><small>FRIDAY · DEMO CLIENT</small><h2>Shape the session in space.</h2>{workoutRows.map(row=><article key={row.name}><span><strong>{row.name}</strong><br/><small>{row.meta}</small></span><b>{row.dose}</b></article>)}</Canvas><Glass><h3>Context satellites</h3>{clientSignals.map(signal=><Chip key={signal} onClick={()=>onAction(`${signal} expanded in spatial context`)}>{signal} <MoveUpRight size={15}/></Chip>)}</Glass></Scene></Space>;
