import React from 'react';
import styled from 'styled-components';
import { ArrowRight, Zap } from 'lucide-react';
import { ConceptProps, PrototypeNote, workoutRows } from './conceptShared';

const Poster = styled.div`min-height:calc(100vh - 96px);padding:clamp(24px,4vw,72px);overflow:hidden;background:var(--velocity-black,#090909);color:var(--velocity-cream,#f6f1e6);font-family:'Sora',sans-serif;position:relative;&:before{content:'TRAIN';position:absolute;right:-3vw;top:7vh;font:900 clamp(140px,28vw,520px)/.7 'Plus Jakarta Sans',sans-serif;color:color-mix(in srgb,var(--velocity-cream,#f6f1e6) 4%,transparent);transform:rotate(-7deg);pointer-events:none}`;
const Header = styled.div`position:relative;display:flex;justify-content:space-between;align-items:center;border-bottom:2px solid var(--velocity-cream,#f6f1e6);padding-bottom:14px;`;
const Body = styled.div`position:relative;display:grid;grid-template-columns:minmax(0,1.55fr) minmax(280px,.45fr);gap:40px;margin-top:38px;@media(max-width:850px){grid-template-columns:1fr}`;
const Title = styled.h2`margin:0;font:900 clamp(70px,13vw,220px)/.72 'Plus Jakarta Sans',sans-serif;letter-spacing:-.085em;text-transform:uppercase;span{display:block;color:var(--velocity-red,#e5484d);margin-left:10vw}`;
const Prescription = styled.div`align-self:end;border-left:2px solid var(--velocity-red,#e5484d);padding-left:20px;h3{font-size:28px;margin:0 0 22px}p{display:grid;grid-template-columns:1fr auto;gap:18px;padding:14px 0;margin:0;border-bottom:1px solid color-mix(in srgb,var(--velocity-cream,#f6f1e6) 20%,transparent)}`;
const Launch = styled.button`position:relative;min-height:60px;margin-top:30px;width:100%;border:0;background:var(--velocity-lime,#d8ff3e);color:var(--velocity-black,#090909);font:850 15px/1 'Sora',sans-serif;text-transform:uppercase;cursor:pointer;&:focus-visible{outline:4px solid var(--velocity-red,#e5484d);outline-offset:4px}`;
export const VelocityPoster:React.FC<ConceptProps>=({onAction})=><Poster aria-label="Velocity Poster workout interface"><Header><strong>NO EXCUSES / SESSION 04</strong><PrototypeNote/></Header><Body><div><Title>Own<span>the set.</span></Title><p><Zap size={18}/> Knee-aware strength · 42 minute target</p></div><Prescription><h3>Today’s work.</h3>{workoutRows.map((row,i)=><p key={row.name}><span>0{i+1} {row.name}</span><strong>{row.dose}</strong></p>)}<Launch onClick={()=>onAction('Velocity launched the high-energy exercise wall')}>Build the next move <ArrowRight size={18}/></Launch></Prescription></Body></Poster>;
